### ISSUE TITLE
Messages are rendered differently on iOS and OS X. But shouldn't.

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-webapp#10]
Wire for Mac (or Web) appears to be rendering messages differently than the native client on iOS.

Given:
- A message containing `¯\_(ツ)_/¯`.

When:
- On iOS.

Then:
- The message shows up as `¯\_(ツ)_/¯`.

---

Given:
- A message containing `¯\_(ツ)_/¯`.

When:
- On OS X or Web.

Then:
- The message shows up as `¯_(ツ)_/¯`.

---

Given:
- A message containing `¯\\_(ツ)_/¯`.

When:
- On iOS.

Then:
- The message shows up as `¯\\_(ツ)_/¯`.

---

Given:
- A message containing `¯\\_(ツ)_/¯`.

When:
- On OS X or Web.

Then:
- The message shows up as `¯\_(ツ)_/¯`.

---

Same thing for `foo _bar_ baz`, which shows up as `foo _bar_ baz` on iOS and as `foo bar baz` (with _`bar`_ in _italics_) on OS X or the web.

---

The web app seems to have some basic support for markdown-flavored formatting, which the native client lacks.

**Comment by bennycode** [comment]
Hi @regexident, thank you very much for making us aware of this issue. We added your scenario to our test suite with this **Pull Request**: https://github.com/wireapp/wire-webapp/pull/16

Thank you very much — Good job!

Benny
