### ISSUE TITLE
Add option to configure Language in settings 

### ISSUE THREAD

**Issue by Aikatsui** [wireapp/wire-webapp#10092]
Currently we cannot configure language in wire-web similar desktop app etc but that feature available on world top social media platforms, email providers (gmail, protonmail), communication services (discord, slack) and etc (those are web apps).
It's not necessary to persistence (the selection)

**Comment by bennycode** [comment]
Hi @Aikatsui, you can change languages in our webapp by using an "ISO-639-1" language identifier with the "hl" parameter.

Try:
- https://app.wire.com/auth/?hl=en
- https://app.wire.com/auth/?hl=de

**Comment by Aikatsui** [comment]
@bennycode this doesn't work with `ja`, `si`, `id` etc and more [crowdin.com/./wire-webapp](https://crowdin.com/project/wire-webapp ), why?
however such problem doesn't have with eg: desktop app.
