### ISSUE TITLE
Hide message content on notifications

### ISSUE THREAD

**Issue by Nuruddinjr** [wireapp/wire-webapp#101]
While focusing on privacy, I believe Message content should also be private on notifications.
[ Feature request ]

**Comment by notNSANE** [comment]
Yeah, both Telegram and Whatsapp have this option and I always enable it.
Displays a browser notification that says something like "X messaged you" without showing the actual message.

**Comment by helenakos** [comment]
Hey @Nuruddinjr, thanks for the request! Very valid point, I'm noting it down for the future 👍

**Comment by gregor** [comment]
@Nuruddinjr Ths feature has now made it to production. Restart the app and go to Preferences -> Options to choose to hide sender name and message content in notifications.

**Comment by Nuruddinjr** [comment]
Great! Thank you!
