### ISSUE TITLE
Last update → Impossible to archive conversation

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1012]
Since yesterday I cannot archive current conversation. Left tab shows everything is archived but conversation remains in the main tab. Clicking on and off settings makes it go away. This issue appeared in "Version 2017-04-05".

**Comment by herrmannplatz** [comment]
Thanks, we already saw it and fix is coming.

**Comment by ghost** [comment]
Today's update doesn't fix this issue…
