### ISSUE TITLE
Keep getting Error 207 in chats

### ISSUE THREAD

**Issue by jszoja** [wireapp/wire-webapp#10133]
Wire version: Version 3.21.2936(desktop) / 3.60.960(Android)
Wire for Web Version 2020.11.30.11.35(desktop)
Operating system: Ubuntu 20.04.1 LTS 64bit, GNOME 3.36.3 and Android 10 One UI 2.5 
Which antivirus software do you have installed: none
What steps will reproduce the problem?

0. Have the both desktop and android apps opened  
1. Type message on desktop 
2.  Leave pc - sleep mode might kick in?
3.  Come back and notice the error on desktop - last received message:
  - (ERROR: 207 ID: 72C1EB897012754B)
4. Check mobile and it is fine for last message, but the previous messages have the same error?
  - but they were fine before?

What is the expected result?
I should see correct messages on both devices all the time.

What is the actual result?
- messages correctly displayed on one device have errors on the other one and vice-versa

Please provide any additional information below. Attach a screenshot if possible.
- I'm using vpn, but left it opened all the time. Could ubuntu turn it off temp. on sleep?
- 'reset session' never helped on desktop

**Comment by StefanBoehme** [comment]
The same is happening for me. I am using Ubuntu Ubuntu 20.10 64bit and Android 11. Wire had been running stable and without any errors for quite some years. However, starting 3 weeks ago I regularly experience the same behaviour @jszoja described.

**Comment by bennycode** [comment]
@jszoja if you click on "Reset Session" and then write a message to the other participant, will the other side then receive your message?

**Comment by jszoja** [comment]
Sorry, I no longer use the wire app so cannot test.

From what i remember the reset session  button was throwing some error
advising to try again later or contact Support.

Kind regards,
Jan
