### ISSUE TITLE
The project doesn't run

### ISSUE THREAD

**Issue by zhongzhi206** [wireapp/wire-webapp#10178]
[![rGmwWj.png](https://s3.ax1x.com/2020/12/17/rGmwWj.png)](https://imgchr.com/i/rGmwWj)
Store picture view operation information

**Comment by ffflorian** [comment]
Hi @zhongzhi206, can you please add the `Webapp-error.log` file? Otherwise we won't know what's going on.
Also, what did you try to achieve and which commands did you run?

**Comment by zhongzhi206** [comment]
> @ zhongzhi206，您好，能否添加`Webapp-error.log`文件？否则，我们将不知道发生了什么。
> 另外，您尝试达到什么目的以及运行了哪些命令？

[![rqR759.png](https://s3.ax1x.com/2020/12/30/rqR759.png)](https://imgchr.com/i/rqR759)
ts-node is NOT AVAILABLE in PATH，What shall I do？

**Comment by zhongzhi206** [comment]
> Hi @zhongzhi206, can you please add the `Webapp-error.log` file? Otherwise we won't know what's going on.
> Also, what did you try to achieve and which commands did you run?

Executed command：yarn start:prod

**Comment by zhongzhi206** [comment]
> Hi @zhongzhi206, can you please add the `Webapp-error.log` file? Otherwise we won't know what's going on.
> Also, what did you try to achieve and which commands did you run?

Executed command：yarn start:prod
