### ISSUE TITLE
Strange messages and missing messages since last update

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-webapp#1018]
I updated last night to version 2.11.2685.
This morning while I was using it, I saw that all my conversations display a message saying "You haven't used this device for a while. Some messages may not appear here". This is false because I use this device almost every day, and I definitely used it yesterday.
On top of that (this may be a different issue, or maybe they're related), some of the messages I sent using the pc* this morning do not appear on my Android phone. However, those same messages were sent correctly to the recipients (who in fact replied).

*I use the Linux app

**Comment by herrmannplatz** [comment]
Thanks for reporting and sorry for the inconvenience. You havent missed any message. Its just diplayed incorrectly. This should be fixed with #1015.
