### ISSUE TITLE
Send after network disruption fails

### ISSUE THREAD

**Issue by fungs** [wireapp/wire-webapp#10362]
## Your Account Type
- [x] Wire Personal Account

## What steps will reproduce the problem?
Open wire app in (Chromium/embedded electron) web browser session, hibernate the computer, wake it up after a while and send the message. The message is sent but hangs forever. You have to reload the app, send the message as new and remove the hold hanging message, which otherwise will never disappear.

Happening since a few weeks until now.

## What is the expected behavior?
The message is sent, and you get a reception notice.

## Which browser are you using?
See above.

## Installed browser addons
None

**Comment by bennycode** [comment]
Thanks for your report. We fixed this issue with an update of our core messaging component: https://github.com/wireapp/wire-webapp/pull/11123

**Comment by fungs** [comment]
Great, I haven't seen this error again, lately.
