### ISSUE TITLE
Feature request: Login by using GET-parameter

### ISSUE THREAD

**Issue by user9209** [wireapp/wire-webapp#1076]
Hello,

it would be nice for the web client to allow inserting the username and password by using GET-parameters like:
'https://app.wire.com/auth/#login?username=demo&password=test'

So you can use bookmarks to directly login without user interaction.

For more security:
Set only the username to fill in automatically but asking for the password.

Thanks in Advance

By the way: 
If you encode the password with base64, special chars in the password are easy to handle and the password is not directly human readable. But to use it you must encode your password in the URL. Maybe plain text passwords are better.

**Comment by gregor** [comment]
What is keeping you from using our desktop apps?

**Comment by user9209** [comment]
- For example the .deb-installer currently needs admin rights, as workaround you can extract the binary from the deb-archiv or use the web app.
- On systems where no apps available for example bada (https://en.wikipedia.org/wiki/Bada)

For testing:
- desktop app currently does not support multi-user, so use desktop app with main profile and web browser with other profile
- To send friends a link with login details for easy testing

**Comment by max-baz** [comment]
If you are bound to use webapp, I suggest you look into password managers. The markup on login page is pretty good now, password managers are easily able to fill username and password with 0 or 1 click, and even press the "Log in" button for you.

**Comment by user9209** [comment]
The possibility of using GET-Params would be much easier, but I can understand that there are some workarounds to get similar behavior.
I close this Issue now.
Maybe in the future this feature can be added.
