### ISSUE TITLE
Swagger API

### ISSUE THREAD

**Issue by segahm** [wireapp/wire-webapp#1091]
In the code there are references to the swagger-ui. Seems like the code supports Swagger code gen. What is the url for generating swagger API documentation?

**Comment by bennycode** [comment]
Hi @segahm, thanks for showing interest in our Swagger API. You have very sharp eyes! ;D

We do have a generated Swagger API but unfortunately it's only available internally here at Wire. We just started to [opensource our server code](https://medium.com/@wireapp/open-sourcing-wire-server-code-ef7866a731d5). Part of the further publication of our server code could be releasing our Swagger API. But there are no official plans yet. 

Please follow us on [medium](https://medium.com/@wireapp) to get updates about this topic as soon as we have them. 📰 

May I ask what you want to do with our API documentation? There is a [webapp-core](https://github.com/wireapp/wire-webapp-core) module (which is in a very early stage) which shows some of our endpoints. Maybe it suits your needs. 

Example: https://github.com/wireapp/wire-webapp-core/blob/v0.2.0/src/main/js/user/UserAPI.js

**Comment by segahm** [comment]
Thanks @bennyn. I am already subscribed to the updates, so will be looking after them on Medium in the future.

Re: API - just a better way to understand the way the web client actually works. So webapp-core and  server code is probably beyond the scope for now. I am building a front-end on top of your existing web client. So far really liking the architecture choices, but sometimes struggling to keep memory of how everything works without making changes to the original code. Documentation would be helpful.
