### ISSUE TITLE
How does Authentication work

### ISSUE THREAD

**Issue by segahm** [wireapp/wire-webapp#1092]
Is there a description of how Wire's Authentication works? I would like to use Wire's authentication to authenticate users into my application on the same domain that I am hosting the chat client. Two questions:
1) How do I grab user's identifier?
2) How to forward users for authentication with pre-filled email/phone information?

**Comment by bennycode** [comment]
@segahm We are working on an API library which can be used by third parties: [wire-web-api-client](https://github.com/wireapp/wire-web-api-client)

You can see there how authentication is done:
- https://github.com/wireapp/wire-web-api-client/blob/v0.0.21/src/ts/core/WireAPIClient.ts#L43
