### ISSUE TITLE
Unable to import Android Backup on PC (GNU/Linux)

### ISSUE THREAD

**Issue by fekir** [wireapp/wire-webapp#10966]
Wire version:  3.24.2939
Wire for web version: 
Operating system: Debian GNU/Linux bullseye
Which antivirus software do you have installed: 

What steps will reproduce the problem?

1. Backup conversations from Android App (Version 3.66.985)
2. Copy backup on PC (GNU/Linux)
3. Restore from Backup on Wire on PC (GNU/Linux)

What is the expected result?

Should be able to import backup

What is the actual result?

````
Something went wrong
Your history could not be restored.
`````

Please provide any additional information below. Attach a screenshot if possible.

I've installed the app on the PC, .
During an update I got logged out, that's why I've made a backup from the Android App, where this did not happen

**Comment by ffflorian** [comment]
Hi @fekir, importing an Android backup is currently not possible, see https://support.wire.com/hc/en-us/articles/360000824805-Back-up-your-conversation-history. I filed this under feature requests.

**Comment by fekir** [comment]
Is it possible to convert the android backup to a pc one? What format are those?
Otherwise is there anything one can do to use a backup?

**Comment by ffflorian** [comment]
AFAIK it's not possible to convert the backup, sorry.
The desktop backup is basically a renamed zip file with events and metadata in JSON format in it. Please ask @makingthematrix about the Android backup format.
