### ISSUE TITLE
[Bug] During a call the video feed freezes while a picture is being uploaded via Ctrl+V (audio works)

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#1098]
I was on a video call, and after pasting an image with Ctrl+V the video feed froze for both parties while the image was uploading. We were able to hear each other though, and the video resumed when the image finished uploading. I could reproduce it several times with different images, they just have to be large enough to take a few seconds to upload for you to observe the bug.

The issue didn't seem to reproduce when I uploaded a different image using the dedicated button in the bottom (i.e. not with Ctrl+V), although it was a smaller image. Need to double check.

**Comment by gregor** [comment]
Encryption is resource intensive and blocking the thread. We continue to improve in this area and move it off the main thread but it is nothing that will be fixed short term.

**Comment by max-baz** [comment]
I'm just curious, do you know how is it happening that audio is not freezing, but video is?
Also seems related: https://github.com/wireapp/wire-desktop/issues/586
