### ISSUE TITLE
Bad kerning for emoji

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-webapp#11]
The trailing kerning of Emoji glyphs seems to be a bit too narrow in the OS X client as well as the web client when accessed via Chrome.

Example:

Given a message like this: `Foo😃bar 🤓😎` the bigrams `😃b` and `🤓😎` both seem to overlap internally.

This seems to be a rendering bug in Chromium's Blink engine (as it doesn't happen in – say – Safari). However since Electron (which the OS X client is built upon) uses Chromium, it ends up as a text glitch in Wire.

**Comment by bennycode** [comment]
Hi @regexident, when it is a Chromium bug, then it needs to be filed here: https://chromiumbugs.appspot.com/, no?

**Comment by regexident** [comment]
While I agree that the bug would have to be fixed in (and reported to) Chromium, it deteriorates the user experience of Wire (an emoji-heavy app, due to its nature) regardless of the bug's origin and might thus be worth a temporary work-around fix.

**Comment by bennycode** [comment]
I just checked it and the rendering doesn't look to bad:

**Screenshot:**
![screenshot](https://cloud.githubusercontent.com/assets/469989/17171797/833e90de-53f2-11e6-95b2-346de18207c5.png)

So we will wait until the kerning is fixed in Chromium. This seems to be the most efficient way.

**Comment by regexident** [comment]
The kerning in your screenshot is totally fine, actually.

This is how emojis look for me in OS X client and Chrome browser however:

![emoji](https://cloud.githubusercontent.com/assets/138017/17186491/ce5c294e-5435-11e6-98d3-eec3bc3d70bf.png)
