### ISSUE TITLE
Chat window doesn't always scroll down when a new message is received.

### ISSUE THREAD

**Issue by MrSuttonmann** [wireapp/wire-webapp#1106]
I have noticed that Wire doesn't always scroll down automatically when I receive a new message, even if I'm already at the bottom of the chat.

It should scroll down to show the new messages when you're already at the bottom of the chat window.

This behavior is apparent in Chrome, Firefox and Opera.

**Comment by MrSuttonmann** [comment]
I've done a bit more research on this. It only occurs if the window has focus. If I'm on another tab, or click away from the window, the chat window will scroll down as expected - otherwise it malfunctions.

**Comment by MrSuttonmann** [comment]
@bennyn - do you know if this is being looked at? Although it seems a small detail it is incredibly frustrating. :smile:

**Comment by gregor** [comment]
@plinkpaste Do you still see this issue? We have since added a threshold to the check, whether a chat was scrolled to bottom when you receive a new message to decide if we should scroll that new message into the view.

**Comment by gregor** [comment]
We have made some additional improvements regarding this in the latest release. With the changes and not further feedback we currently consider this issue to be fixed. Please update if it still happens to you.
