### ISSUE TITLE
Update bar 'what's new' points to unreachable domain for users in China

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-webapp#1108]
I have commented on other posts about the use of the 3rd party domain 'medium.com' as it is not reachable for users in China, nor is it under the control of Wire.

It is my opinion that all updates, all information about Wire should be kept under the control of Wire thus only on the domain controlled by Wire, so please change the 'what's new' to a url on the Wire domain.

A. Users lose privacy to a party nothing to do with Wire
B. some countries will render 'social network' domains unreachable

**Comment by helenakos** [comment]
@aquatooth Thanks for letting us know. 

I'm going to take this further internally and close this issue. If you notice any other irregularities please feel free to open an issue. Thanks!
