### ISSUE TITLE
Connection sur application web par navigateur.

### ISSUE THREAD

**Issue by ilorium** [wireapp/wire-webapp#1111]
Bonjour,
Préambule.
Oui, ceci est en français, et il serait bien agréable que vous fassiez l'effort d'une traduction du forum et de l'application par navigateur.
Et vous serez tout aussi courtois de me répondre dans ma langue.
Merci.

Maintenant, mon soucis du jour.
Impossible de se connecter par l'interface web disponible pour un navigateur (ici Firefox).
Mes identifiants renseignés, aucune action visible sur la page lors de la validation.
Aucun message d'erreur. Rien.
J'ai bien lu #261 (qui, comme pratiquement l'ensemble des topics, est clôt quand vous estimez que la conversation est close ! (et mer...ci pour les autres) , recommandant, pour ne pas accéder à une session temporaire, de ne pas se connecter par "/auth", mais la page est renvoyée automatiquement et systématiquement sur "/auth".

Commençons par ceci, avant d'aborder les sauvegardes d'historiques, ...

Et mon billet d'humeur (et pourtant, dieu sait que je prêche pour que mes contacts utilise ce bel outil)
...  sauvegardes d'historiques, que JE VEUX, parce que je suis le client et utilisateur et que je désire pouvoir librement choisir si oui ou non je transfère, archive, exporte MES données.
On vous demande de sécuriser nos données, pas de nous en priver !
J'adore cette application, mais je déteste votre état d'esprit. Vous transformez le concept de sécurité des données (et des utilisateurs) en une paranoïa excessivement sécuritaire à l'encontre et au détriment de vos adhérents.
En politique cela se nomme ... bien malheureusement!
Bien cordialement.

**Comment by david-wire** [comment]
Bonjour,

Que se passe-t-il si vous:
- Renseignez vos identifiants
- Ouvrez la [console](https://developer.mozilla.org/fr/docs/Outils/Console_Web/Opening_the_Web_Console) Firefox
- Cliquez sur 'Log in'
Remarquez vous des erreurs dans la console? Merci aussi de vérifier que vous n'utilisez pas le mode _Navigation privée_ sur Firefox car il est incompatible avec IndexedDB, que nous utilisons (il s'agit de ce [problème](https://bugzilla.mozilla.org/show_bug.cgi?id=781982), non résolu à ce jour. Il est nécessaire d'utiliser les [paramètres personnalisés](https://support.mozilla.org/fr/kb/parametres-vie-privee-historique-pas-pister#w_utiliser-les-paramaetres-personnalisaes-pour-lhistorique) pour l'historique à la place.

Concernant la sauvegarde de l'historique, nous avons commencé à travailler sur ce sujet (au niveau du design dans un premier temps). 
Veuillez également remarquer que #261 a été fermée par l'utilisateur, et que nous laissons généralement les "issues" ouvertes si elles demandent plus de recherche ou si nous n'avons pas de solution.
Nous travaillons aussi sur la traduction de l'application web, merci de votre patience. 
Bien à vous.
