### ISSUE TITLE
Perf bug: the `three-dots.less` animation causes huge CPU consumption and drains battery

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#1112]
The animation in `three-dots.less` is the reason for https://github.com/wireapp/wire-desktop/issues/135 (or one of them).
This has a _very serious_ effect on battery life, please fix it ASAP.

To reproduce: 
- send an image, preferably a large one
- send like 15 text messages, so that image goes up from the viewport
- switch to a different conversation, and then back
- now the `three-dots` animation is playing on that image, even though the image is not in the viewport. The CPU usage is 10% - 30%, depending on the number of images you have in the conversation.
- scroll above to load all images - as soon as the last image was loaded, all `three-dots` animations are removed, and CPU usage is 0%.
- alternatively, just execute `jQuery(".image-placeholder-icon").remove()` in the console to achieve the same effect.

I simply comment out these three lines, and the steps above result in 0% CPU usage.
```
  & > span:nth-child(1) {animation: animation-first-dot 1.4s linear infinite;}
  & > span:nth-child(2) {animation: animation-second-dot 1.4s linear infinite;}
  & > span:nth-child(3) {animation: animation-third-dot 1.4s linear infinite;}
```

Let's find out how to disable this animation for elements outside of the viewport. 
Perhaps also check if a simple 1kb gif will have less effect on CPU than this css animation.

If neither of the above steps are possible, I would much prefer to see static unanimated three dots to get a truly longer battery life.

**Comment by anatoli26** [comment]
A gif would be a quick solution, though the best way IMO is to implement a download progress indicator like in mobile apps. When something is not immediately available to the user (e.g. a video downloading), the more feedback you give him/her, the better.

**Comment by roberdorfer** [comment]
Agree with the ideal of the progress indicator. It can be frustrating at times to not know what's going on. A progress bar would help with that.

**Comment by max-baz** [comment]
I'm OK with further improvements, let's only agree to deal with the performance issue first, get our CPU usage down to 0% ASAP with whatever simplest approach is acceptable, and once we are there think of how to make it even better :+1: 

Getting battery life improved is very important, switching from 3 dots to a fancy progress bar is less important, and I wouldn't want to delay the first one because of the second 🙂

**Comment by herrmannplatz** [comment]
@maximbaz yes, i also realized that and already started changing the behaviour to only show the three dots when the image is actually loading and in the viewport. This is done for collection and i will continue with conversation assets as well.

**Comment by roberdorfer** [comment]
@herrmannplatz

I'd argue that the animation should be removed completely since it's now been proven to cause mayhem on dattery. It should not be used at all IMO.

**Comment by herrmannplatz** [comment]
@rbieb yes, had a small chat with our designers if we can get rid of it, since its causing also a quite huge load on the cpu when you open a collection.

**Comment by herrmannplatz** [comment]
Ok #1115 just removes the animation and keeps the dots.

**Comment by ffflorian** [comment]
@maximbaz Thank you for reporting!
Closing this since the issue was fixed in https://github.com/wireapp/wire-webapp/pull/1115 and will be included in the next release. :slightly_smiling_face: Feel free to reopen if the issue persists.
