### ISSUE TITLE
A Beta distribution channel

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-webapp#1113]
Subj. I believe we could have a beta channel (a beta PPA for example) where beta versions would be available before they go to the release channel. This way critical errors don't slip through to the mainstream users.

And for the release channel, IMO low-frequency high-quality releases would be much better.

**Comment by helenakos** [comment]
Thanks for the request! We don't have plans to support a beta channel for the Linux client at the moment as this is quite a resourceful task, however you can always build the client for yourself.

**Comment by max-baz** [comment]
I published an AUR package for ArchLinux community: [wire-desktop-beta](https://aur.archlinux.org/packages/wire-desktop-beta)

/cc @ConorIA

**Comment by helenakos** [comment]
@anatoli26 Hey, we have a smaller group of Linux users discussing the client. If you would like to join you can contact me @helena on Wire and I will add you.
