### ISSUE TITLE
Non-standard use of spaces in key fingerprints

### ISSUE THREAD

**Issue by sts10** [wireapp/wire-webapp#1147]
I've noticed that when you copy (and paste) device key fingerprints from the web (and desktop) app, the resulting paste does **not** have spaces between every second character. 

```
aa80a4d2f38b63ffeaff1686bf6d2906ad39bb3e117d0a56e64477085a80b6bb
```

While if you copy a key fingerprint from the iOS app, the resulting paste _does_ maintain displayed the space after every second character. 

```
aa 80 a4 d2 f3 8b 63 ff ea ff 16 86 bf 6d 29 06 ad 39 bb 3e 11 7d 0a 56 e6 44 77 08 5a 80 b6 bb
```

I'd argue that this might be confusing to users. It also may hamper any programmatic fingerprint comparisons. Unless there's some use-case where this functionality makes things easier? 

I'd suggest changing the web (and desktop) application to copy and paste with spaces-- I think it's easier to compare fingerprints by eye (for example if a fingerprint is displayed on a personal website or email signature) that way. I was poking around [the devices.less](https://github.com/wireapp/wire-webapp/blob/dev/app/style/content/preferences/devices.less) file but couldn't find where to make this change.

**Comment by helenakos** [comment]
@sts10 Thanks for your request! I am opening a ticket for this internally.

**Comment by bennycode** [comment]
Can be easily fixed with a `placeholder` attribute.

**Comment by bennycode** [comment]
Because of time constraints we unfortunately cannot work on this ticket for now. But we will keep it in our backlog. Thanks @sts10 for reporting!
