### ISSUE TITLE
Requesting a just slightly more Fluid UI for narrow windows

### ISSUE THREAD

**Issue by notNSANE** [wireapp/wire-webapp#119]
Hi, I started using Wire just an hour ago and I love it. I'm having some minor issues in general, but this one it's the most annoying one right now...

My current desktop setup involves reserving approx. 1/3 of the screen space (1920/3) to messengers (this includes some tabs with Whatsapp, Wire, Discord, etc.). While Wire is funcional, I'm missing some UI elements like Ping and Call (with this width), and probably some other options.
I'll attach a screenshot to show you what I mean.

![image](https://cloud.githubusercontent.com/assets/7162375/17991184/bf12f92e-6b12-11e6-8aab-124a8aeaa35b.png)

As you can see, the browser window is a bit narrow (it's actually 700px wide according to a pixel ruler). My suggestion would be reducing the contact list width to make space for the actual chat, so we can have more screen space and chat space.

Thanks!

**Comment by helenakos** [comment]
Hey @notnsane, thanks for the feedback! We are aware of the layout issue and will fix them at some point. Opening a ticket internally :)
