### ISSUE TITLE
Old-style ASCII smileys not recognized (unlike native clients)

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-webapp#12]
If a message contains `;-)` it shows up as `😉` on iOS,
while on OS X or the web it remains the plain `;-)`.

Same is the case for other old-style smileys.
I would expect my conversations to look the same on every platform.

**Comment by lipis** [comment]
Being secure comes with the cost.. since the messages are not readable to our backend we can't do much to render everything in the same way, so every client has to implement these things.. That's being said we'll have to fix it.. Thank you very much @regexident for finding it :)

**Comment by bennycode** [comment]
Current state is the following:
- **Android:** `;-)` → `;-)`
- **OS X:** `;-)` → `;-)`
- **Webapp:** `;-)` → `;-)`
- **Windows:** `;-)` → `;-)`
- **iOS:**  `;-)` → `😉`

So it's our iOS client who is misbehaving. We forwarded it to them.

Thank you. :smiley:

**Comment by regexident** [comment]
Damnit, should have kept my mouth shut then, I guess. 🤐
