### ISSUE TITLE
Replace $.ajax, $.get, etc with fetch()

### ISSUE THREAD

**Issue by lipis** [wireapp/wire-webapp#1265]

**Comment by ghost** [comment]
👍  for opening this issue!

Note: Polyfill is here: https://github.com/github/fetch and it would be a good idea to upgrade to jQuery 3 when we'll get rid of $.ajax

**Comment by lipis** [comment]
Let's do this without the Polyfill

**Comment by bennycode** [comment]
@lipis, fetch doesn't support upload progress (i.e. to show a file upload progress) and it doesn't support to cancel requests. So we will stay with XMLHttpRequest for now. In the long run we might even make use of `@wireapp/api-client`. But that's not up for discussion at this stage.

**Comment by lipis** [comment]
and here is the answer @pwnsdx  :)
