### ISSUE TITLE
Some of the "complex" emojis are not properly rendered

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#1267]
https://github.com/wireapp/wire-webapp/pull/1250 solved text rendering issue, but on the other hand it prevents rendering some of the "complex" emojis, which consist of several unicode characters.

For example, `:woman golfing` 🏌️‍♀️ is an emoji that consists of two unicode characters, `:golfer` and 🏌 and `:female sign` ♀. Unfortunately while `:golfer` is rendered with `emoji` font, the `:female sign` is a symbol that also exists in the text fonts, so it is rendered with `sans-serif`. That's why the `:woman golfing` is rendered as two glyphs instead of one:

![image](https://cloud.githubusercontent.com/assets/1177900/26321942/318c3598-3f29-11e7-8cfb-5cccab60d29d.png)

While it should be like this:

![image](https://cloud.githubusercontent.com/assets/1177900/26321952/3f2c8c20-3f29-11e7-8924-6ae23ac50048.png)

-----

I don't think it is solvable with a single `font-face` definition, we either hit this bug or #1250. I think the best way to fully solve this would be to detect emojis in the conversation (perhaps with logic similar to `Emoji.includes_only_emojies`) and wrap them in a `<span class="emoji">`, and defining a css class `.emoji { font-face: emoji }` which would forcefully use `emoji` font for emojis.

I don't know if this is reproducible on Mac and Windows, and how many people actually will find this bug.  Keep it in a backlog for now and refer to it when someone else reports this.

**Comment by max-baz** [comment]
@gregor this is a different bug than #1268 and should remain open, sorry I should have made that more clear 🙂

> P.S. This **does not** fix #1267, that one is still a valid bug.

**Comment by gregor** [comment]
@maximbaz Didn't manually close this. Github did on merging the PR.

**Comment by gregor** [comment]
With @maximbaz latest changes being part of the public releases, this issue is addressed.
