### ISSUE TITLE
Web Panels support for Vivaldi

### ISSUE THREAD

**Issue by notNSANE** [wireapp/wire-webapp#127]
Just requesting Web Panel support for the Vivaldi browser:
1. Download Vivaldi https://vivaldi.com
2. Use a Web Panel and add http://app.wire.com

I hope you can add support for this great browser. It uses Blink (Chrome engine) so there shouldn't be any problems. Vivaldi even has the same or even better HTML5 support.

Wire works just fine in a normal tab.

**Comment by herrmannplatz** [comment]
Problem in this case seems to be that Vivaldi is using a mobile user agent when loading a site inside a Web Panel. This makes sense since the Web Panel should work as a small sidebar (i guess). We could change our user agent detection to cover that case, but our web app doesn't support such small dimensions (see #119). Which means you have to make you Web Panel quite big. Not sure if this is the way to go. Will discuss with the team.

**Comment by notNSANE** [comment]
Thanks for replying!

Yes, it's exactly as you say, but what's weird is that Vivaldi has an option to enable Desktop view (to avoid this "not supported" issue) and Wire still doesn't work. That's why I raised an issue, I'm not sure if this issue is from Wire or from Vivaldi, if you guys can't fix it, maybe it's Vivaldi's problem. Width isn't a problem either due to the new Width controls (available on Snapshot version only, for now): https://vivaldi.net/en-US/teamblog/148-snapshot-1-3-582-3-web-panel-improvements-and-a-new-snapshot-logo

Here's a screenshot on how to enable Desktop view:
![image](https://cloud.githubusercontent.com/assets/7162375/18073288/2b1cc8d6-6e3b-11e6-8e3b-4cf0e5a72c38.png)

Thanks again for the help!

**Comment by bennycode** [comment]
@lipis Can you have a look at the user agent detection?
@notnsane Can you send us your user agent? You can get it from: http://www.whoishostingthis.com/tools/user-agent/

**Comment by notNSANE** [comment]
Sure! Here it is:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.80 Safari/537.36 Vivaldi/1.3.582.3`

**Comment by thenktor** [comment]
Hi,

Vivaldi user agent in browser window: 

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.122 Safari/537.36 Vivaldi/1.4.589.29

Vivaldi user agent in web panel: 

> Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.122 Mobile Safari/537.36 Vivaldi/1.4.589.29

Vivaldi user agent in web panel using desktop version: 

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.122 Safari/537.36 Vivaldi/1.4.589.29

**Comment by gregor** [comment]
@notnsane While we like your request, we have not been able to allocate enough resources within the past year to make the necessary changes. It will not be on our immediate roadmap for the forseeable future. We continue to track this requests internally but close the issue down for housekeeping reasons.
