### ISSUE TITLE
Unable to type "@" in the email field

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-webapp#1275]
I've reported this bug through other channels many other times, so I'm sorry if I'm repeating myself, but I've got to.
I cannot reproduce right now because I'm not on a windows machine, so I can't give a detailed environment -- all I can say is that it happens all the time.
1. Use a windows 10 machine
2. open chrome (I think firefox would work too)
3. go to app.wire.com
4. try to type any email ---> there is no way to type "@". It just doesn't let you. You have to copy-paste the symbol into the email field from somewhere else

I have no idea why it doesn't let you type the "@" character, but this has happened to me and my friends consistently for months, so it's not just me/my computer/my browser/my room. However, it might be related to the fact that we are all using Italian keyboards.

**Comment by balping** [comment]
I could not reproduce this bug in win10 using chrome 58 or firefox 53 (non-italian keyboard)

**Comment by bennycode** [comment]
Here at Wire we are also unable to reproduce this issue. 

As a workaround we recommend to login with username (not email!) and password because this works too. 😃

**Comment by someoneEsle** [comment]
Is there *anything* I can do to help debug this? It just happened again and I won't be able to sleep well until I know that Italians can log in by typing "@"

**Comment by bennycode** [comment]
We are still unable to reproduce this problem. Please use your handle and password to login.
