### ISSUE TITLE
Opening multiple tabs breaks encryption

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1287]
Opening multiple tabs breaks encryption. This is very annoying because for people who are used to opening more than 10 browser tabs, it is easy to miss that you've already opened. Even worse, it will also break messages *that were already successfully received*. The protocol should be altered in a way that multiple browser tabs somehow recognize each other and figure out how to set up the encryption keys to keep things working.

Wire for Web Version: `2017-05-26-08-16-prod`
Browser Version: `Firefox Developer Edition 54.0a2 (2017-04-18) (64-bit)`
Installed Browser Addons: User Agent Switcher, ublock, HTTPS Everywhere
OS: `Ubuntu 17.04`

What steps will reproduce the problem?
1. Open wire web app in a regular non-private tab and write to someone
2. Open wire web app in parallel in a second browser tab (in the same browser instance with the same cookies, so not in private mode or something)

What is the expected result?
The app still works

What happens instead?
Everything breaks, all the latest messages are replaced by `a message from XXX was not received.
(Error: 205 ID: d5be4c1911067446)
Reset session `

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
Known and unfortunate. We have been considering to block users from opening a second tab. So far it has never gotten enough priority to be actually implemented.

**Comment by ghost** [comment]
Well it happens to me every 1-2 days even now that I know about it, and it's the single biggest annoyance I have with wire. But I guess if that's just me... ?

A block would already be super useful. Of course if in the long term you can simply make it work properly, that'd be even better.

**Comment by max-baz** [comment]
Perhaps consider pinning a tab with Wire in browser, or using desktop version, as a workaround for now. Pinning tab has a nice bonus, it makes Wire always the first tab in your browser, and so no matter how many open tabs you have at the moment, you can always quickly navigate to it with a shortcut <kbd>Ctrl+1</kbd> (in Chrome, at least).

**Comment by ghost** [comment]
Yes but the pinning is gone as soon as I restart the browser. (since it is configured not to save the session ever) You might argue the way I configured my browser is silly, but it works for literally everything else and the only thing I ever use which breaks badly over it is Wire..

**Comment by max-baz** [comment]
Nobody will argue that it is silly, if it works for you, that's a good configuration 🙂

As another idea for a workaround for you, maybe instead of starting every session as empty, starting it with one tab (wire) always opening by default will work?

![image](https://cloud.githubusercontent.com/assets/1177900/26523204/c042db38-4312-11e7-8d84-b5131c1fe1d6.png)

**Comment by ghost** [comment]
It appears Firefox has no such setting available. I'm not really much of a Chrome or Chromium user.. (also the setting doesn't look like the site would open back up pinned)

I understand assuming nobody else is bothered by this that you might not be really motivated to fix it. But there isn't really a good way to prevent a user from accidentally opening a tab again when it's already open, so it seems like a bad idea to rely on this assumption in the first place.

**Comment by max-baz** [comment]
No such setting, that's unfortunate. However these were workaround ideas anyway, it is acknowledged that this is a bug and needs to be properly addressed at some point. 

You are not the first one to raise this issue, by the way - see https://github.com/wireapp/wire-webapp/issues/772 for example.

**Comment by gregor** [comment]
Started working on this as a little personal side project over the weekend. #1338 would prevent the app from running in multiple tabs simultaneously. No promise this will make it into the product but I wanted to give it a shot.

**Comment by tjvf** [comment]
@JonasT You can set Firefox to open a tab or set of tabs in about:preferences#general, under Startup at the top. You can set multiple URLs as your home page by separating them with a |. This shouldn't be affected by your privacy settings.
