### ISSUE TITLE
Emojis won't appear properly

### ISSUE THREAD

**Issue by severus-tux** [wireapp/wire-webapp#1291]
Wire for Web Version: 2017-05-26-12-03-prod
Browser Version: Mozilla Firefox 53.0.3
Installed Browser Addons: Duckduckgo plus
OS: Arch Linux, Kernel : 4.11.2-1-ARCH

What steps will reproduce the problem?
1. Open wire on firefox and in any chat box type " hi :) (and a space after :) ) "
2. This will appear as " hi � �"
3. Pressing backspace will correct it sometimes.

What is the expected result?

An emoji should appear instead of :)

What happens instead?

It appears as  :  
![2017-05-30-065745_127x47_scrot](https://cloud.githubusercontent.com/assets/21301040/26565030/2e9eb55e-4505-11e7-93cd-bd204123e8e1.png)

Please provide any additional information below. Attach a screenshot if
possible.

![type](https://cloud.githubusercontent.com/assets/21301040/26565139/25ce3d40-4506-11e7-9e17-9c9e5eafbed0.gif)

**Comment by MrSuttonmann** [comment]
Wire for Web Version: 2017-05-26
Browser Version: Opera 45.0.2552.881
Installed Browser Addons: HTTPS Everywhere, UBlock Origin
OS: Windows 7 Professional 64-bit

Same issue, emojis appear as boxes. 

![image](https://cloud.githubusercontent.com/assets/7480500/26574233/78c2dd82-4518-11e7-9da6-078e97649ce2.png)

**Comment by mythsunwind** [comment]
This is not a bug. The correct display of emojis depends on your local font configuration. Please see https://github.com/wireapp/wire-desktop/wiki/Colorful-emojis-on-Linux for more information.

**Comment by severus-tux** [comment]
Thank you
