### ISSUE TITLE
About panel showing template code instead of actual version

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-webapp#13]
When opening the about panel of the Web client, the version template code is shown, instead of the actual version:

```
© Wire Swiss GmbH • Version {{config.CURRENT_VERSION_DATE}}
```

**Comment by bennycode** [comment]
Hi @regexident, on which platform and host (localhost?) did you test the `CURRENT_VERSION_DATE`?

**Comment by bennycode** [comment]
Ok, I verified the issue and it's expected behaviour by us. Versions are only show on production environments like https://app.wire.com but not on http://localhost:8888/.

**Comment by regexident** [comment]
Hi Ben, the web app was indeed running on localhost.
