### ISSUE TITLE
Revert the New Visual Changes

### ISSUE THREAD

**Issue by Sledge-Hammer** [wireapp/wire-webapp#13278]
Hello,

How can I disable the new visual changes, because they're extremely irritating to me and literally make the app unusable?
I use the desktop version for long periods of time and those highlighted sections (the conversations tab and the currently active contact) are way too distracting. I can't work like that.
Also the white background for the contacts list is also distracting me from the conversation portion of the window which should be the only thing in focus. 

The previous design was much better suited for using the app for more than 3 minutes per day. Please bring back the old design as a separate theme (like the dark theme) or at least let us build custom themes through CSS or something else, that won't be overridden on upgrade.

**Comment by Transisto** [comment]
This is not a theme these are clearly attempt at permanent improvement.
You should try understanding what they've tired to do and suggest small changes from that.

**Comment by Transisto** [comment]
Seems like we traded having a darker contact side with a nice smooth background for having labels under the Contact and Conversation icons which are pretty self explanatory.

IMO Mostly a downgrade.

**Comment by nealmckee** [comment]
Agreed, aesthetics might be subjective but to me it is a massive downgrade on that front, but even in terms of user friendliness, the only improvement seems to be higher contrast. To me that contrast is distractingly high, the new blocks of color for highlighting are too bold, the additional outlines around icons feel unbalanced and like clutter and for dark mode the contrast for text actually decreased — but not by making the text less bright but by making the background too light.
Please at least make this optional (like an accessibility mode if that was your intention) or do another relatively major update to fix some of these issues.

**Comment by mfrydrychowicz** [comment]
bump

I would also add that it would be great if there will be some indication who wrote what. I mean some colored bar when "on hover" on left or right side; or text alignment to selected side. Anything.

**Comment by Sledge-Hammer** [comment]
Really?
How did you managed to make it even worse in version 2022.09.20.08.41?
That new font is even harder to read!
I'm not trying to be a d*ck or anything, but are you trying to make people stop using the app on purpose?
At least give us an option to choose our own font if we can't downgrade to the more usable versions...

The new font in the contact list is a little better but now the chat window is completely unusable.

**Comment by Transisto** [comment]
I don't like it either, I wish there was a way to make the text bigger, It's too thin, it looks like I can see though parts of the letters.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/191398934-956659e9-f262-49d6-9695-0d4a0d3f0579.png)

**Comment by dcorc** [comment]
Please allow the option to revert settings as per previous versions - the new font is less legible 
- but what to me is MORE IMPORTANT is that the graphical redesign has resulted in the webcam window being smaller, with large amounts of "real estate" taken up with a thick border which only serves for the display of large circular icons for "conversation", "microphone", "camera", "share screen" and "hang up". I need some way of getting the webcam window to be FULL screen, without cutting in on the webcam image. 
-

**Comment by dcorc** [comment]
Being ignored is really great.......

**Comment by JCmAxohtwEoK0fdaQip7** [comment]
> Really? How did you managed to make it even worse in version 2022.09.20.08.41? That new font is even harder to read! I'm not trying to be a d*ck or anything, but are you trying to make people stop using the app on purpose? At least give us an option to choose our own font if we can't downgrade to the more usable versions...
> 
> The new font in the contact list is a little better but now the chat window is completely unusable.

I thought exactly the same with the font
Please revert it
https://github.com/wireapp/wire-desktop/issues/6016

**Comment by JCmAxohtwEoK0fdaQip7** [comment]
Looks to be fixed in the [2022-11-02-production.0] release just today
