### ISSUE TITLE
Not delivered message does not have "not delivered"/"resend" indication

### ISSUE THREAD

**Issue by mfrydrychowicz** [wireapp/wire-webapp#13315]
## Your Account Type

- [ x] Wire Personal Account
- [ ] [Wire Pro Account](https://wire.com/products/pro-secure-team-collaboration/)
- [ ] [Wire Enterprise Account](https://wire.com/products/enterprise-collaboration/)
- [ ] [Wire Red Account](https://wire.com/products/red-crisis-communication-software/)

## What steps will reproduce the problem?
send message that will not be delivered.

## What is the expected behaviour?
The message shall show clear indication, that error occurred and shall give used an option to try to resend it.

## Which browser are you using?
Firefox 102.0 (64 bit)

## Installed browser addons
uBlock origin

**Comment by tlebon** [comment]
can you please include more information about this issue? Perhaps a photo or a description of why the message was not delivered? In most cases this **should** show a resend option.

**Comment by mfrydrychowicz** [comment]
The issue no longer occurs. I'm closing
