### ISSUE TITLE
WebApp doesnt work on browsers built for android

### ISSUE THREAD

**Issue by streng12** [wireapp/wire-webapp#13798]
## Your Account Type
[Wire Personal Account] 

## What steps will reproduce the problem?
1. Run WebApp on Google Chrome on Android device
2. Login Through your credentials - after login you are imediately log off - NOK
3. Repeat for Firefox or Edge for Android - same behavior, but Edge start to decrypting messages, and i can see my contactllist for a while until it log off

## What is the expected behaviour?
You can easily login and use webapp with Chrome/Edge/Firefox android web browsers

## Which browser are you using?
Mozilla/5.0 (Linux; Android 12; SM-G970F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36

## Installed browser addons
None of them, just clean installations

**Comment by tlebon** [comment]
Sorry to say that the webapp is not intended to work on **any** mobile device. you will have to use the Android application.

**Comment by streng12** [comment]
There are two reason why I asking for this:
1.	Many phones now allows a desktop like experience (Samsung Dex, Motorola Ready for …). Wire for android doesn’t fit well with that mode. That’s the reason why I want to use it in browser, to be as close as possible for desktop usage.
2.	https://github.com/wireapp/wire-android/issues/3732 - I’m unable to use wire when I’m on online through ethernet cable (connected with docking station). Since internet connection works well on browsers and different messenger I was wanted to bypass it by run it into browser

**Comment by tlebon** [comment]
Sorry, these topics are getting into Wire for android decisions and I am not really qualified to answer them. (Specifically reason 2). 

All I can say is that we have no plans to allow the web wire client to work on mobile devices currently. 
We intend the native apps to be used for those cases. 

Sorry for that! I hope the Android team is able to help you with any specific issues. Maybe @tmspzz can comment on this.
