### ISSUE TITLE
In chat window, URL with "@" sign is not displayed correctly

### ISSUE THREAD

**Issue by ppkt** [wireapp/wire-webapp#139]
For example, when I sent a URL in chat: 
`https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1448956.html`
It was displayed as: 
`debian-bugs-dist@lists.debian.org/msg1448956.html" target="_blank" rel="nofollow">https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1448956.html`
in chat window. I think it's because URL is treated as an e-mail, but I'm not sure ;)

Please check screenshot below
![screenshot from 2016-08-30 14-45-07](https://cloud.githubusercontent.com/assets/477174/18089564/da1ded8a-6ec0-11e6-8a21-7290d2ccfccd.png)

**Comment by bennycode** [comment]
Thanks for the  bug report, @ppkt. We track it now in our test cases: https://github.com/wireapp/wire-webapp/pull/151 :+1:
