### ISSUE TITLE
A few Problems With Version 2022.11.28.08.15

### ISSUE THREAD

**Issue by Sledge-Hammer** [wireapp/wire-webapp#14181]
Hello,

I'm not sure if every problem I have with update 2022.11.28.08.15 is related to the web app but I've decided to post them here since they showed up in this update.

1) ~~Bug: After reading the latest message in the chat window the system tray icon retains the red dot indicating a new message.
There's also a white dot on my avatar on the left (in the accounts list).
I have to go to another conversation in order to make it disappear.~~

2) Feature Request: The new typing indicator functionality is nice but it would be great if we could disable it for our own account (so others don't see while we're typing). This way we can only see that people are typing only if they had enabled it for their account.

3) ~~Feature Request: The new typing indicator is kinda huge... Making the font and the pencil icon a few pixels smaller might be better (this might be somewhat subjective, but at least for me the current implementation is too large).~~

4) ~~Bug: The new typing indicator is not always working right - sometimes it shows that someone is typing while they're doing something completely different on the PC and the client isn't even focused.~~

I'm currently on Windows using the desktop client: 
Version 3.29.4349
Wire for Web Version 2022.11.28.08.15

//EDIT:
It seems that 3 of the issues have been fixed in Wire for Web Version 2022.11.30.09.39

**Comment by aweiss-dev** [comment]
Hi @Sledge-Hammer.

The typing indicator is still evolving and is an actively worked-on feature. 
Your Feature Request (2) is already part of the product roadmap and will be implemented in the future.

Thank you for giving us valuable feedback. It is highly appreciated.
