### ISSUE TITLE
SSL in Node.JS - not in Nginx

### ISSUE THREAD

**Issue by segahm** [wireapp/wire-webapp#1423]
The issue with this setup is that it assumes all SSL is handled by the Node. But that's not an industry common practice. The usual setup is to proxy SSL via nginx, and then issue direct requests with a Node.Js service. Instructions on the later would help.

**Comment by bennycode** [comment]
Hi @segahm, can you please give more context to this issue? wire-webapp is about Wire's frontend code (no Node.js involved).

**Comment by gregor** [comment]
I will go ahead and close this as no info was added to the ticket.
