### ISSUE TITLE
Feature request:  Option to change name format / Rename user

### ISSUE THREAD

**Issue by rehoehle** [wireapp/wire-webapp#1436]
I use Wire now and i find that it's working well and and try to change with all of my contacts. 

But one thing what i've seen is that my contact list have only the firstname of the user. That is a problem if some users have the same name and i can't change them. Some user Don't use their complete name or use a pseudonyms what makes it hard to see which user is the right one. 

It would be very helpful if i could rename a user or set as option that i can see the username instead of the firstname.

**Comment by bennycode** [comment]
Hi @rehoehle, thanks for sharing your thoughts with us! 

Unfortunately we cannot accept feature requests as part of this repository. 
But you can draw attention to your feature request here: https://github.com/wireapp/wire/issues 😃 

Best from Berlin,

Benny

**Comment by rehoehle** [comment]
@bennyn thx :) there are so much repos for the same :D that it's a bit difficult to find the correct one :D
