### ISSUE TITLE
Page shows: "Wire is already open in another tab." Even though it isn't

### ISSUE THREAD

**Issue by Don42** [wireapp/wire-webapp#1440]
Wire for Web Version: 2017-06-22-12-18-prod Doesn't seem to show on the error screen
Browser Version: 54.0 (32-bit)
Installed Browser Addons: Ghostery, µblock origin (Tested with both 'paused') Firefox Sync is set up
OS: Windows 7 (Not sure were to find a specific version)

What steps will reproduce the problem?
1. Have *app.wire.com* open and be logged in; Firefox set up to restore session; (Tab is pinned)
2. Close Firefox and reboot the computer (I did a full reboot)
3. Start Firefox

What is the expected result?
Open Firefox should contain a *app.wire.com* tab ready to login.

What happens instead?
Firefox contains a *app.wire.com* tab with only the message "Wire is already open in another tab"
And the URL shows *https://app.wire.com/auth/#tabs*

Please provide any additional information below. Attach a screenshot if
possible.
Reloading the page, even with with **Shift+F5** does not solve this problem.
Closing the tab and reopening also doesn't help. Restarting Firefox was also tested.
Opening *https://app.wire.com/auth/#login* in the same tab only works for less
than a second.
The only way to "fix" this issue was to make Firefox forget the site and then login.
This unfortunately deletes keys and history, which creates a new client.

![capture_wire_error](https://user-images.githubusercontent.com/141622/27506356-35674800-58b6-11e7-8986-740d23163f98.PNG)

**Comment by max-baz** [comment]
Workaround: 

* Go to https://app.wire.com
* Hit <kbd>Ctrl+Shift+J</kbd> (<kbd>Cmd+Opt+J</kbd>) to open Dev tools in console
* Paste `document.cookie = 'app_opened=;expires=Thu, 01 Jan 1970 00:00:01 GMT;Path=/;'`
* Hit <kbd>Enter</kbd>
* Go again to https://app.wire.com and it will let you in.

**Comment by jarvis-owl** [comment]
Hej,

same issue here:
OS: Linux Mint 18.1 Serena - Cinnamon | and also with Windows 10
Firefox 54.0(64-bit) with disabled µBlock

@maximbaz Workaround seems to work :+1:

**Comment by Don42** [comment]
@makingthematrix Confirmed, Workaround works for now. Thanks. 
I expect the issue will pop up after the next restart.

**Comment by gregor** [comment]
Thank you for your reports. We introduced the multiple tabs detection in the last release to prevent decryption errors like #1287. Obivously this has some undesired side effects if the cooke enabling this behavior is not properly cleared. I will look into fixing the behavior for the next release or disable the feature temporarily until we have a permanent fix in place. Please excuse the inconvenience.

**Comment by deadalnix** [comment]
Workaround works.

**Comment by Don42** [comment]
Any timeline of when this is going to land in production?

**Comment by gregor** [comment]
@Don42 No promises, but this is planed for this week. Maybe we manage to get it out as early as tomorrow.

**Comment by deadalnix** [comment]
It's the second time this is breaking for me :/

**Comment by piegamesde** [comment]
![image](https://user-images.githubusercontent.com/14054505/49826011-256ac780-fd86-11e8-973d-c7d8553a4ce5.png)
If have this issue too, the workaround didn't work for me. Deleted the cookie and after every crash of Chromium I get this screen again.
