### ISSUE TITLE
Hardware acceleration for video decoding

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#1442]
@bennyn, @gregor I'd like to discuss the possibility of achieving hardware acceleration for video calls. As far as I can tell, hardware acceleration is not being utilized today. If we could get it working, not only the CPU usage will go down, but the battery would live longer, laptop would not heat all the time and possibly even the video quality would increase.

This is primarily targeted Windows and macOS where it is supported natively, although it is [potentially possible](https://github.com/electron/libchromiumcontent/issues/92#issuecomment-310837069) in Desktop app for Linux and achievable with other magic in Chromium on Linux (no Google Chrome, not sure about FF).

What kind of video format is being used today for video calls? Most video adapters can decode h264 standard, if it is possible to get video stream in this format that would cover wide range of users.

**Comment by bennycode** [comment]
Hey @maximbaz, please let me get @jspittka in the loop. He is working at the Audio/Video-Team here at Wire and knows best about the possible options and codecs. 🙂

**Comment by bennycode** [comment]
Because of different priorities we will put this in our backlog.

**Comment by max-baz** [comment]
Roger that, although I'd appreciate some pointers on where in the code the video recording/transmission/decoding is happening, and I'll play with this on my own 🙂 Then, you know, if I manage to hack something working, I'll show it to you 😉

**Comment by oliverdunk** [comment]
How is this in the backlog? On my MacBook, it slows things down to a crawl and I have to close Wire after each screenshare to be able to continue with my work.

**Comment by gregor** [comment]
@maximbaz We touch non of this ourselves. This is handled by the underlying Chromium implemation and it's desktop capturer provided by Electron (https://electron.atom.io/docs/api/desktop-capturer/).

@oliverdunk Our desktop app implementation relies on it's Electron core. The issues at stake here are rooted in that implementation - not something we can fix in our code. We try to pass on any improvements made in the Electron platform as quickly as possible to our production releases.

**Comment by max-baz** [comment]
I think there is some confusion here, what I was asking is about video calls, video stream from webcam. If we can transmit video in h264 format, most devices on the receiving side would be able to use GPU instead of CPU to decode and draw this video.

**Comment by gregor** [comment]
@maximbaz The codec is selected as part of the webRTC PeerConnection negotiation by the means of SDP exchange. The SDP offers and answeres are generated by the the browsers themselves. We try to keep the manual interference with it as low as possible. You can find the related code at https://github.com/wireapp/wire-webapp/blob/dev/app/script/calling/SDPMapper.js though.

You can force a call to use certain codecs by removing all other lines of code. BUT it is very tricky as you can easily break compatibility not only between different browsers and their versions but also with our mobilie clients based on our branched code (https://github.com/wireapp/wire-audio-video-signaling) of which I do not know the currently supported codecs. Firefox will already choke on an SDP with one whitespace in an unexpected place.
