### ISSUE TITLE
Screen Sharing Resolution has unreadable text due to hardcoded resolution

### ISSUE THREAD

**Issue by matthiasg** [wireapp/wire-webapp#1443]
Wire for Web Version: https://github.com/wireapp/wire-webapp/blob/6089d0f383499875a0787ba1c56cd6470b2c58ca/app/script/media/MediaStreamHandler.js#L146
Browser Version: Desktop Client and WebApp
Installed Browser Addons: None
OS: Win10 up-to-date, MacOS

What steps will reproduce the problem?
1. Share screen from typical modern laptop or higher end desktop monitor (e.g iMac,Surface Book, MacBook Pro)
2. Try to read text on recipient side

What is the expected result?

- Readable Text :)

What happens instead?

![dc_cb_5wsaalarg](https://user-images.githubusercontent.com/231889/27513931-d4fa5fba-5979-11e7-9584-c1cfb3bee020.jpg)

**Comment by gregor** [comment]
The screensharing expereicne has been drastically improved. We took another look at the resolution we transmit. Text should be readable now when sending from the latest desktop apps.

**Comment by matthiasg** [comment]
We tried this with 3.3 (windows -> mac and vice versa). Screen resolution is much improved but the darkening overlay every time the mouse moves is quite annoying.

Sadly electron crashes a lot when people switch screen sharing back and forth. 

Also we are a little confused on how/whether double screen sharing is possible or not.
