### ISSUE TITLE
Cannot login on mobile app with web created account, and vice-versa

### ISSUE THREAD

**Issue by SkyzohKey** [wireapp/wire-webapp#1467]
Hey guys.

I created an account from my computer _(Linux - Solus OS, Wire AppImage 64 bits)_ and then tried to login on the Android app _(Android 7.1.1 - Honor 8)_ using that same account. But it fails.

The mobile app tells me that error message:

> **Invalid information**
> Please verify your credentials and try again.

I verified my credentials and they ARE valid, but the app think they are not. The same issue works for mobile created account when i try to connect on my desktop app.

That's a really weird issue and it undermine my Wire usage... Please investigate. Anyway, thanks for the **great** solution you provide!

**Comment by max-baz** [comment]
Looks like Wire AppImage 64 bits is compiled against non-production environment 🙊 

/cc @gregor

**Comment by mythsunwind** [comment]
@SkyzohKey Have you compiled the AppImage yourself? When you download the new version from https://wire.com/download/ does it still happen?

**Comment by max-baz** [comment]
I reproduced this issue myself 5 days ago by downloading Wire AppImage 64 bits from https://wire.com/download/

**Comment by max-baz** [comment]
Doesn't happen anymore with the latest version :+1:

**Comment by mythsunwind** [comment]
Sorry for the inconvenience!

**Comment by SkyzohKey** [comment]
Thanks for the quick fix ! =)
