### ISSUE TITLE
Wire web app doesn't load properly on slow connection, but doesn't display an error either

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1470]
Wire web app doesn't load properly for me on a slow connection, but it doesn't display an error either.
I have watched it try to load itself with Firefox' "Inspect" > "Network" tab open and it says 4,10MB transferred in 1,12mins and now it is just stuck there:

![broken_webapp_loading](https://user-images.githubusercontent.com/1573352/27763564-fddefd9e-5e85-11e7-95b9-2cad89ab4821.jpg)

It would be highly preferable if it did something smart with retrying downloads to actually manage to run, also if it doesn't it really should display a proper error.

## Wire for Web Version
2017-06-28-15-13-prod

## Browser Version
Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

## Installed Browser Addons
ADB Helper
HTTPS Everywhere
uBlock Origin
User Agent Switcher (addon enabled but not using any user agent switching during the test)
Valence

## Operating System
Ubuntu 17.04

## What steps will reproduce the problem?
1. Use a slow web connection with occasional dropouts (e.g. tethered)
2. Try to open the web app

## What is the expected result?
It either works, or a proper error is displayed. Preferably it should also work with a higher consistency than it does now, since it seems pretty easy to throw the loading process off even though 4MB transferred in 1-2 minutes successfully.

## What happens instead?
It just gets stuck with zero useful feedback:

![broken_webapp_loading](https://user-images.githubusercontent.com/1573352/27763564-fddefd9e-5e85-11e7-95b9-2cad89ab4821.jpg)

**Comment by mo3rfan** [comment]
I think this happens when you haven't used the web version of wire for a long time and it kind of tries to pull in everything from the point you left it.

**Comment by ghost** [comment]
@PowerInside that's not much of an excuse for lack of proper error handling though.. also it seems to lack even a most basic retry mechanism, or if it has one it probably should be tweaked to retry more aggressively

**Comment by gregor** [comment]
@JonasT Thanks for your report. We will see how we can improve the situation in the future but have no immediate plans to change the current implemenation regarding our page setup. Thereby I am going ahead and closing this issue.
