### ISSUE TITLE
Conversation UI should not restrict messages to 800px width

### ISSUE THREAD

**Issue by rgmz** [wireapp/wire-webapp#14999]
## What steps will reproduce the problem?

When using the Wire web and desktop apps, the message list and conversation elements are 'artificially' restricted to 800px. This leaves a lot of empty space and makes it harder to read and write messages.

It is especially peculiar for the conversation input as the element seemingly uses the entire width (Ping, Attach picture, Add File, Self-deleting message, and Send message are on the right-most side), however, the textarea only uses a small portion of the screen's width.

**Example:**

![image](https://user-images.githubusercontent.com/32133502/230905780-d5cc9d21-0eed-41be-9e95-a39a9a8b2a8f.png)

![image](https://user-images.githubusercontent.com/32133502/230905816-298c4aa1-0294-4ce2-8df2-fdc147004dda.png)

## What is the expected behaviour?

The message list and conversation input should be responsive and use the full width of the screen. 

As far as I can tell, this should be simple to achieve by tweaking the ` @conversation-max-width` value:

https://github.com/wireapp/wire-webapp/blob/0fb331bc07a8aaa610f5234f95a12db000c35902/src/style/content/conversation/message-list.less#L26-L27

https://github.com/wireapp/wire-webapp/blob/0fb331bc07a8aaa610f5234f95a12db000c35902/src/style/common/variables.less#L230

**Example:**

![image](https://user-images.githubusercontent.com/32133502/230907639-2214913e-a61b-44d5-8f1f-f23b81018e1e.png)

**Comment by Yubraj977** [comment]
![Screenshot (2)](https://github.com/wireapp/wire-webapp/assets/112848654/be9812b4-f3ea-4df0-93a9-52d20b8d9163)
But this is taking entrie width

**Comment by tlebon** [comment]
i believe this is fixed now? please reopen if it still appears to be an issue.
