### ISSUE TITLE
Markdown processing inside a url

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire-webapp#1538]
## Wire for Web Version
2017-07-18-12-50-prod

## Browser Version
Chrome/59.0.3071.115

## Installed Browser Addons
A lot, but almost certainly irrelevant

## Operating System
Windows 10

## What steps will reproduce the problem?
1. Paste a link that contains two underscores in it
2. Watch the italics break your link
3. Go to mobile to actually click on link

## What is the expected result?
Markdown should not be processed when it is part of a hyperlink

## What happens instead?
The contents between two underscores becomes italicized and the link breaks.

This link `https://twitter.com/One_T_/status/884853224003555328` turns into:

![https://i.gyazo.com/f8ca1114bfccfaea99ab709bebda3a49.png](https://i.gyazo.com/f8ca1114bfccfaea99ab709bebda3a49.png)

**Comment by gregor** [comment]
Fixed by #1875. Will be part of the next release to production.
