### ISSUE TITLE
Can not register staging account

### ISSUE THREAD

**Issue by tester000007** [wireapp/wire-webapp#15812]
When I run webapp code, and want to create account
the link in browswer is: 
https://local.zinfra.io:8899/auth/#/createaccount 

but , I receive error meesage. 
{code: 403, label: "unauthorized", message: "Unauthorized e-mail address or phone number."}
the back api is :  https://staging-nginz-https.zinfra.io/v5/activate/send

how I register  a staging account? to use it login dev env.

**Comment by tester000007** [comment]
![image](https://github.com/wireapp/wire-webapp/assets/144110541/585066ef-67f0-46ec-aec6-f1a362d395d9)

**Comment by tester000007** [comment]
this link also can not use:  https://wire-webapp-master.zinfra.io/auth/#/createaccount

**Comment by tlebon** [comment]
unfortunately staging accounts are only for internal testing at this point.
