### ISSUE TITLE
Can't use the web interface as of Monday, August, 14th, 2017

### ISSUE THREAD

**Issue by dysinger** [wireapp/wire-webapp#1600]
## Wire for Web Version
2017-08-08-15-09-prod

## Browser Version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.78 Chrome/60.0.3112.78 Safari/537.36

## Installed Browser Addons
HTTPS Everywhere (because we like TLS .... especially on our e2e encrypted communications)

## Operating System
Linux (Ubuntu 17.04)

## What steps will reproduce the problem?
1. Visit the site
2. Login
3. See the login prompt again

## What is the expected result?
That I would successfully login & see my chat page

## What happens instead?
I see the login page in a loop

**Comment by dysinger** [comment]
This worked fine before so I imagine you've recently released the web app (August 8th). I was offline since 11th.

**Comment by dysinger** [comment]
Incognito mode works in Chromium (no previous cookies and no extensions active)

**Comment by dysinger** [comment]
I disabled all of my Chrome extensions. Still getting bounced to the login screen repeatedly (every time I login, I get redirected back to the login form)

**Comment by dysinger** [comment]
I am going to attempt to clear my wire.com cookies as this has helped in the past with bugs.

**Comment by gregor** [comment]
Hi @dysinger, thank you for your report. Can you please tell me from which state in the login process you get bounced back to the login form? What's the last thing you see before it switches back to the form?

**Comment by fuine** [comment]
I have also stumbled upon this bug while using `Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0` on `Arch Linux`. There are two different behaviours that I can notice - either a loading bar is briefly shown on the screen and i get bounced or I get to see a blue canvas with just the logo for a short period of time (think second or less) after which I'm back at the login screen. I also use `HTTPS Everywhere` addon. Notably it seems that cookies don't matter here, as I tried clearing them before getting bounced.

**Comment by dysinger** [comment]
I am not sure of the state. It takes my (valid) login credentials, it looks like we are going somewhere & then back to the login prompt.

On a virgin incognito tab, my login works & acts like a new device/browser.

**Comment by fuine** [comment]
So I played around a bit and after I press a `log in` button I can see a `uncaught exception: out of memory` message in the browser's console. This issue does not exist in `chromium` on the same machine. I'm not sure whats to blame - `firefox`, `wire`, my OS setup, or combination of all these things. @gregor any way I could help you narrow down the problem?

Edit: I can reproduce this bug on a fresh profile using the latest (`57.0a1 (2017-08-29)`) `firefox nightly` browser
