### ISSUE TITLE
Control-backspace disables use of 'K' key

### ISSUE THREAD

**Issue by alekratz** [wireapp/wire-webapp#1602]
## Wire for Web Version
2017-08-08-15-09-prod

## Browser Version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

## Installed Browser Addons
Vimium and ublock origin, but both have been disabled.

## Operating System
Arch Linux 64 bit

## What steps will reproduce the problem?
1. Type something
2. Press ctrl-backspace, to delete the previous word
3. Press the "K" key. The group chat window is brought up instead of "K" being inserted.

## What is the expected result?
The letter "K".

## What happens instead?
The group chat window pops up, stealing the focus of the chat textbox.

## Additional info
* Chrome version is 60.0.3112.90 (Developer Build) (64-bit)
* I *was* able to reproduce this in Firefox 55.0.1 on the same OS.
* I can work around this by either refreshing the page, or switching tabs.

**Comment by ThomasLeister** [comment]
I'm facing the exact same issue :(

**Comment by ThomasLeister** [comment]
This issue seems to be resolved with the current version on https://app.wire.com/ :-)

**Comment by ppkt** [comment]
@ThomasLeister I'm not sure - I still have this bug in 2017-08-31-14-21-prod

**Comment by bennycode** [comment]
I have been unable to reproduce this issue so it seems to got fixed over the years. :)
