### ISSUE TITLE
When cookies blocked, error message should say login fails because of it

### ISSUE THREAD

**Issue by thomas-kuntz** [wireapp/wire-webapp#1609]
## Wire for Web Version
 2017-08-08-15-09-prod

## Browser Version
Chrome 60.0.3112.90

## Installed Browser Addons
uBlock Origin, Privacy Badger, Wayback Machine, HTTPS Everywhere, Data Selfie, Mesure, React Developer Tools, IBA opt-out (by Google)

## Operating System
macOS Sierra

## What steps will reproduce the problem?
1. Go to app.wire.com with Google Chrome
2. Enter login credentials and click "log in"
3. Get the vague error message

## What is the expected result?
When cookies are disabled on the browser, I should know that the login fails because of that.

## What happens instead?
"Problems with the connection. Please try again." is displayed between the password field. The error message is vague and could be much more helpful in helping people not waste their time trying to figure out why it's not working 😉

<img width="1280" alt="screen shot 2017-08-19 at 5 26 02 pm" src="https://user-images.githubusercontent.com/16361470/29491012-81b15fe2-8503-11e7-921c-0942541edb42.png">

Consequence of #1608

**Comment by gregor** [comment]
@thomaskuntzz Thank you for your feature request. We will continue to improve our error case handling and will keep this in mind when we do. We have no immediate plans on adding a detection that login fails due to missing cookies at this time though. Due to the nature of this being a feature reques, we will continue to track this internally only. I will thus go ahead and close this issue.

**Comment by gregor** [comment]
No promise that it will make it in to the product but I quickly add support for it in a side project: https://github.com/wireapp/wire-webapp/tree/feat/cookies

**Comment by thomas-kuntz** [comment]
@gregor Cool! Did you PR?

**Comment by gregor** [comment]
Not yet. Needs some copy first. Will work with our design guys and see if we get it in.

**Comment by gregor** [comment]
https://github.com/wireapp/wire-webapp/pull/1660 has now been merged to address this and will be part of the next public release.

@thomaskuntzz Thanks again for pointing this out.

**Comment by thomas-kuntz** [comment]
Perfect, thanks for taking care of this!

**Comment by gregor** [comment]
@thomaskuntzz You can also always open PRs to handle omissions like that. We are more than happy to take contributions.
