### ISSUE TITLE
Canvas shifted up (Rambox)

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-webapp#1616]
## Wire for Web Version
Version 2017-08-08

## Browser Version
Rambox 0.5.10
(Electron 1.7.4, Chromium 58.0.3029.110, Node 7.9.0)

User agent:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.10 Chrome/58.0.3029.110 Electron/1.7.4 Safari/537.36`

## Installed Browser Addons
None

## Operating System
Ubuntu 16.04 

## What steps will reproduce the problem?
1. Add Wire on Rambox
2. Quit Rambox and run it again
3. Don't focus the Wire tab, wait until you expect it to have loaded
4. Focus the Wire tab: everything is slighly shifted up.

Workaround:
Refresh the tab while having it focused and everything comes back into place.

## What is the expected result?

All the page elements should shown, no blank gaps should appear.

## What happens instead?

The upper elements are cropped and there is a white gap at the end.

![27858754-b6b53746-6176-11e7-9f39-0cbe2a95bbac](https://user-images.githubusercontent.com/4943683/29616663-e8589b92-881a-11e7-8d25-70593c7fd638.png)

I opened the same issue in Rambox, but the developer thinks it is related to Wire itself: https://github.com/saenzramiro/rambox/issues/976

Update: just to confirm, this still holds in November 27, 2017 (Rambox 0.5.13, Wire 2017-11-10).

**Comment by gregor** [comment]
While it's nice to see that Wire mostly works in Rambox, we do not officially support it. We don't do anything special in the case the browser is not focused when loading the app - meaning the described scenario works smootly in a plain browser environment. Thus I do not believe it is related to our implemetation. If it turns out to be the case, we are more than happy to fix it but we unfortunately do not have the resources to track this down. :(

**Comment by MakisH** [comment]
Dear stale (bot),

I would like to prevent you from closing this issue, as it is still occuring to me with the latest Wire and Rambox versions in Ubuntu 16.04. Make sure that I will take care to close it when it stops occuring.

Please note that Wire is the only service I have tried that suffers from this, among Messenger, Wire, Whatsapp, Gitter, Gmail, Google Calendar, Google Keep, and Toggl. However, I have no idea if it originates from Wire or from Rambox (or for the cause), therefore I opened issues on both projects.

Best regards,
Makis (human, I think)

Edit: Since I opened this issue, I have gotten a new computer and installed everything again. It still occurs.

**Comment by MakisH** [comment]
In the latest versions of Wire and Rambox, this looks fixed! :-D

**Comment by gregor** [comment]
Glad to hear this.
