### ISSUE TITLE
No way to have Wire working on Linux

### ISSUE THREAD

**Issue by riksoft** [wireapp/wire-webapp#1618]
## Wire for Web Version
2017-08-08-15-09-prod

## Browser Version
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
55.0 on the 3 PC involved.

## Installed Browser Addons
No addons.

## Operating System
Mint 18, Mint 17, Ubuntu 16

## What steps will reproduce the problem?
Call from one device to the other:
pc1->pc2
pc1->pc3
pc2->pc1
pc2->pc3
pc3->pc1
pc3->pc2

## What is the expected result?
It should ring, then accepting the call should connect.

## What happens instead?
Accepting the call shows "Connecting" but after 10s it hangs up. All the above combination have the same behaviour and its impossibile to start a conversation.

I've repeated the test with a tablet Samsung S2 with your app.
pc1->tablet OK
tablet->pc1 OK
pc2->tablet OK
tablet->pc2 OK
pc3->tablet NO 
tablet->pc3 NO
Note: pc3 is on ADSL 20/1 (real speed 18/0.9 mbps) while pc1 and pc2 are on fibre (real speed 50/15 mbps)

We have also tested the desktop software for Linux against the web app: same thing.
Sometime it doesn't even ring, but most of the time it rings and doesn't connect just like the browser app..

Tried Jitsi to be sure it's not a problem of RTC and all the above combinations work OK.
Any chance to have it working on Linux?

**Comment by riksoft** [comment]
**Other tests.**
Firefox on Linux --> Firefox on Win7
The connection is made but hangs after few seconds. Tested more times.

Firefox on Win7 --> Firefox on Linux
It works!

Firefox on Linux --> Wire desktop on Win7
It works!

Wire desktop on Win7 --> Firefox on Linux
It works!

There are clearly a lot of problems when both sides uses Linux + Firefox and some problems when only one side uses Linux+Firefox.

**Comment by gregor** [comment]
Thank you for your report. We are continuously looking at improving the calling experience. Firefox scenerios will get more attention again. We have already fixed some cases (and might have broken others a long the way). Without any specific details on why calls fail in your case, I am going ahead and closing this ticket.
