### ISSUE TITLE
Crash with Opera

### ISSUE THREAD

**Issue by Malaquita** [wireapp/wire-webapp#1630]
Today I got a message that the issue with Wire and Opera is closed and solved.
Well, let me tell that it is not.
Wire crashes ALWAYS on Opera. Since I have constantly this problem (I have the latest opera version on a lenovo ideapad 510) I normally type and inmediately close the app so I do not get the whole Opera and other windows I have open to crash and collapse as well. I hear the sound on the phone when the person replied and I open it again.
So,  mr Herdmann, sorry to informa you that the issues is not closed neither solved. Maybe it would be good if you install yourself Opera and try it out. 
I am not changing my browser and I am still a truthful user of wire. 
I hope soon to get a new more optimistic message.
Good night!

## What steps will reproduce the problem?
1.
2.
3.

**Comment by gregor** [comment]
@malaquita Closing the issue was not meant to  indicate it was solved. We have simply not gotten enough information to reproduce. For me it doesn't always crash.

Please update your report to include browser and Windows versions so we can check on your particular environment. At which point in the app life cycle does it crash?

**Comment by Malaquita** [comment]
@gregor For me it crashes always, that is why I developed that Alternative system. I have Windows 10, I have the wire app on my Lenovo ideapad 510s and yes, I use Opera latest version and DuckDuckGo browser. When does it crash? When any message comes in. Then it shows the blue wire window saying that wire is open in another window. It takes 3 minutes to be able to reconnect.

**Comment by bennycode** [comment]
@Malaquita we improved the quality of our app a lot within the last 3 years. Please report back if you are still experiencing crashes on Opera.
