### ISSUE TITLE
Not seeing my latest messages

### ISSUE THREAD

**Issue by tomerbarkan** [wireapp/wire-webapp#1687]
## Wire for Windows Version 
2.15.2750

## Operating System
Windows 10

## What steps will reproduce the problem?
1. Send a message to a friend
2. Switch to another conversations
3. Switch back on the first conversation

## What is the expected result?
I See the message I sent in step #1

## What happens instead?
I see previous messages but not the one in #1.

## Additional Info
If I wait a while and switch to another conversation and back again, then more of my messages appear.
It seems there may be some kind of delay that causes Wire to only show messages up until ~1 minute before, instead of showing latest messages.

See first screenshot, I sent "testing 1" and "testing 2". You can see the time stamp 14:47.
Then in my second screenshot, after switching to another conversation and then back sent "testing 3", "testing 4", and "testing 5", but not the previous 2.
A while later if I switch to another and back then I see all the messages in the correct order.
Also, Wire shows a timestamp around 1 minute ahead of my PC time, so I believe it has to do with that.

![image](https://user-images.githubusercontent.com/9161786/30273099-2f149fa6-9700-11e7-8eda-c70dae33b0a8.png)

![image](https://user-images.githubusercontent.com/9161786/30273109-3c7d8d2e-9700-11e7-9292-a8356a7e7a1b.png)

**Comment by tomerbarkan** [comment]
I have no idea where Wire takes it's timestamp from, since it always shows ~1 minute ahead of my OS time.

**Comment by gregor** [comment]
The timestamp is from our servers. When sending messages, the timestamp will be updated later on. Looks like your messages just seem out of order due to the timestamp difference. We are working on improvements even on the sending side. But can you please sync your OS clock and check if the problem still exists?

**Comment by tomerbarkan** [comment]
My OS NTP is acting up so I can't keep constant sync. I manually adjusted the time to be 2 minutes ahead and the problem doesn't occur.

Glad to hear you're working on a solution cause in this day and age time difference between server and client shouldn't be an issue :)

**Comment by tomerbarkan** [comment]
BTW apologies for posting under webapp, just did google search for "wire bug report" and it took me here, didn't notice it was specifically for webapp. The issue is in Windows Desktop in case it wasn't clear.

**Comment by gregor** [comment]
No worries. Most of the desktop issues for us are actually webapp problems as we base our desktop offerings on Electron that run the webapp. I will then go ahead and close the issue. Improvements should be making their way into the coming releases. Please let us know if we still behave unexpectedly in a month or two,
