### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by Super-Baleine** [wireapp/wire-webapp#1690]
## Browser Version
Firefox 52.3

## Installed Browser Addons
ublock origin

## Operating System
Debian Jessie

## What steps will reproduce the problem?
1. load |wire](app.wire.com)
2. see your CPU at 100%

## What is the expected result?
Once the page loaded, it shouldn't take so much resources.

## What happens instead?
The CPU runs up to 100%.

**Comment by muellert** [comment]
I personally don't remember the CPU being stuck at 100%, but Wire sure does use a hell lot of CPU and memory, and makes my laptop sound like a vacuum cleaner. I would highly appreciate if Wire would use less resources, and don't care about spiffy visual effects. FWIW, I have an i7 and 8GB memory.

**Comment by mythsunwind** [comment]
The CPU load that you see does not come from visual effects, but from Wire being a full End-to-end encrypted (E2EE) messenger. Doing cryptographic computation is very slow and resource intensive with JavaScript in a Browser. We are currently working on making this much faster by adopting to the newest web technologies. In the meantime you can make your own experience a bit nicer by downloading and installing our desktop applications for macOS or Linux. Both use libsodium-neon, which replaces the pure JavaScript version of the crpytographic library with a much faster version written in c/rust.

You can read more about it here: https://medium.com/@wireapp/speeding-up-crypto-on-wire-desktop-apps-3ff37fc98c3f

**Comment by Super-Baleine** [comment]
hi,

Although, this issue even happens when I don't receive any message.

**Comment by mythsunwind** [comment]
@Super-Baleine what is your hardware setup? What browser/version are you using?

**Comment by Super-Baleine** [comment]
old pentium haha, Firefox ESR 52.4

**Comment by andreasboll** [comment]
This issue is still reproducible with Firefox ESR 52.5
It happens before logging in and is probably related to the following errors on web console:

```
TypeError: a.RTCPeerConnection is undefined     wire-vendor.min.js:6:21501
    [10]</e.shimRemoveStream    https://app.wire.com/min/wire-vendor.min.js:6:21501
    [4]</b.exports  https://app.wire.com/min/wire-vendor.min.js:5:29928
    [3]</<          https://app.wire.com/min/wire-vendor.min.js:5:28557
    [3]<            https://app.wire.com/min/wire-vendor.min.js:5:28490
    e               https://app.wire.com/min/wire-vendor.min.js:4:27433
    a               https://app.wire.com/min/wire-vendor.min.js:4:27607
    <anonym>        https://app.wire.com/min/wire-vendor.min.js:4:27198
    <anonym>        https://app.wire.com/min/wire-vendor.min.js:4:27165
    <anonym>        https://app.wire.com/min/wire-vendor.min.js:4:26893

ReferenceError: platform is not defined     wire-app.min.js:2:9712
    d.is_electron   https://app.wire.com/min/wire-app.min.js:2:9712
    <anonym>        https://app.wire.com/min/wire-app.min.js:2:10581
    <anonym>        https://app.wire.com/min/wire-app.min.js:2:9131
```

Please restore support for Firefox ESR 52

**Comment by gregor** [comment]
@andreasboll Support for Firefox ESR is there.

Your error message is an instance of #1915. You have disabled webRTC in your browser and the webRTC adapter that is shimming away the implemenation differences in browsers was not properly loading in that case. The issue has been reported and fixed in the dependency (https://github.com/webrtc/adapter/issues/730) and the fix will be part of our next release in the coming days. Until then you either have to use another browser or ensure that webRTC is not disabled.

**Comment by andreasboll** [comment]
@gregor Thanks, enabling webRTC solves my issue. Looking forward to the next release of Wire-WebApp.

**Comment by BatmanAoD** [comment]
@mythsunwind Does "adopting to the newest web technologies" mean compiling the C/Rust version to WebAssembly? If so, is there a tracking issue for this somewhere?
