### ISSUE TITLE
Photos don't keep aspect ratio when viewed

### ISSUE THREAD

**Issue by immutability** [wireapp/wire-webapp#1714]
In the web version, the photo thumbnails are displayed correctly in a conversation, but once you click the thumbnail, the full-screen photo fills the entire screen, ignoring the aspect ratio. Usually hardly noticeable with landscape photos but quite a problem with portrait photos. The same photos display OK in the mobile app. I've only been using Wire since August 2017 and never saw this work OK.

## Wire for Web Version
2017-08-31-14-21-prod

## Browser Version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

## Operating System
Windows 10

## What steps will reproduce the problem?
1. open a conversation with photos
2. click a photo thumbnail
3. the full-screen photo doesn't maintain aspect ratio but fills entire screen

Screenshots attached.

![wire_full_photo](https://user-images.githubusercontent.com/1141653/30581557-e2453fba-9d20-11e7-8bcb-b996e7ed80fb.png)
![wire_conversation_w_thumb](https://user-images.githubusercontent.com/1141653/30581556-e2203db4-9d20-11e7-8390-7df279ca50a6.png)

**Comment by Beep6581** [comment]
+1

**Comment by Bomper** [comment]
Surprised this bug rather glaring hasn't been fixed yet. Nobody else getting selfies? :)

**Comment by gregor** [comment]
This was fixed by #2535 a while ago.
