### ISSUE TITLE
CERT EXPIRED! WHOLE SYSTEM IS DOWN!

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire-webapp#17239]
Currently it is not possible to use any Wire app because the certificate for app.wire.com has expired.

Your app.wire.com certificate expired on `Apr  9 23:59:59 2024 GMT`, but it is currently `Apr 10 00:52:31 2024 GMT`.

```
user@disp2526:~$ echo -n | openssl s_client -showcerts -connect app.wire.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > mycert.pem
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
verify return:1
depth=0 C = CH, ST = Zug, L = Zug, O = Wire Swiss GmbH, CN = *.wire.com
verify error:num=10:certificate has expired
notAfter=Apr  9 23:59:59 2024 GMT
verify return:1
depth=0 C = CH, ST = Zug, L = Zug, O = Wire Swiss GmbH, CN = *.wire.com
notAfter=Apr  9 23:59:59 2024 GMT
verify return:1
DONE
user@disp2526:~$ 

user@disp2526:~$ date -u
Wed Apr 10 12:52:31 AM UTC 2024
user@disp2526:~$ 
```

Please update the your servers' certificate.

Note that the cert provided by https://wire.com is valid, so perhaps you can copy that to the other load balancer -- both are *.wire.com wildcard certs, after all.

**Comment by maltfield** [comment]
I also created another ticket to create a status page as, surprisingly, wire doesn't appear to have one for their infrastructure?!? Kinda a red flag of immaturity for potential customers tbqh..

 * https://github.com/wireapp/wire/issues/409

**Comment by gopherit** [comment]
I remember this happened about one year ago as well, leading to 4-6 hours of unavailability.

My desktop (Windows) clients are able to connect now, so I assume a new certificate has been issued.  My Android clients never lost connectivity.

The outstanding issue as of right now is that images/attachments/videos are un--
^ And in the middle of typing that sentence, images/attachments videos are loading correctly on both mobile and desktop.  Everything is back to normal, and I'm not seeing any data loss or anything.  Phew.

**Comment by maltfield** [comment]
:cricket: Is there anyone working at Wire these days?

**Comment by maltfield** [comment]
See also discussion on Reddit

 * https://old.reddit.com/r/wireapp/comments/1c08eib/cant_connect_to_wire_desktop_expired_cert/

**Comment by b1pb1p** [comment]
Thanks for reporting this @maltfield ; this is now fixed.

**Comment by maltfield** [comment]
@b1pb1p can you please tell us what is the appropriate high-priority comms to use in the future for such issues? Is this the best place to report global outages like this?

**Comment by b1pb1p** [comment]
@maltfield We will consider putting up a status page. I'll follow up on the issue you created.

**Comment by derkommutator** [comment]
Perhaps monitoring the cert in the first place would be a good idea.

**Comment by b1pb1p** [comment]
We want to share a bit more details here about what happened : 

- We renewed the certificates before expiration and replaced them on most services.
- However, a misconfiguration in the CDN of Wire Cloud led to this partial outage.
- New sessions of the Web and Desktop clients, Teams Management service, and file services (for all clients) were impacted.
- Existing Web/Desktop sessions, mobile clients, Messaging, Calls, and Conference Calls weren’t impacted. 

We are taking steps to prevent this from happening again in our certificate rotation procedure.

We apologize for the inconvenience you experienced and thank you for your patience and understanding. 

I’m closing this issue now as the outage is resolved.
