### ISSUE TITLE
Device key for web app seems to change sporadically on same device, but still appear magically trusted from other devices

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1724]
I can only remember verifying my devices once with the respective fingerprints. However, I just checked and I have *multiple fingerprints* now for each device, but all of them still trusted. From this I conclude that the device key for web app seems to change sporadically even on same device, but still appear magically trusted from other devices for whatever reason. If this is an intended process, then it should be more transparent to the user what is going on.

## Wire for Web Version
`2017-08-31-14-21-prod`

## Browser Version
`Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0`

## Installed Browser Addons
`HTTPS Everywhere`
`uBlock Origin`
`User Agent Switcher`

## What steps will reproduce the problem?
1. Have multiple devices
2. ???

## What is the expected result?
one device initially has one fingerprint, I mark that one as trusted, and then no additional trusted fingerprints will appear for the same device

## What happens instead?
device seems to have multiple fingerprints at some point, but automatically trusted

**Comment by gregor** [comment]
What leads you to the conclusion that a device has multiple fingerprints? The fingerprint of a device should never change. In cases where the cryptographic identity of a device was erroneously recreated, messages would fail to decrypt on the receiving end for exactly that reason - fingerprints not matching.

**Comment by ghost** [comment]
> What leads you to the conclusion that a device has multiple fingerprints?

Ah, I assumed "DESKTOP" listed multiple times was the same device, but I guess it means multiple desktop devices.

Anyway, they are all marked as trusted and I'm pretty sure I didn't mark them all as trusted. So what is going on?

Edit: ah nevermind. I'm being silly, they aren't actually marked as trusted/verified. Which makes this issue ticket nonsense I suppose

**Comment by gregor** [comment]
Thanks for your update.

For other users you indeed only see the device type - phone, tablet or desktop - of which a user can have multiple each. Will note down the feedback and foward your feedback/confusion to see how we can improve this in the future.
