### ISSUE TITLE
Gif: Remain in Grid View After Pressing 'Try Again' Button

### ISSUE THREAD

**Issue by cwmke** [wireapp/wire-webapp#1773]
## Wire for Web Version
2017-09-26

## Browser Version
Firefox Nightly 58.0a1 (2017-09-29) (64-bit)

## Operating System
Fedora 26

## What steps will reproduce the problem?
1. Type a word and click the 'GIF' button.
2. Click the grid button located in the upper left corner to show several options at once.
3. Click 'Try Another'

## What is the expected result?
Multiple new gif results are shown in a grid.

## What happens instead?
The window changes back to showing an individual gif.

Personally I always click the grid button to see more gifs at once but when I click 'Try Again' while in grid view, it reverts back to the individual view. I propose that the grid view should remain when clicking 'Try Another'.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have a lot of ideas on how to improve the GIF experience but unfortunately do not have the resources to work on it at this time. We will keep your idea in mind when we get back to the feature.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
