### ISSUE TITLE
Future For  Admin Server : Public Group

### ISSUE THREAD

**Issue by Nemra1** [wireapp/wire-webapp#1776]
Is it possible in the future Allow to    Admin Server create Public Groups that appear for each new subscriber

**Comment by gregor** [comment]
@Nemra1 Thanks for your feedback. This is definitely something to consider and I will forward it internally. I will go ahead and close this issue though as this repository is used to track issues specific to the webapp. General product inquieries and feedback are better directed at us via our support channels or the generic repository found at https://github.com/wireapp/wire.
