### ISSUE TITLE
System notifications from app.wire.com in FF are not working

### ISSUE THREAD

**Issue by marfous** [wireapp/wire-webapp#178]
System notifications under Firefox are not working. I have pinned tab in my FF 47.0 and no notification comes. But it works like a charm in the Chrome. Please could you take a look on that? Thanks.

**Comment by lipis** [comment]
Which operating system are you using?

**Comment by lipis** [comment]
Works fine on my machine.. :/ OS X - FF 48 (latest)
<img width="340" alt="screen shot 2016-09-06 at 19 07 27" src="https://cloud.githubusercontent.com/assets/125676/18283399/544bc772-7465-11e6-83e4-95b47567e6c2.png">

**Comment by marfous** [comment]
Yep, I have the notification allowed on that page. I'm using Fedora 23.

**Comment by mohammadrafigh** [comment]
@marfous did you update your FF to a recent version? (maybe it's just a bug in FF 47 notifications)

**Comment by marfous** [comment]
Looks to be working well now. Thanks for reminding it. :)
