### ISSUE TITLE
Support for Low end devices; Kindles/E-INK e-readers or old computers

### ISSUE THREAD

**Issue by BrokenLatchhook** [wireapp/wire-webapp#17885]
Please add webapp support for kindles/e-ink ereaders or low end devices.
I have tested wire webapp on my kindle paperwhite 11, it crashes the whole kindle if I try logging into wire.

**Comment by lipis** [comment]
This is impossible my friend.. Try reading some books instead of messaging on Kindle :)

**Comment by BrokenLatchhook** [comment]
ok
