### ISSUE TITLE
Backslash is missing in sent text

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1822]
## Wire for Web Version
Version 2017-10-09

## Browser Version
Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

## What steps will reproduce the problem?
Send following line: env | grep 'LANG\\|LC_'

## What happens instead?
Backslash is missing in text received by user: env | grep 'LANG|LC_'

**Comment by mythsunwind** [comment]
When you send source code or command lines, I recommend to use markdown-syntax to make sure all special characters are included:

```
```env | grep 'LANG\|LC_'```
```

**Comment by ghost** [comment]
Thanks for recommendation!
