### ISSUE TITLE
Remember me doesn't work in the FF under Linux

### ISSUE THREAD

**Issue by marfous** [wireapp/wire-webapp#183]
I'm using app.wire.co in pinned tab in Firefox 47.0 (OS: Fedora 23). Even when I check the "Remember Me" checkbox I need always to reenter my credentials to sign-in to the Wire after reopening my browser.

**Comment by gregor** [comment]
@marfous Which URL do you have exactly pinned to the tab? If it is not the blank domain but https://app.wire.com/auth you will be asked to log in every time despite the valid cookie. Please let us know if "Remember me" is still not working as expected.

**Comment by marfous** [comment]
Yeah, the URL was really wrong. I'm very sorry for the false report, I'm closing it now.

**Comment by gregor** [comment]
No, worries. We are always happy to help.
