### ISSUE TITLE
Shortcuts should be optional.

### ISSUE THREAD

**Issue by wjtk4444** [wireapp/wire-webapp#1846]
First of all, I would like to point out that what I'm reporting here is rather an annoyance than a real issue.
`alt + ctrl + D` key combination doesn't prevent any characters from being typed (Unlike in [#94](https://github.com/wireapp/wire-webapp/issues/94)), it's just being pressed by me (and probably some other users) accidentially. 

I believe that the best solution to this problem would be to add an option to disable shortcuts globally (which would be a temporary quick-fix). In the more distant future ([comments under #94](https://github.com/wireapp/wire-webapp/issues/94#issuecomment-290714090))
> Unfortunately our design team told us today that there is no plan to redesign keyboard shortcuts any time soon.

I would like to see a proper shortcuts menu (both in web and desktop clients) which would allow user to:
-create custom shortcuts
-edit existing shortcuts
-enable or disable shortcuts
-enable or disable shortcuts globally (all at once)

**Comment by mfrydrychowicz** [comment]
+1

**Comment by gregor** [comment]
Thank you very much for your feature request. Certainly a nice idea on how to improve the experience. At this time we do not have the resources to work on this feature though. We will keep it in mind for possible consideration for our future roadmap.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by wjtk4444** [comment]
So, I ended up with a working solution - an usercript to capture and ignore certain key combinations.
If anyone is struggling with a similar issue, here's my code. 
Obviously, you need a script manager, such as [violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) to run the script.

Currently it blocks the following key combinations:
`Alt-Ctrl-K`, `Alt-Ctrl-D`, `Alt-Ctrl-S`
but you can modify it to you liking.
```
// ==UserScript==
// @name Wire - block Alt-Ctrl-(K | D | S) keyboard shortcuts
// @namespace Violentmonkey Scripts
// @match https://app.wire.com/*
// @grant none
// ==/UserScript==

window.addEventListener ('keydown',  reportKeyEvent, true);

function reportKeyEvent (zEvent) {
    //--- Was a Alt-Ctrl-(K | D | S) combo pressed?
    if (zEvent.altKey && zEvent.ctrlKey && (zEvent.code === "KeyK" || zEvent.code === "KeyD" || zEvent.code === "KeyS")) {
		    //alert("Alt-Crtl-" + zEvent.code + " combo pressed");
        zEvent.stopPropagation ();
        zEvent.preventDefault ();
    }
}
```

**Comment by pete-willard** [comment]
It's 2019 and this is still an issue unfortunately

**Comment by pete-willard** [comment]
@gregor Has a slither of resources fred up perchance? This issue is still driving me nuts after all this time :( Please let us disable shortcuts.
