### ISSUE TITLE
unable to login using localhost:8888

### ISSUE THREAD

**Issue by segahm** [wireapp/wire-webapp#1853]
## Wire for web version

prod. #a2b4c41 2017-10-25

## Browser version

Version 61.0.3163.100 (Official Build) (64-bit)

## Operating system
MacOS

## What steps will reproduce the problem?
1. clone the repo locally
2. yarn install, yarn start
3. attempt to login on localhost:8888

## What is the expected result?
logged in

## What is the actual result?
Error message: Please verify your details and try again.

**Comment by gregor** [comment]
Localhost by default points to our development backend. If you want to try localhost with a production account, please use localhost:8888/auth/?env=prod
