### ISSUE TITLE
Locally installed webapp keeps signing me out

### ISSUE THREAD

**Issue by link2xt** [wireapp/wire-webapp#1881]
I am running web application locally with `yarn` as a replacement for desktop version which I can't run on my desktop because electron is not supported here. Unlike web version hosted on https://app.wire.com/, it keeps logging me out after some timeout and displays message "You were signed out because your session expired."

I expect it to behave the same as https://app.wire.com/
I don't sign "this is a public computer" so what is the reason to log me out after timeout?

**Comment by gregor** [comment]
If you are running the app locally our backend will reject the attempt to refresh your access token after 15 minutes. This is a security measurement that you can only do so from whitelisted domains. The only way around that would be running your browser with websecurity disabled - which I would advice against.

**Comment by link2xt** [comment]
Just for reference for anyone reading this later: Same-Origin policy is disabled in Chrome by `--disable-web-security` flag.

**Comment by link2xt** [comment]
So well, the only real solution is to port Electron or use Linux.
With webapp it may be possible to workaround by modifiying `hosts` file locally and pretending I am running app.wire.com, but it does not look like a great idea too.
Thanks.

**Comment by link2xt** [comment]
Well, maybe you can add more meaningful error message or warning instead of "You were signed out because your session expired." for this case?

**Comment by gregor** [comment]
@labdsf Thanks for the feedback. Unfortunately we do not detect that the access token request failed because of the same-origin policy. Thus we cannot be more specific with the error message.
