### ISSUE TITLE
Web app does not load

### ISSUE THREAD

**Issue by xrchz** [wireapp/wire-webapp#1915]
## Wire for web version
2017-11-10-10-41-prod

## Browser version
Mozilla/5.0 (Windows NT 6.1; rv:56.0) Gecko/20100101 Firefox/56.0

## Installed browser addons
none

## Operating system
Linux 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux

## What steps will reproduce the problem?

1. Navigate to https://app.wire.com

## What is the expected result?
Wire web app loads, either presenting a login screen or sign up screen, or the chat window if already logged in.

## What is the actual result?
The loading screen shows forever.

screenshot: https://img42.com/Mm9Kk

**Comment by bennycode** [comment]
Hi @xrchz! Thanks for your report. 👍 

Do you see any errors when you open the [Firefox Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console)?

Can you also please check if there is anything listed up for "https://app.wire.com/" in your "Indexed DB"?

![Screenshot](https://user-images.githubusercontent.com/469989/33022998-200d4678-ce07-11e7-9f60-ba39828829da.PNG)

**Comment by xrchz** [comment]
Thanks a lot for your reply @bennyn ! The app started working again for me, so I can't reproduce the problem. However, if it comes back I will follow your next steps and reopen.

**Comment by xrchz** [comment]
I'm reopening this issue because I have the problem again, now with a new browser version: Mozilla/5.0 (Windows NT 6.1; rv:57.0) Gecko/20100101 Firefox/57.0

I have no entries in Indexed DB (or any other Storage) -- I deleted them all.

Same symptoms as above.

I see this on the console:
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Tridactyl content script loaded, boss!
content.js:2520:1
Loaded initial state: 
Object { mode: "normal", cmdHistory: […] }
content.js:256:9
TypeError: asm.js type error: Disabled by debugger
wire-vendor.min.js
TypeError: a.RTCPeerConnection is undefined
[Learn More]
adapter.js:3776:8
INIT
content.js:1675:13
ReferenceError: platform is not defined
[Learn More]
Environment.js:60:23
Loaded initial state: 
Object { mode: "normal", cmdHistory: […] }
```

**Comment by gregor** [comment]
Have you disabled webRTC in your browser configuration? We are relying on the webRTC adapter shim from the webRTC group to mitigate the implementation differences of browsers. The current version is apparently not failsafe if you have webRTC disabled in your browser. Can you confirm this?

**Comment by aaannz** [comment]
I had the same problem and indeed if `media.peerconnection.enabled` if `false` (see about:config) wire does not load and no error is presented.

**Comment by gregor** [comment]
Thanks for letting me know. I opened an issue on the library to get this sorted out.

**Comment by xrchz** [comment]
Enabling `media.peerconnection.enabled` solves the problem for me.

**Comment by gregor** [comment]
webRTC adapter was updted to version 6.0.3 which addresses the RTCPeerConnection shim issue.

https://github.com/webrtc/adapter/releases/tag/v6.0.3
