### ISSUE TITLE
Please add new icon in tab when new message

### ISSUE THREAD

**Issue by dibok** [wireapp/wire-webapp#1954]
Hi,
I'm using Wire as pinned tab in Opera browser instead of desktop app because I always have browser opened and I don't like Electron solution which consume too much resources and in the fact it is just another Chrome instance which Opera has already loaded. Since Wire's desktop notifications works great in Opera (Ubuntu Linux), I sometimes missing messages events because Wire icon on tab is not changing. Could you add some asterisk or small red circle icon on tab when new event occurred in Wire? Something what Skype web version do.
Regards

**Comment by lipis** [comment]
I like the idea.

**Comment by gregor** [comment]
https://github.com/wireapp/wire-webapp/pull/4804

**Comment by gregor** [comment]
We added a notification aware favicon. This was deployed to production earlier this week.
