### ISSUE TITLE
Email autocompletion

### ISSUE THREAD

**Issue by 1j01** [wireapp/wire-webapp#198]
Form autofilling doesn't work on the account creation form in Chrome.

**Comment by helenakos** [comment]
Hey @1j01, thanks for reporting. We couldn't reproduce this one though

**Comment by 1j01** [comment]
To be clear, it works on the login form. By "couldn't reproduce" do you mean clicking on the Name or Email fields on the account creation form triggers a dropdown for you?

**Comment by helenakos** [comment]
That's correct. But you are right, it no longer works on the account creation form. Thanks, will open a ticket internally.

**Comment by 1j01** [comment]
So in conclusion, it works (worked?) but it doesn't work?

**Comment by helenakos** [comment]
In conclusion, it doesn't work.
