### ISSUE TITLE
Lag when sending messages

### ISSUE THREAD

**Issue by hakusaro** [wireapp/wire-webapp#200]
So, I don't know if this is a fairly commonly noticed issue, but I figured I'd speak up. One of the most annoying things about using Wire is that there's a good delay between pressing enter on the input field and the message actually reaching the local chat history. It feels like lag.

This is because, at least from my understanding, the method [`_send_and_save_generic_message`](https://github.com/wireapp/wire-webapp/blob/dev/app/script/conversation/ConversationRepository.coffee#L1106) in `ConversationRepository.coffee` makes a point to synchronize sending the message across the network before putting it in the local chat window.

I can understand the ambivalence as far as user interfaces go towards adding something like Telegram/WhatsApp check marks, but the benefit to using a separate visual indicator for sent messages means that the UI thread isn't clogged up waiting for network tasks each time a message is sent. At least to me, this kind of lag is unbearable -- I would much rather have a message appear to have been sent and acknowledged after the fact, rather than having it only appear if it was sent.

I would have just sent a PR if there was an easy solution, but I feel like it probably needs to be discussed properly, instead.

**Comment by herrmannplatz** [comment]
I totally agree with you. This is something that is on top of our agenda and we already started working on fixing this. Rendering the message immediately would improve the whole experience of the app.

**Comment by hakusaro** [comment]
@herrmannplatz any idea on an ETA, or...? (read: is it worth me changing this locally and recompiling the electron app, or is it going to happen soon?)

**Comment by herrmannplatz** [comment]
soon :)

**Comment by herrmannplatz** [comment]
this is now merged into our dev branch.

**Comment by hakusaro** [comment]
Glad to hear it! Thank you!

**Comment by gregor** [comment]
https://github.com/wireapp/wire-webapp/pull/222

**Comment by hakusaro** [comment]
@herrmannplatz (I can confirm enjoying wire much more now)
