### ISSUE TITLE
On-premises installation

### ISSUE THREAD

**Issue by kbrandwijk** [wireapp/wire-webapp#201]
Hi, I love the Wire app, and I was very excited to find the open source here. I can install and run every version locally, so that's all fine, and I'd love to build further on this platform. However, it started me thinking about how to set up an on-premises solution for enterprise communications. The sources available however seem to be missing the server part. Are there any plans to release the sources for the server side any time soon, or are there other possibilities to get Wire running on-premises (so with local server)?

**Comment by helenakos** [comment]
Hey @kbrandwijk , thanks for the feedback! We're really happy to hear that you want to build further on top of Wire platform. There are indeed plans to release the sources for the server side, but there are currently no committed dates for the release.

**Comment by helenakos** [comment]
@kbrandwijk If you want to talk more about this topic and other examples of using Wire for business, please reach out to siim@wire.com or add him on Wire: siim@wire.com
