### ISSUE TITLE
You cannot call because your computer does not have a microphone.

### ISSUE THREAD

**Issue by CorvusCorax** [wireapp/wire-webapp#2021]
It's not possible to call from or to a computer with no microphone / recording device / driver.

I tried to use wire (in combo with desktop sharing) to help a friend troubleshoot his desktop-audio problems, but I can't establish a connection because wire refuses to take or make a call when no microphone is detected.

## Wire for web version

2017-11-10-10-41-prod

## Browser version

Probably any, tested with Chrome and Firefox

## Installed browser addons

Any

## Operating system

Windows - theoretically any.
(Some Linux distributions provide a fake audio device if no microphone is present, as such not triggering the error)

## What steps will reproduce the problem?

1.  Setup wire desktop client on a system with no microphone
OR
1. Log in to the wire web app on a system with no microphone
2. Attempt to call OR
2. Attempt to receive a call

## What is the expected result?

Call should get established, but with a warning message that audio recording isn't working. The call should transfer silence instead of audio. Desktop sharing, video and other call features should still work.

## What is the actual result?

Call cannot get established with above error message:
**You cannot call because your computer does not have a microphone.**

**Comment by CorvusCorax** [comment]
Thanks for the heads-up regarding double filing in both webapp and desktop. I wasn't sure where exactly to file the bug, or whether (depending how you are referencing bugs in commits internally) it might be more convenient to have an issue ID within the same repo that related code changes might be made to) sorry for any inconvenience caused, I didn't want to create extra work :)

**Comment by Aikatsui** [comment]
Duplicate of #7018

**Comment by bennycode** [comment]
In our latest release we improved the media device handling a lot. Please give it another try. :)
