### ISSUE TITLE
Accepting video calls silently fails if no camera - no error message to either caller or receiver

### ISSUE THREAD

**Issue by CorvusCorax** [wireapp/wire-webapp#2022]
Wire-webapp is also affected by this issue:
https://github.com/wireapp/wire-desktop/issues/1144

Browser Firefox 57.0.1 on Ubuntu 64bit 16.04 LTS
(most likely this is a browser and system independent bug)

No webcam on system

**Comment by lipis** [comment]
Since the connected issue has more info, I will close this one. In the future it's enough to report it here or on Desktop, but not on both :) Thank you for the report.
