### ISSUE TITLE
TLS improvement

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#204]
Hi.

It's seems that the TLS implementation has some free room for improvement: https://www.ssllabs.com/ssltest/analyze.html?d=prod-nginz-https.wire.com

Certicate staple etc.

Furthermore, certificate pinning could be done for the Atom desktop client and iOS one.

**Comment by raphaelrobert** [comment]
Thanks for pointing it out. We regularly make adaptations to the supported cipher suites, but things evolve obviously over time.

Regarding certificate pinning: We do it on mobile clients (iOS and Android). On our desktop app we use Electron, which in turn uses the Chromium mechanisms when checking certificates. We found this to be good enough given our threat model, but we don't rule out that it will be changed in the future.
