### ISSUE TITLE
cannot login when using web-app

### ISSUE THREAD

**Issue by TommyTeaVee** [wireapp/wire-webapp#2156]
## Wire for web version
3,9

## Browser version
chromium  Version 62.0.3202.94

## Installed browser addons
yes

## Operating system
Ubuntu 16 LTS
## What steps will reproduce the problem?

1.When I try to login after successfully building web-app , the app return "Please verify your initials and try again ", if I use email
2. ...When I try to login using phone number, the app returns "This number is forbidden" error 
3. ...

## What is the expected result?
Web app to login using my account
## What is the actual result?
login error

**Comment by mythsunwind** [comment]
For these kind of questions please directly talk to our friendly support: https://support.wire.com/hc/en-us/requests/new

They can help you with problems regarding your account and resetting your password etc.
