### ISSUE TITLE
https://app.wire.com should allow mobile browsers

### ISSUE THREAD

**Issue by fdelapuente** [wireapp/wire-webapp#217]
Hi,
In my Phone with I cannot use the wire-webapp. I think my browser's user agent is rejected just for being a mobile browser. See link to the suspected culprit code[1]

If you want to enforce the usage of the native apps on mobile devices, the code should make sure the device being rejected is using one of the natively supported platforms. Mine is not (Ubuntu Touch OS).

Users running Not-So-Popular Mobile OS will really appreciate your support on this.

Thanks!

[1] https://github.com/wireapp/wire-webapp/blob/7ccb9a015544e9265d4b378d54b40bc9ee0cc4df/aws/main.py#L74

**Comment by gregor** [comment]
This is a deliberate design decision as the current Wire UI design is not aimed at small screen and really frustrating to use there. Currently we are very restrictive what we allow to access in order not raise any expectations on other clients.

**Comment by fdelapuente** [comment]
Hi Gregor, thanks for the clarification!

I'll file a separate enhancement request for the UI design limitation for different form factors.

Best Regards.

**Comment by fdelapuente** [comment]
Hi @gregor,

It would be a great usability improvement if the Blocking mechanism is changed to be driven by the actual minimum screen width/height constraints of the UI rather than the user agent being a mobile device. With current behaviour all Mobile devices are being banned ignoring the fact that the device could be a tablet with enough screen space or (in my case) an convergent device that could have either a native normal size display or a temporary attached external display with more than enough space for the wire-webapp client.

Best Regards.

**Comment by gregor** [comment]
@fdelapuente Sure. But with the current way we essentially control the environment and have a much smaller test matrix. For a technically advanced user like you knowing that something is not supported but might work is ok. For an average user we will get lots of customer service complaints and bad reviews if we allow these untested setups to access the app. We will certainly consider your input. But currently a change is not planned.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
