### ISSUE TITLE
Firefox'es new privacy firstparty isolation feature messes with wire's ability to keep history

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-webapp#2173]
## Wire for web version
2017-12-20-12-48-prod

## Browser version
Firefox Quantum 57.0.1 (64-bit)

## Installed browser addons
Adblock Plus, Ghostery, NoScript, Stylish

## Operating system
Linux Mint (64-bit), 16GiB RAM, Intel® Core™ i5-3320M CPU @ 2.60GHz × 4

## What steps will reproduce the problem?

1. Go to about:config
2. Set `privacy.firstparty.isolate` to `true`
3. Log into app.wire.com as NOT a public computer
4. Try opening app.wire.com again the next day.

## What is the expected result?

Wire logs in automatically without asking for a password and presents the previous messages.

## What is the actual result?

Wire asks for username and password and then informs me that this is a new computer and message history will not be shown here.

**Comment by gregor** [comment]
With the browser in this state the IndexedDB will be cleared after each browser session. We rely on it to store client information and you history. If your browser deletes it, we have no way of showing you your previous messages. This is kind of like asking to show the contents of the file after manually deleting it. Nothing we can do.

**Comment by 0ki** [comment]
Thanks for clarifying that. Sounds like a bug in firefox. Isolation should not be clearing IndexedDB. I'll file the bug with them.

**Comment by jocull** [comment]
@0ki Post a link to the bug report when you make it. I'm interested in following the case.

**Comment by gregor** [comment]
@0ki Please also check if my assumption is actually valid. It is the only thing that makes logically sense in oder to explain the behavior. Just check you browser storeon the next day to see what is still there. IndexedDB, cookies, etc.
