### ISSUE TITLE
wire-webapp UI should be able to properly handle different screen resolutions/form_factors

### ISSUE THREAD

**Issue by fdelapuente** [wireapp/wire-webapp#218]
Hi,

This enhancement request is related to #217 and is a dependency to fix that one.

The wire-webapp should adapt properly to different screen resolutions and form factors.

As an example, in narrow screens (Like a Phone in portrait position) the buttons for Video/Audio call get easily out of the screen and the user must manually workaround the UI in order to get there.

Thanks!

**Comment by gregor** [comment]
That's why we block those clients from accessing the web app. We do have native applications for Android and iOS and want to reduce the overhead created by maintaining a responsive design in our web application. We might reconsider this in the future but for now our UI is built and designed on the promise that we can always depend on a certain minimum width of the display.

**Comment by fdelapuente** [comment]
For the record I added a new comment on #217 proposing a change in the condition to reject the connection from a non-supported browser.

The problem with blocking by user agent is that you end up blocking a family of browsers under the assumption that all the clients running this browser will not have enough screen space to properly use the wire-webapp, while being unaware of actually detecting the real problem which is the actual space available in the browser viewport.

I can mention the following undesired outcomes of this approach:
1. A Desktop browser connecting to the webapp with a small window size will not be filtered out and still will be facing the UI design issues.
2. A Mobile browser will be rejected from the webapp even if it has enough space in its browser viewport.

Best Regards.

**Comment by lipis** [comment]
Web is a wild wild place indeed.. and we are officially supporting the [4 _major_ browsers](https://wire.com/download/) on Desktops..

**Comment by max-baz** [comment]
> We might reconsider this in the future but for now our UI is built and designed on the promise that we can always depend on a certain minimum width of the display.

@gregor, @lipis: I want to add another reason to reconsider this. Given that desktop apps in reality just load this same webapp, you have to consider how they are used when taking such decisions.

I can see that right now the minimal supported width is around 760px, below which the layout starts to break. However people on desktop rarely spend their time _exclusively_ in the chatting apps, instead most people do something, and on a side they have a chat app open, often resized to take as less space as possible.

Have a look at 3 screenshots below that demonstrate the case, where I'm reading github and having a chat app on a side. The 3 pictures show:
1. How Telegram app is able to take advantage of a narrow window size (notice: I use most of the screen space for my primary activity, but can occasionally keep chatting on the right). 
2. How Wire app looks like given the same window size (notice: chat is not even visible).
3. What is the minimal width that Wire requires without breaking the layout (notice: there is not much space left for doing primary activity, which is reading github in this example).

![7_174](https://cloud.githubusercontent.com/assets/1177900/21028457/935a02ca-bd95-11e6-8ebb-65ceaa835291.png)
![7_175](https://cloud.githubusercontent.com/assets/1177900/21028455/9353f6b4-bd95-11e6-8827-c734b72c061c.png)
![7_176](https://cloud.githubusercontent.com/assets/1177900/21028456/935580d8-bd95-11e6-9e8c-0fd9b4bb6929.png)

**Comment by bennycode** [comment]
I will close this issue because we now had a discussion and a final decision here: https://github.com/wireapp/wire-webapp/pull/543#issuecomment-268046541
