### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by sorin-davidoi** [wireapp/wire-webapp#2205]
Running the [aXe accessibility audit](https://www.axe-core.org/) reveals multiple issues:
<img src="https://user-images.githubusercontent.com/2109702/34908879-cf518a8a-f897-11e7-9d02-2aa6eef5d881.png" width="200"></img>

Another main one (which can't be detected automatically) is that **none** of the buttons are accessible - they use divs instead of buttons, which means that they can't be focused and screen readers are not aware of them. The native button tag might be a bit harder to style, but it bakes in so many things that it is better to use it rather than reimplementing all the accessibility for divs.

## Wire for web version

2017-12-20-12-48-prod

## What is the expected result?

Wire is accessible:
 - at the very least the audit passes for all pages
 - users can trigger any action using only the keyboard
 - ARIA is used to provide additional semantics

## What is the actual result?

Wire is basically unusable for screen reader users.

**Comment by gregor** [comment]
Thanks for bringing this up. We are aware of the fact that we do not deliver in this space. There has been an ongoing discussion for a while at https://github.com/wireapp/wire-desktop/issues/299. Thus I will go ahead and close this issue in favor of the one on the desktop repository.
