### ISSUE TITLE
Create account with "+" in the email

### ISSUE THREAD

**Issue by topless** [wireapp/wire-webapp#2212]
I am attempting to create a wire account with `myemail+wire@myprovider.com` so I can have my emails classified but it doesn't seem to be possible, I get the error `THIS EMAIL ADDRESS HAS ALREADY BEEN REGISTERED. LEARN MORE`

I have already an account with `myemail@myprovider.com`

Is it by design?

**Comment by Bomper** [comment]
Please support [email sub-addresses](https://en.wikipedia.org/wiki/Email_address#Subaddressing).

**Comment by raphaelrobert** [comment]
Yes, this is by design. This measure is in place to prevent spam accounts.
For email classification you would have to use sender classification with Wire emails.
