### ISSUE TITLE
Please support Markdown links

### ISSUE THREAD

**Issue by Bomper** [wireapp/wire-webapp#2234]
I was pleasantly surprised to see Wire supports basic Markdown formatting, like Slack. It would be great if it supported links too.

## Wire for web version

2017-12-20-12-48-prod

## What steps will reproduce the problem?

1. Message someone `Check out [Wire](https://wire.com)!`

## What is the expected result?
The recipient sees "Check out [Wire](https://wire.com)!`

## What is the actual result?
I see `Check out [Wire](https://wire.com)!`

![image](https://user-images.githubusercontent.com/34669048/35079547-17b0bc4c-fbbd-11e7-8a5b-eecaa57f0dda.png)

**Comment by lipis** [comment]
This is by design to avoid phishing, because you can easily do something like this: `[https://google.com](https://bing.com)`

**Comment by Bomper** [comment]
I use Wire with people I trust; otherwise I wouldn't bother with end-to-end encryption to begin with. I look at the status bar before clicking on links. I've also never been phished in 20+ years on the Internet.

Why not let *me* make the decision whether I believe my interlocutor is a phishing scam artist or not?

**Comment by lipis** [comment]
There is status bar on the Desktop app or on any of the mobile apps..
