### ISSUE TITLE
API guidelines / documents / instructions for WIRE chat integration 

### ISSUE THREAD

**Issue by projectsnc** [wireapp/wire-webapp#229]
Hi - i hope someone can help, im trying to find the API guidelines / documents / instructions for WIRE chat, to help me integrate it with another mobile app.

Can anyone point me in the right direction please ?

Many Thanks

**Comment by bennycode** [comment]
@projectsnc, we are currently working on a general "Hello World"-project, which will help developers to make their first move on the Wire platform. 

I will notify you here, once this is done. 😃

**Comment by taylorzane** [comment]
@bennyn Do you have an update on this? I've been considering Wire for our org, and I'd really love to integrate our tools with Wire. 

Thanks!

**Comment by lipis** [comment]
Stay tuned.. it's all we can say :D

**Comment by taylorzane** [comment]
👍 Thanks for the swift response! I'll be sitting on the edge of my seat.

**Comment by gregor** [comment]
We have since started our developer initiative. SDKs are being tested in closed beta. You can find all the information related to this at developer.wire.com.

**Comment by harishvishwakarma** [comment]
What happened to this API? developer.wire.com redirects to home page.
