### ISSUE TITLE
Impossible to escape backticks when nested inside another backtick

### ISSUE THREAD

**Issue by atomrc** [wireapp/wire-webapp#2335]
## Wire for web version

 2018-01-24-18-11-prod 

## Operating system

Arch Linux 

## What steps will reproduce the problem?

1. Go to a chat window
2. type " \`echo \\\`pwd\\\`\` "
3. hit send

## What is the expected result?

The expected generated HTML should be:
&lt;code>echo \`pwd\`&lt;/code>

## What is the actual result?

&lt;code>echo \\&lt;/code>pwd\`

**Comment by atomrc** [comment]
Well, even inside Github, it is not easy to do :)

**Comment by mythsunwind** [comment]
True, the only way i found is using the triple backticks in a single line for marking the whole paragraph as code. This way the single backticks don't need to be escaped.

**Comment by atomrc** [comment]
@mykola-mokhnach Oh that's nice, it works like a charm, thanks.

Actually I just discovered that you can use the double backtick also (not sure what is the difference though)

So I guess there is a clean workaround to my issue and I can close it :)
