### ISSUE TITLE
Be able to paste images from clipboard

### ISSUE THREAD

**Issue by zenitraM** [wireapp/wire-webapp#236]
To be able to send a picture from the clipboard to someone, by just hitting Ctrl/Command+V.

Telegram Web and other messenger apps support this, I find it handy and use it frequently

**Comment by gregor** [comment]
@zenitraM This is definitely something on our wish list as well.

**Comment by bennycode** [comment]
It's one of our most wanted features: https://github.com/wireapp/wire-webapp/issues/5

I think we have to do it. 👍

**Comment by GabMar** [comment]
+1 :)

**Comment by herrmannplatz** [comment]
In order to make this work we need an intermediate step in the UI to avoid accidently pasting to a conversation. Had a small discussion with our design how to implement this. Will link the PR once we have sth to show.

**Comment by max-baz** [comment]
And so it's done 🎉 

Playing with it now, looking good @herrmannplatz 👍
