### ISSUE TITLE
No audio or video after incoming or outgoing call connects

### ISSUE THREAD

**Issue by Bomper** [wireapp/wire-webapp#2405]
After I call or receive a call and the other party responds, no audio or video goes through. The other party used both the desktop and the Android app.

## Wire for web version

2018-02-01-10-26-prod

## Browser version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.140 Chrome/64.0.3282.140 Safari/537.36

## Installed browser addons

uBlock origin, which does [Prevent WebRTC from leaking local IP address](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address), but I've disabled uBlock for app.wire.com

![image](https://user-images.githubusercontent.com/34669048/36011364-716de78c-0d0b-11e8-9087-2575d1565760.png)

## Operating system

Ubuntu 16.04

**Comment by Bomper** [comment]
Turns out that disabling the uBlock addon *entirely* (not just for the Wire tab) solved the problem.

Would it be possible for Wire to explicitly tell the user that WebRTC is not available?

**Comment by gregor** [comment]
@Bomper Thanks for your own research. We are continuously looking into improvements for our calling experience. This is on our long wish list but no commitment if and when we will ever implement it. I will go ahead and close this issue as it is more of a feature request than a bug.
