### ISSUE TITLE
Verification should propagate across devices

### ISSUE THREAD

**Issue by deelan** [wireapp/wire-webapp#248]
This applies to all the applications, not just the web app, but since the desktop app just wraps the web app, I'm submitting this here.

Somewhat related to https://github.com/wireapp/wire-webapp/issues/208, but basically I think that when you verify someone else's device, that verification state should be propagated across all your devices.

For example:

I have Wire for Android installed on my phone. I verify my friend's phone fingerprint. When I install the Wire desktop app, my friend's phone fingerprint should be set to verified automatically, rather than having to go into each of my devices/applications and manually toggle it to verified again.

**Comment by mikeger** [comment]
@deelan thanks for your feedback. I would like to indicate a certain issue with your proposal, that I believe is significant.

Currently the fingerprint of the device is inferred from the public keys of the device. This means that if key data is changed on the device (or someone is trying to replace one device with another) it's fingerprint is going to change. The purpose of having a fingerprint of the device is to make it possible to verify that the person you are going to talk or you are talking to is the person you would like to talk and not the man in the middle. Therefore user is supposed to verify the fingerprint in person or using another communication channel by comparing the fingerprints on both devices. This reassures that nothing on the network side can intercept and modify the communication, even Wire service itself.

This is the reason why the device verification is local and not synchronised across devices. If it would be synchronised then the attacker can intercept the internet traffic and make all your devices think that the people you are communicating with are having a verified by you devices.

I am sure there is a way to improve the current verification process, but we should not compromise the security level of the application.

**Comment by deelan** [comment]
Hi @mikeger and thanks for taking the time to respond to my issue.

Firstly, let me just say that I think you guys have done some great work with Wire and I'm a big fan of what I've seen so far!

I definitely don't intend for you to compromise security in any way, so if you feel that verification propagation is not secure, then by all means close up this issue. I was presuming that this kind of propagation could only occur between my verified devices, such that I know that the messages I send between them are 'to me' only and not any possible middle-men, but I do understand the "don't trust the network" situation. 

I guess the reason for posting it was really just an attempt at suggesting some sort of specific way to potentially help with the currently difficult (in terms of usability) verification mechanism. I know that Signal and WhatsApp have gone a different way with verification/extra devices and I appreciate that Wire provides some key functionality that they don't, but it would be nice to get to a point where a user gets the fully secure experience without having to learn anything about fingerprints (beyond just 'scan this QR code or whatever' in person to verify this person is who you think it is) and having to toggle a whole bunch of switches for every user on every added device.

It's a tough problem and I'm sure you guys are thinking about it, so I'm interested to see what you can come up with!

Thanks for all the work you're doing with Wire!

**Comment by mikeger** [comment]
@deelan thanks a lot for the feedback. Yeah, switches are not the most exciting way to do it, definitely :) We'll continue thinking on improving this part of the application. One of proposed ideas are from @IpsmLorem https://github.com/wireapp/wire-ios/issues/232

**Comment by IpsmLorem** [comment]
Synchronisation among devices is a hard problem to solve without compromising security. 
People have often less than 3 devices (desktop, laptop, mobile) and by improving local validation could be enough.

Having #208 to send only to verified devices and https://github.com/wireapp/wire-ios/issues/216 for verification display improvement (and with https://github.com/wireapp/wire-ios/issues/232 as stated),  may help reach that goal.

**Comment by 0ki** [comment]
Seconding mikeger that this is not a good idea.

**Comment by raphaelrobert** [comment]
We have some improvements in mind regarding the verification process. But like @mikeger said, it is difficult to get it right while maintaining high security standards and it requires changes in the architecture. We will keep you posted as we get closer!

**Comment by IpsmLorem** [comment]
Please, never compromise security against any friendlyness.

Secure by design first and then try to improve user experience based on that design :)

**Comment by deelan** [comment]
Though I still feel the user experience is problematic, I agree that this is not the right way to handle it. Verifications always need to be handled out of band.
