### ISSUE TITLE
Unable to login with email from Chromium on Linux

### ISSUE THREAD

**Issue by Bomper** [wireapp/wire-webapp#2487]
## Wire for web version

2018-02-01-10-26-prod

(BTW, the Copyright year in the source code is still 2017)

## Browser version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.140 Chrome/64.0.3282.140 Safari/537.36

## Installed browser addons

uBlock Origin but disabled on app.wire.com

## Operating system

Ubuntu 16.04

## What steps will reproduce the problem?

1. Try to login with email@protonmail.com / password

## What is the actual result?

The login prompt persists. Please see the screencast below.

![login doesn t work](https://user-images.githubusercontent.com/34669048/36289491-0d3bd62e-1275-11e8-954e-7f4a9fa46f7f.gif)

**Comment by gregor** [comment]
@Bomper From the information provided I cannot see why the login fails. Can you please check the console tab. There should be some errors thrown that cause the login process to stop. Usually you should seen an error. Not sure why it isn't happening now. My first guess is the database misbehaving and us failing to handle the situation properly. (Properly as in at least showing you that it failed).

**Comment by Bomper** [comment]
@gregor, thanks for looking into this. In the meantime (about 2 weeks after I first ran into this), the issue was resolved. I did lose all my conversations though because I tried to clear the site data in an attempt to solve the problem (related - #2576, #2497).

The console tab is displayed in the screencast, and there were no errors.

**Comment by gregor** [comment]
You only seem show the network and application tabs. I can't see the console tab of the devloper tools in the screencast.

**Comment by Bomper** [comment]
It's in the bottom right.

**Comment by gregor** [comment]
Our login process has been overhauled. We identified and fixed a few problems. Please report if this issue still happens.
