### ISSUE TITLE
Some content containing underscores doesn't render correctly in webapp.

### ISSUE THREAD

**Issue by daveloyall** [wireapp/wire-webapp#250]
The following doesn't appear correctly in the web app, but it does appear correctly in Android: `<_< >_>`.  In the web app, it looks like this: `<< >>`.

This might be related to #10

Mysteriously, this one does render correctly: `>_>`.

**Comment by herrmannplatz** [comment]
Yes its related and its a pitty since a variety of kaomjies break. We will discuss how to improve the markdown parsing.

**Comment by daveloyall** [comment]
If you provide some specification of the markdown flavor you are using, I can use some appropriate escape mechanism.

**Comment by max-baz** [comment]
I belive this is not a bug. The [markdown syntax](https://daringfireball.net/projects/markdown/syntax#em) defines text wrapped in `_` as _italic_, and so the proper way is either to escape `_` with a backslash ( `<\_< >\_>` ), or wrap the entire thing with back quotes ( \`<\_< >\_>\` ).

I think it's rather an issue in Android that the app does not render markdown.

**Comment by gregor** [comment]
Fixed by #1875. Will be part of the next release to production.
