### ISSUE TITLE
Not able to run wire-webapp locally

### ISSUE THREAD

**Issue by tomicakorac** [wireapp/wire-webapp#26]
Sorry for posting this here, I couldn't find a more appropriate location for this kind of a question.

I'm trying to run wire-webapp locally. I've followed the instructions from README.md, but after running `sudo npm install`, I'm getting a bunch of warnings (which I'm guessing are not critical) and several critical errors:

```
$ sudo npm install
npm WARN deprecated lodash@0.10.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
wire-webapp@ /media/DATA128/work/sites/wire
└── (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path ../has-ansi/cli.js
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall symlink

npm ERR! Error: EPERM: operation not permitted, symlink '../has-ansi/cli.js' -> '/media/DATA128/work/sites/wire/node_modules/bower/node_modules/.bin/has-ansi'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, symlink '../has-ansi/cli.js' -> '/media/DATA128/work/sites/wire/node_modules/bower/node_modules/.bin/has-ansi'
npm ERR!     at Error (native)
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../has-ansi/cli.js',
npm ERR!   dest: '/media/DATA128/work/sites/wire/node_modules/bower/node_modules/.bin/has-ansi',
npm ERR!   parent: 'bower' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/DATA128/work/sites/wire/npm-debug.log
npm ERR! code 1
```

Then, when I run `grunt`, this is the output:

```
$ grunt
>> Local Npm module "grunt-bower-task" not found. Is it installed?

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "coffee:dist" (coffee) task
>> 246 files created.

Running "coffee:dist_init" (coffee) task
>> 1 files created.

Running "less:dist" (less) task
>> FileError: 'ext/css/normalize-css/normalize.css' wasn't found. Tried - app/style/ext/css/normalize-css/normalize.css,app/ext/css/normalize-css/normalize.css,ext/css/normalize-css/normalize.css in app/style/main.less on line 20, column 1:
>> 19 
>> 20 @import (less) "ext/css/normalize-css/normalize.css";
>> 21 @import (less) "ext/css/antiscroll-2/antiscroll-2.css";
Warning: Error compiling app/style/main.less Use --force to continue.

Aborted due to warnings.
```

Finally, when I access `http://localhost:8888`, I get this error message:

```
This site can’t be reached
localhost refused to connect.
```

I'm running Laravel Valet server on Ubuntu 16.04.

**Comment by lipis** [comment]
In general when installing local dependencies with `npm install` you should never use `sudo` and it looks like your issues starts there so let's try to fix that first..

The following links might be quite helpful..
- https://docs.npmjs.com/getting-started/fixing-npm-permissions
- http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

Try fixing the npm permissions and report back with your findings.

**Comment by tomicakorac** [comment]
@lipis thank you very much for the quick reply. Before going with `sudo` I did try to run the command without it, but I remember getting the same result, which by the way required from me to run the same command as Administrator. That's why I tried it again with `sudo`.

Anyway, following your reply, I purged everything from my system (that is, I fully deleted npm-related folders from my `/home/{user}` folder, and also the entire `wire-webapp` folder), followed the steps from your two links, made a fresh installation of `wire-webapp` and ran `npm install`. Unfortunately, I think I got the exact same result. Due to the length of the output, I'm only pasting here links to the paste-bins:

http://laravel.io/bin/yGJQL

As the output suggests, here's the content of my `npm-debug.log`:

http://laravel.io/bin/52Kz2 [*]

I'm not sure whether this matters, but my computer is [Acer Cloudbook](http://www.acer.com/ac/en/US/content/model/NX.SHGAA.001), meaning my processor is Intel Celeron N3050.

[*] EDIT: I just realized that my file's content got cut off. So here's the entire file here:

http://dit.rs/npm-debug.log

**Comment by mythsunwind** [comment]
The error message shows that npm has issues with creating symlinks in a certain directory. The name of the directory lets me guess it is an externally mounted filesystem.

Can you check if it is possible to create a symlink at all in a directory on /media/DATA128/ by using the command `ln`? Maybe it is a filesystem type that does not support or allow this. Also a good idea to check permission and owner of the directory.

Can you also specify which OS you are running?

**Comment by tomicakorac** [comment]
@mythsunwind spot on! Thank you very much for the hint! This is a new computer, and I'm still forgetting important traits here and there. The disk's filesystem was FAT32, that's why it was failing.

I'm going to have to re-format it to NTFS as soon as I get some time. I'm pretty sure it will resolve my problem.

Thank you all again for your quick help. Wire rocks!

**Comment by tomicakorac** [comment]
For anyone getting the same issue, I just learned that `npm install --no-bin-links` will in fact allow you to install packages on a FAT32 file system. I still haven't tested this with wire, but will come back with results when I do.
