### ISSUE TITLE
Screen Sharing button doesn't appear in Chrome

### ISSUE THREAD

**Issue by bradfier** [wireapp/wire-webapp#260]
Using https://app.wire.com or the Chrome Store webapp:

When in a voice call, the Share Screen button isn't present, so I can't start sharing my screen to the other party. Can receive shared screens from my contacts without issue.

_Does not_ work in Chrome Version 53.0.2785.143 (64-bit)
_Does_ work on same machine (Linux) using Firefox 49.

No errors or warnings to report, the button simply isn't present.

**Comment by gregor** [comment]
@bradfier This is not a bug but a limitation of the browser. Chrome does not allow the sharing of your desktop screens unless you install a browser extension via which you can facilitate the screensharing. Firefox uses a different security model and has whitelisted use for screensharing. Technically it would work with Firefox versions below 48 but that is the first version in which we are on the whitelist and do not need to ask users to manually modify that list. If you want to use screen sharing you either have to use Firefox or build a Linux version of desktop app yourself as Linux is not a supported platform for the dekstop app.

**Comment by bradfier** [comment]
Thanks @gregor, are there any plans to support this feature on Chrome (ie adding an extension)? Using Firefox is a perfectly sufficient work around for now.

**Comment by gregor** [comment]
So far we haven't looked into building, releasing and maintaining an extension. But we are continuously listening to feedback and might re-evaluate the need for it in the future. We targeted the feature at our desktop versions based on Electron at the beginning and then noticed that we could also easily enable the feature in Firefox.

**Comment by tad-lispy** [comment]
Hello. Thanks for Wire. It's great and our team is currently trying to migrate to it from Slack + Google Hangouts.

We have ran into this issue too. It's understandable that it may not be feasible for you to make screen sharing work on Chrome in short time, but I think there should be some kind of explanation in the UI as to why sharing does not work. Maybe display the sharing button as disabled and make a tool-tip that explains why. As it is today it seems like a bug, esp. that Chrome is a dominant browser on the market.
