### ISSUE TITLE
Wire thinks my Firefox is a new device

### ISSUE THREAD

**Issue by mikalehmann** [wireapp/wire-webapp#261]
I just logged into the webapp on my Firefox, but Wire thought it was a new browser and gave it a new name with a new key: "Firefox (temporary)". I am also logged out everytime I open Firefox, even though I click on "Remember me". I will file this as a separate bug if they are not related.

**Comment by gregor** [comment]
If you are logged in with a temporary device than the remember me option was not selected when you where logged in this time. When yoe next log in with the option selected, you should be on your old device. You can have a temporary and a permanent device in the same browser. The data is stored in separate databases. Temporary device data gets deleted when you sign out. Permanent device data only gets delete if you explicitly check the option and click continue when you sign out.

**Comment by gregor** [comment]
If you want to be signed in when you open Firefox, make sure that you have bookmarked the blank domain https://app.wire.com and not https://app.wire.com/auth as we will not check whether you have a valid cookie there. You can always sign back into your exisiting permanent device from the auth page as stated above.

**Comment by mikalehmann** [comment]
What's the difference between https://app.wire.com and https://app.wire.com/auth?

**Comment by lipis** [comment]
`/auth/` will always going to prompt you to login, even if you are already logged in. While the other one is going to ask you for credentials only when needed.
