### ISSUE TITLE
Unable to share screen since today

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#2713]
It seems something has updated and neither me nor one of my friends can share screen anymore. Clicking on button has no visible result, and in the logs:

![image](https://user-images.githubusercontent.com/1177900/37089679-b4036710-2201-11e8-9469-2e3d82dca0d1.png)

## Wire for web version

We both use "internal" desktop app on Arch Linux, and I tried switching to "Developer > Internal" and "Developer > Production", but both strangely show the same version of webapp:

Wire for Web Version 2018.03.06.2034

## Operating system

Arch Linux

## What steps will reproduce the problem?

1. Make a call
2. Click on share screen button

## What is the expected result?

Screen sharing starts

## What is the actual result?

No visible indication, error in the logs.

-----

I couldn't test at the moment in more details, if you can't reproduce I will be able to make some more experiments in the evening.

**Comment by gregor** [comment]
Thanks for the report. We broken by #2641 that was part of our latest staging bump. Fixed by #2716.
