### ISSUE TITLE
"Night Mode" toggle

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire-webapp#2771]
It would be very useful and a relatively easy feature to implement a night mode toggle switch. I've been using stylebot locally to debug what a night mode might look like.

The most seamless look I've come up with so far is this:

```
div#conversation, div.conversation-input, .message.hover .time, .message:hover .time, .message.hover .context-menu, .message:hover .context-menu, .message .show-timestamp.time, .conversation-input-bar, .conversation-title-bar, .right-column, .conversation-input-bar-paste-modal, .preferences-page, .preferences-titlebar, .ephemeral-timer {
    background-color: #0c0c0c ;
    color: #cfcfcf;
}


```

This effectively inverts the colors and makes the chat window not so blindingly white. Very important for my late night wire chats.

I've seen a number of people also request this via twitter, so thought I'd file an actual issue and give you the list of elements that I've encountered so far that need to be inverted in order to look right. You could implement this via a setting in the web app that, when toggled, causes the webapp to load and apply nightmode.css with these changes.

**Comment by max-baz** [comment]
Eh, that would be really cool, and there have been Github requests for this before, it's just that they all have been called "dark theme" 😉 

https://github.com/wireapp/wire-webapp/issues/83, https://github.com/wireapp/wire-desktop/issues/299, https://github.com/wireapp/wire/issues/114, https://github.com/wireapp/wire-desktop/issues/709, https://github.com/wireapp/wire-desktop/issues/640, https://github.com/wireapp/wire-desktop/issues/474

**Comment by 0xdade** [comment]
Ah "dark" would have been useful to search before filing. Anyways, hopefully I was able to provide a bit more useful information as far as which classes should be adjusted in the toggle.

**Comment by lipis** [comment]
Thank you for the request.. It's on our list already and we have one open issue for it https://github.com/wireapp/wire-desktop/issues/299

(🍻 Maxim for the links)

**Comment by ffflorian** [comment]
By the way, this was implemented in https://github.com/wireapp/wire-webapp/pull/5415 and will be published soon :tada:

**Comment by Viss** [comment]
hell yes!
