### ISSUE TITLE
bower install error, how to fix it?

### ISSUE THREAD

**Issue by nanedi** [wireapp/wire-webapp#2811]
## Operating system
Ubuntu 16.04 x64

## What steps will reproduce the problem?

1.  bower install error, how to fix it?

**Comment by gregor** [comment]
What's tje browser install error and how is Wire related to it? If you are using the webapp we do not install anything.

**Comment by nanedi** [comment]
`-c bower install`

Do you remember?

`bower ESUDO error`

**Comment by gregor** [comment]
But you do not need bower in order to get the webapp running. Instructions can be found here: https://github.com/wireapp/wire-webapp#installation

**Comment by bennycode** [comment]
Hi @kudouyuzi, did you got it working? If not, then please try with `npm install -g bower`.

**Comment by gregor** [comment]
Closing the issue as we haven't heard back from you.
