### ISSUE TITLE
RTL should not be applied inside code blocks

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#2951]
Wire for Web Version 2018.03.12.1141
Version 3.0.0-undefined (3.0.2816 - Linux)
Arch Linux

-----

A friend of mine decided to share with me in Wire this code snipped:

![wire 2018-03-26 at 20 40 40](https://user-images.githubusercontent.com/1177900/37926096-b98c83bc-3136-11e8-80e1-0c94272ddab6.png)

I received this:

![image](https://user-images.githubusercontent.com/1177900/37926178-f6235256-3136-11e8-932f-be806d9a9c57.png)

--------

## What is the expected result?

RTL should not be applied in code blocks. This is a code snippet after all, I'd rather see badly rendered comments than badly rendered code 🙂

**Comment by lipis** [comment]
Interesting..

The following

```
// שלום עולם
print 'שלום עולם'
```

Does this :)

<img width="208" alt="screen shot 2018-03-26 at 23 22 36" src="https://user-images.githubusercontent.com/125676/37933792-989ea84a-314c-11e8-8896-066e929c8c25.png">

**Comment by lipis** [comment]
#2970 would that be enough to only use it for code blocks?

<img width="617" alt="screen shot 2018-03-27 at 17 28 00" src="https://user-images.githubusercontent.com/125676/37977564-3fe874c2-31e4-11e8-9614-aaabde145057.png">

**Comment by max-baz** [comment]
I'd say yes!

**Comment by lipis** [comment]
Cool website BTW: https://codecombat.com :) Thanks
