### ISSUE TITLE
Running wire-webapp fails using latest node.js 6.7.0

### ISSUE THREAD

**Issue by StevenVanAcker** [wireapp/wire-webapp#308]
I've set up the wire-webapp using the provided instructions, using the official node.js Docker image as a basis

My Dockerfile is this:

```
FROM node:onbuild
RUN npm install -g grunt-cli && npm install
EXPOSE 8888
CMD [ "/usr/local/bin/grunt" ]
```

When I run this container, I get the following output and error:

```
ubuntu@ip-172-30-0-97:~/wire-webapp$ docker run wire-webapp
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "coffee:dist" (coffee) task
>> 255 files created.

Running "coffee:dist_init" (coffee) task
>> 1 files created.

Running "less:dist" (less) task
>> FileError: 'ext/css/normalize-css/normalize.css' wasn't found. Tried - app/style/ext/css/normalize-css/normalize.css,app/ext/css/normalize-css/normalize.css,ext/css/normalize-css/normalize.css in app/style/main.less on line 20, column 1:
>> 19
>> 20 @import (less) "ext/css/normalize-css/normalize.css";
>> 21 @import (less) "ext/css/antiscroll-2/antiscroll-2.css";
Warning: Error compiling app/style/main.less Use --force to continue.

Aborted due to warnings.
ubuntu@ip-172-30-0-97:~/wire-webapp$
```

To replicate this error, create the Dockerfile in the root of the repo, and run: `docker build -t wire-webapp .`
Then, after building, run: `docker run wire-webapp`

The current version of node.js is 6.7.0, which is also what the official Docker image uses.

**Comment by StevenVanAcker** [comment]
After some debugging, it seems the issue is caused because of running `npm install` as root.
If I create a regular user and run `npm install` as the regular user, things seem to work fine.

The updated Dockerfile now looks like:

```
FROM node:onbuild
RUN useradd -ms /bin/bash someone
RUN chown -R someone /usr/src/app
RUN npm install -g grunt-cli
USER someone
RUN npm install
EXPOSE 8888
CMD [ "/usr/local/bin/grunt", "--force"]
```

I hope this helps other people with similar issues.

**Comment by mokiding** [comment]
Why is there no official impelemtation of Docker ?
And is there any user manual on how to setup wire-webapp on brand new digitalocean servers ?
