### ISSUE TITLE
Can't see if old messages have been delivered

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-webapp#309]
Why is the "delivered" tag only shown for the last sent message? How do I know if older messages have been delivered? I don't see an option to see that other than opening the app on my phone...

**Comment by helenakos** [comment]
"Delivered" is shown to the last successfully delivered message, meaning all the messages before the one showing "Delivered" were delivered as well.

**Comment by someoneEsle** [comment]
Uhmm... So, let's say that I send the messages: A, B, C, D, ... Z. Say that all the messages up to "D" get delivered, then "E" gets lost, and then F, G, ..., Z will be delivered correctly.
What do you display in this scenario? Do you show "Delivered" only up to "D", even if "F" was delivered correctly?

**Comment by helenakos** [comment]
Thanks for your request, we don't have any iterations planned here at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
