### ISSUE TITLE
Wire webapp does not work on Seamonkey.

### ISSUE THREAD

**Issue by mzs114** [wireapp/wire-webapp#310]
I get a message which shows "Unsupported Browser". Both Firefox and Seamonkey use the same gecko engine under the hood. (about:config)
Please don't limit Wire to just a handful of browsers, by allowing Wire to run on different browsers you increase its accessibility.

**Comment by bennycode** [comment]
Hey @mzs114, can you please tell us the user agent of your Seamonkey browser? 

You can get if from: http://whatsmyuseragent.com/

**Comment by mzs114** [comment]
@bennyn 

`Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0 SeaMonkey/2.40`

**Comment by gregor** [comment]
@mzs114 We currently support Firefox from the last LTS release onwards, which is currently version 45. Your SeaMonkey relies on a Firefox 43 which is not supported. Please upgrade if there is a newer SeaMonkey version available. https://github.com/wireapp/wire-webapp/blob/dev/aws/config.py#L32

**Comment by mzs114** [comment]
Thanks @gregor, that makes sense _if_ the Wire web app uses something which older version don't support. 
Also I see that Chrome must be at lest 51, that means [midori](http://midori-browser.org/) based on webkit won't work either :(

**Comment by gregor** [comment]
We use many state of the art features of ES6 like Promises or ever evolving APIs like webRTC. Many versions have bugs that we need to work around to keep calling working. We do not have the resources to do cross-browser testing with all these versions with every release. We require almost up to date browsers to take this source of error out of the matrix.
