### ISSUE TITLE
Feature Request: Let the user rename devices

### ISSUE THREAD

**Issue by ffflorian** [wireapp/wire-webapp#313]
As a user I'd love to be able to rename my devices so I can keep track of which devices I don't use anymore. The fingerprint solution is great for security - but for a quick overview (local?) naming would be cool.

**Comment by helenakos** [comment]
Thanks @ffflorian, good request :)

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
