### ISSUE TITLE
full screen button (feature request)

### ISSUE THREAD

**Issue by oscardssmith** [wireapp/wire-webapp#3152]
Hi peoples,
I just started using Wire and really like it, but the one thing I've found that would really be great to add would be a way to make a video call go to full screen rather than by manually full screening the window.
I'm not entirely sure if this should be filed under the web-app or here so I've guessed.
Thanks

**Comment by gregor** [comment]
Thanks for your feature request. This is certainly an interesting idea but nothing we have in mind for the immediate feature. With the nature of this being a feature request I am going ahead with closing this ticket as we want to keep the issues section for bug.
