### ISSUE TITLE
Wire's incidental killing in Russia's Telegram war

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#3235]
As a side effect of Russia's vs. Telegram war Wire is no longer available in Russia because it is hosted on Amazon AWS. I remember that Wire claimed sort of independence and neutrality due to Swiss registration... why use US based hosting?

**Comment by raphaelrobert** [comment]
Wire servers are located in Ireland and Germany, not in the US.

With the AWS block in Russia, Wire seems at least partially affected indeed.
