### ISSUE TITLE
device id

### ISSUE THREAD

**Issue by lololsiyuan** [wireapp/wire-webapp#3289]
##I want to know how the device id is generated? But no entry point could be found...

**Comment by gregor** [comment]
The device ID is generated by the backend and returned to us on a `POST /clients/` request. It is best to direct this question to https://github.com/wireapp/wire-server as the related code is to be found somewhere there in the haskell implementation. I am sure that @tiago-loureiro or @jschaul can help out.

**Comment by jschaul** [comment]
If by `device id` you mean what we internally call a `ClientId` (which in combination with your UserId uniquely identifies your wire client), the `ClientId` [is derived from the last Prekey](https://github.com/wireapp/wire-server/blob/develop/services/brig/src/Brig/API/Client.hs#L71-L73). A wire client (e.g. the wire-webapp) generates prekeys (among other things) locally when initializing its state. See the [proteus](https://github.com/wireapp/proteus/) implementation of the "axolotl" protocol for details.

**Comment by gregor** [comment]
I suppose this answers your question and am thus moving ahead with closing the issue.
