### ISSUE TITLE
Feature request: mention/highlight by username on group chats

### ISSUE THREAD

**Issue by Phitherek** [wireapp/wire-webapp#3313]
Hello,

I have a request for a feature that seems so obvious that I'm stunned it's missing from Wire. While in a group chat, it would be very useful to be able to mention/highlight a particular user or users by username, much as @-mentions here on GitHub. The mention could send a direct notification to that particular user and become highlighted. It would also be useful if you could choose from the list of users in the group, similarly as the emoji picker is done. This is the feature that I would also like to see in the desktop app (which is based on the web version so I guess it's one and the same) and to be passed on to the mobile app.

Regards,
Phitherek_

**Comment by gregor** [comment]
@Phitherek Thanks for your post. This is definitely on our wishlist as well. We just haven't gotten around to implement it. While this is no commitment to the feature or a specific timeline I can assure you that we are missing it too in our daily workflows.

Thank you very much again for your feature request. As stated in our issue template, we intend to keep this purely as a bug tracker. While we appreciated your interest in Wire and your post will make an impact when we evaluate priorities, I will go ahead and close this issue.

**Comment by urzds** [comment]
We would love to see this, too.
