### ISSUE TITLE
GIFV Embed Support

### ISSUE THREAD

**Issue by livejamie** [wireapp/wire-webapp#332]
Would be nice if gifv files were loaded like gifs are

https://i.imgur.com/sxc9H2J.gifv

**Comment by notNSANE** [comment]
Not sure if webms are supported, but those would be awesome too.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
