### ISSUE TITLE
My avatar being the sidebar background is weird

### ISSUE THREAD

**Issue by livejamie** [wireapp/wire-webapp#333]
Have the same feedback from all my friends and family. It would be fun to be able to choose from something generic, or set a color or set my own photo (separate from my avatar) as the background of the side of the app.

Having it be a blown up version of my own face is really weird.

**Comment by herrmannplatz** [comment]
Yes, good point. Thats already under discussion within our team.

**Comment by livejamie** [comment]
Is this being considered? Google taking away SMS from Hangouts is causing my family to get more serious about switching.

**Comment by helenakos** [comment]
@livejamie A different version of conversation list UI is coming out in a matter of weeks. Closing this as I'm pretty sure the outcome is what you requested (not having a blown up version of your own face).
