### ISSUE TITLE
Multi-language layouts broken because of AltGr+ bindings

### ISSUE THREAD

**Issue by tkgalk** [wireapp/wire-webapp#334]
Same issue as in #94.

"AltGr+n" = "ń".
"AltGr+s" = "ś".
"AltGr+Shift+n" = "Ń".
"AltGr+Shift+s" = "Ś".

Alt+Ctrl combinations on Windows are treated as AltGr and tend to go in conflict with non-english layouts.

Proposal: move away from Ctrl+Alt keybindings to something like Ctrl+Shift or something completly else because Polish won't be the only affected.

**Comment by gregor** [comment]
Closing in favor of #94
