### ISSUE TITLE
Would you consider relicensing your web client to AGPL?

### ISSUE THREAD

**Issue by strypey** [wireapp/wire-webapp#3396]
Wire is a wonderful piece of software, thanks so much for developing it. I note that you are releasing Wire under a GPLv3, which is great, it's a solid copyleft license. However, I wonder if you have considered putting the server-side components of your projects under [AGPLv3](https://www.gnu.org/licenses/agpl.html)? It's very similar to the GPL, but has a few extra clauses that address the special conditions created by software that can be accessed by users as a service over the internet, rather than downloaded and installed on their own computer. The main benefit for you is that it asserts that running a user-facing service using your code counts as "distribution", triggering the copyleft clauses, and obliging them to share a copy of the source code of your app (and any modifications they've made) with their users, and with you.

**Comment by raphaelrobert** [comment]
This has always been the case:

https://github.com/wireapp/wire-server/blob/develop/LICENSE

**Comment by strypey** [comment]
The back-end is AGPL yes, but the web app also runs on a server, and is currently GPL:
https://github.com/wireapp/wire-webapp/blob/dev/LICENSE

**Comment by raphaelrobert** [comment]
I see, but I think this is a misunderstanding. The web app doesn't run on the server, it is downloaded by the browser and is executed there. In that sense it is just like any other client software.

**Comment by strypey** [comment]
On 2018-06-05 09:23, raphaelrobert wrote:
> I see, but I think this is a misunderstanding. The web app doesn't run on the server, it is downloaded by the browser and is executed there.

I understand that.

> In that sense it is just like any other client software.

I see what you mean, but wouldn't this mean having separate terms for
"web app" and "desktop app" or "mobile app" would be pointless, since
they're all client software? The reason these terms exist is that from a
user POV, there is a big difference between a) choosing to download and
install an app, with the freedom to keep or remove it, and b) having
that download done for me by a browser, without me necessarily even
knowing, and with the software effectively removed as soon as I close
the browser.

Anyway, the point here is whether GPL or AGPL is the most appropriate
license for protecting the software freedoms related to your web app.  

Let's say I took your web app code, modified it, and used it as part of
a proprietary platform, I wouldn't be violating your GPL license. 
Neither you, nor my users, would have access to source code of my
modified version, as the copyleft provisions of the GPL requires. But
the AGPL was written because in-browser execution does not count as
"distribution" of your software, so it doesn't trigger the copyleft
requirements of GPL.

The AGPL explicitly includes running the software as a service (or a
Service-as-a-Software-Substitute) in its definition of "distribution. It
also requires me to inform my users in the UI that part of the code of
my platform was derived from Wire, and provide a link to the source code
of the version I'm running. This could be a link back to your repo, if
I'm running your code verbatim, or to my own if I've modified it.

Again, IANAL, I'm an activist, and this is not legal advice. Just
sharing my understanding of how AGPL works different from GPL. I presume
you will consult someone from a group like the SFLC or SFC, who have
people experienced in this area of law who are qualified to give legal
advice.

Finally, thanks again for releasing Wire as free code software. Keep up
the good work!

**Comment by raphaelrobert** [comment]
> Let's say I took your web app code, modified it, and used it as part of
a proprietary platform, I wouldn't be violating your GPL license.
Neither you, nor my users, would have access to source code of my
modified version, as the copyleft provisions of the GPL requires. But
the AGPL was written because in-browser execution does not count as
"distribution" of your software, so it doesn't trigger the copyleft
requirements of GPL.

So your concern is that GPL is the wrong license for web apps. Could you provide some more context/evidence for why you think this is the case?

The FSF explicitly recommends releasing Javascript libraries under GPLv3:
https://www.gnu.org/software/librejs/free-your-javascript.html (section 2.3)

**Comment by strypey** [comment]
On 2018-06-07 18:18, raphaelrobert wrote:
> So your concern is that GPL is the wrong license for web apps.

Yes. Well ... just not the *ideal* license, for the reasons given.

> Could you provide some more context/evidence for why you think this is the case?

> The FSF explicitly recommends releasing Javascript libraries under GPLv3: criphttps://www.gnu.org/software/librejs/free-your-javast.html (section 2.3)

The author(s) of this page do, true. Maybe you could email the contact
address on the Free Your Javascript page and ask for clarification? I'm
guessing they assume that the Javascript in question is *libraries*,
rather than complete packages of software, in which case some of the
considerations here might apply:
https://www.gnu.org/licenses/why-not-lgpl.html

Here's the FSF release announcement about the AGPL and what its for, in
their words:
https://www.fsf.org/news/agplv3-pr

Here's a general human-readable summary of the implications of the AGPL:
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)

Ultimately, of course, it's your decision to make, in consultation with
whoever gives you professional legal advice. Thanks for the friendly
engagement, and if there are any other questions on AGPL I might be able
to answer, I'm happy to to help as best I can.

**Comment by raphaelrobert** [comment]
Revisiting and questioning the status quo is a good and necessary thing. At this point however it still feels like a theory, because the links you posted don't clearly corroborate it.
We'll stick with the [official FSF recommendation](https://www.gnu.org/software/librejs/free-your-javascript.html) (to use GPLv3 for JS) for now on our side.
I feel this is a question that should be raised with a different audience, so that people that have a deeper legal understanding can chime in. After all, this would affect all websites with JS code published under GPL. Feel free to pursue that, we don't have the capacity to do this right now (but would try to support you where it makes sense).
Thanks for your time and effort on this!

**Comment by strypey** [comment]
On 2018-06-11 11:10, raphaelrobert wrote:
> We'll stick with the [official FSF recommendation](https://www.gnu.org/software/librejs/free-your-javascript.html) (to use GPLv3 for JS) for now on our side.

Fair enough. So just to be crystal clear, you consider that page a
canonical FSF recommendation. You would revisit a change of license for
your web app is that page was changed to say something like:
* we recommend putting all JS libraries under GPL or LGPL
* we recommend putting all complete JS web clients under AGPL

Is this correct?

> Thanks for your time and effort on this!

De nada :) It's been good to be challenged to check my workings, and I
now have a clear path forward (talk to folks at FSF). Thanks for your
constructive engagement.
