### ISSUE TITLE
Solid drawer background

### ISSUE THREAD

**Issue by Madis0** [wireapp/wire-webapp#3456]
I would like to have an option to use a solid (black, white or customizable) background for the contacts drawer. 
Having a resized, cropped and blurred profile image is not the best background in my opinion, especially because you can't really change it without changing it for everyone else too.

Current workaround: add `app.wire.com##.background:nth-of-type(2) > .background-image` in a content blocker to remove the background image. 

[Cross-posted from wire/wireapp](https://github.com/wireapp/wire/issues/188)

**Comment by gregor** [comment]
Thank you very much for your feedback. We have collected a number of different ideas regarding the conversation list and it's appearance. We have no short term plans on changing the current look and feel though as we intend to focus on other parts of the product at this point in time. I will go ahead and close this issues in its nature as a feature request. Be assured that your feedback has been heard and will be evaluated when we revisit this part of the app.
