### ISSUE TITLE
Text formating support is incomplete/wrong

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#355]
I tried common text formatting tricks and this is what I get (not entirely sure if this is a way it supposed to be):

`*bold*` gives me italic
`_italic_` works as expected
`~strikethrough~` does nothing

Tested in app.wire.com in Firefox (Linux)

**Comment by helenakos** [comment]
@timur-davletshin Thanks Timur, we need to improve the text formatting. No current committed date yet.

**Comment by maximbaz** [comment]
Besides the 3 obvious formatting options mentioned above it is very often requested to have monospace formatting (for code snippets and special marking), `single-line` and 

```
multi-
line
```

**Comment by max-baz** [comment]
@timur-davletshin the app is respecting [the markdown syntax](https://daringfireball.net/projects/markdown/syntax#em), which I think is actually pretty cool, as it is standard and it allows sharing markdown documents _just by copy-pasting the text_ in the conversations, and voilà, it is nicely formatted. 

See the list of formatting commands:

```
_italic_
*italic*

__bold__
**bold**

`single-line code`
\```
multi-
line-
code
\```
```

Honestly I would think twice before killing the support for markdown syntax in favor of something else.

**Comment by bennycode** [comment]
We support the following Markdown syntax on [Wire for Web](https://app.wire.com/):

```bash
**bold**
_italic_
`code`
```

There is also support for code blocks and syntax highlighting. 

Further highlighting features are not yet planned.
