### ISSUE TITLE
Timed messages → Hover tips translation

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#356]
`"Temporare Nachricht"` in English interface while mouse pointer over the timed message icon.

**Comment by gregor** [comment]
@timur-davletshin Thank you for your report. We already noticed and fixed this in https://github.com/wireapp/wire-webapp/commit/c07f118158af121dbbc7065c29914d372e89fe3b a couple of hours ago. Will be part of the next release.

**Comment by gregor** [comment]
We have fast tracked the fix for this. This is now live and available for you on the next page refresh.
