### ISSUE TITLE
Delete message pop-up

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#359]
Delete message pop-up menu probably has got wrong z-index value and should overlap any other interface element. Under certain circumstances it may not be accessible.

See screenshot for details:

![untitled](https://cloud.githubusercontent.com/assets/23050090/19695802/a222cd54-9af5-11e6-9ae9-41245c2f1bee.png)

**Comment by gregor** [comment]
@timur-davletshin Thanks for the report. We are aware of the issue and have been tracking it internally already.

**Comment by gregor** [comment]
We have since replaced our context menu implementation. This should no longer happen with the new approach.
