### ISSUE TITLE
New messages notification in browser

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#360]
I'm sorry, I'm a bit confused with all those new Notification/Push/Workers APIs, so I will explain from user stand point.

Can I receive notification in browser about new messages while tab with Wire is closed (notifications are enabled)?

This is the way I receive news from couple sites on my desktop/phone. I'd like to have the same with web-version of Wire.

**Comment by gregor** [comment]
Yes, this is technically possible but not currently in our implementation scope.

**Comment by ghost** [comment]
As far as I understand this will require server side changer, isn't it?

**Comment by gregor** [comment]
Exactly, we would have to set up a push service that we can use from a service worker.

**Comment by helenakos** [comment]
Closing issue as we don't have it planned for the near future. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
