### ISSUE TITLE
not work on domain

### ISSUE THREAD

**Issue by mjheidari** [wireapp/wire-webapp#3607]
Hi, i want run it on a domain not local,but when use yarn start this error shown:
`[HPM] Error occurred while trying to proxy request  from xx.xx:8080 to http://x.x.x.x:8888 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

**Comment by bennycode** [comment]
Hi @mjheidari, please refer to our updated guidelines: https://github.com/wireapp/wire-webapp#how-to-build-the-open-source-client
