### ISSUE TITLE
Menu to download shared images

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#367]
I'd like to have menu to download shared images. Copying and pasting blob:address is a bit annoying.

**Comment by gregor** [comment]
If you click on an image to see it in full screen mode, the option is available on right click. I fully agree that we should add easier ways to download images though.

**Comment by gregor** [comment]
We have made a number of improvements in this area including adding the download option to the message menu and adding an obvious download button on the detail view. Thereby closing this. Please come back with more feedback if you feel that something is still missing.
