### ISSUE TITLE
platform check failed on `TypeError: window.platform.os.family is null`

### ISSUE THREAD

**Issue by kworr** [wireapp/wire-webapp#3685]
Hello.

Looks like my browser is failing checks at `app/script/util/Environment.js`:

```
window.platform.ua:
"Mozilla/5.0 (X11; DragonFly x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
window.platform.os.family:
null
```

Hence check on the line 77 in Environment.js breaks due to `windows.platform.os.family` being null.

I don't know whether it's fine to treat my platform as Linux, but I think it should work fine anyway.

**Comment by gregor** [comment]
Thanks for the report. We use https://github.com/bestiejs/platform.js/ for our browser detection. I filed an issue with them and will add a safeguard on our end.
