### ISSUE TITLE
I am looking into Wire as a replacement chat tool

### ISSUE THREAD

**Issue by noci2012** [wireapp/wire-webapp#386]
Why doesn't it work on Chromium..., chrome is the google privacy crippled variant of chromium.
So from a privacy standpoint chromium should be part of the family.

A 2nd issue, how is the sustainability of this application arranged for?
There must be something/someone that pays the co-Location bill.

**Comment by gregor** [comment]
It should work on Chromium. Can you post your user agent string so we can check why we apprently block your Chromium build?

**Comment by david-wire** [comment]
@noci2012 Wire is VC backed by Iconical and will monetize with premium features and platform offering in the future.

**Comment by noci2012** [comment]
I have Chromium with the following extentions active:
uMatrix, https everywhere, Ghostery, Cookiemanager.

Even if those are disabled the redirect persists to wire.com/unsupported
I am not aware of anything that changes the UserAgent string.
Ghostery has no issues with your pages 
umatrix has innocraftcloud excluded for javascripting. (it only supplies piwik.js).

Chromium Version 41.0.2232.0  (Blue Icon).

**Comment by lipis** [comment]
can you paste here the result of https://app.wire.com/test/agent/

**Comment by noci2012** [comment]
I will when i am in the office. (windows system).

On this chromium it does work, test output :
It seems to work on a linux version with same extensions...

```
{
  "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36", 
  "bot": false, 
  "browser": {
    "name": "Chrome", 
    "version": "53.0.2785.92"
  }, 
  "is": {
    "android": false, 
    "android_tablet": false, 
    "bingbot": false, 
    "blackberry": false, 
    "blackberry_tablet": false, 
    "chrome": true, 
    "crawler": false, 
    "desktop": true, 
    "electron": false, 
    "firefox": false, 
    "googlebot": false, 
    "ie": false, 
    "ios": false, 
    "ipad": false, 
    "iphone": false, 
    "linux": true, 
    "mobile": false, 
    "opera": false, 
    "osx": false, 
    "phone": false, 
    "safari": false, 
    "tablet": false, 
    "windows": false, 
    "windows_phone": false, 
    "wrapper": false, 
    "yahoobot": false
  }, 
  "os": {
    "name": "Linux"
  }, 
  "platform": {
    "name": "Linux", 
    "version": null
  }
}
```

**Comment by noci2012** [comment]
Windows chromium without recognition

```
{
  "agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2232.0 Safari/537.36", 
  "bot": false, 
  "browser": {
    "name": "Chrome", 
    "version": "41.0.2232.0"
  }, 
  "is": {
    "android": false, 
    "android_tablet": false, 
    "bingbot": false, 
    "blackberry": false, 
    "blackberry_tablet": false, 
    "chrome": true, 
    "crawler": false, 
    "desktop": true, 
    "electron": false, 
    "firefox": false, 
    "googlebot": false, 
    "ie": false, 
    "ios": false, 
    "ipad": false, 
    "iphone": false, 
    "linux": false, 
    "mobile": false, 
    "opera": false, 
    "osx": false, 
    "phone": false, 
    "safari": false, 
    "tablet": false, 
    "windows": true, 
    "windows_phone": false, 
    "wrapper": false, 
    "yahoobot": false
  }, 
  "os": {
    "name": "Windows", 
    "version": "7"
  }, 
  "platform": {
    "name": "Windows", 
    "version": "7"
  }
}
```

**Comment by lipis** [comment]
So I found your issue.. the Chrome version is 41 and we support >= 51

https://github.com/wireapp/wire-webapp/blob/dev/aws/config.py#L30-L35

**Comment by noci2012** [comment]
Ok, maybe the minimal version should be mentioned in the requirements? 
Portable Apps isn't there yet afaict.

**Comment by lipis** [comment]
We are updating them quite often and it would be hard to maintain and keep this information in sync.. Also the officially supported browsers are doing well with their autoupdate mechanisms, so in reality everything is seamless and the end user usually doesn't really care about the actual version.

What do you mean by portable apps?

**Comment by noci2012** [comment]
It's not part of native portable apps..., ok that explains why it is behind.. not auto update.
I use a portable apps version of chromium, as i as a regular user cannot install software but can unzip packages. Appearantly this one isn't picked up by the portable apps environment for updating.
Only on work environments i use windows systems as a regular user if needed.

**Comment by noci2012** [comment]
thanks for the enlightenment.

**Comment by lipis** [comment]
Awesome! So it looks like it's time to update your browsers.. mostly for security reasons.. and secondly for Wire :D

**Comment by noci2012** [comment]
If versions are a requirement, the failure page could tell which versions apply and which test the browser fails (This can be automated..., in a generic version checking routine used both in web frontend as well as webapp frontend).
