### ISSUE TITLE
[Feature request] Show when people are typing

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-webapp#387]
It surprises me that no one has suggested this feature on github yet, so I'll do it. It would be extremely useful if the web app/desktop apps showed when people are typing. I often find myself sending messages on my computer and then checking my phone to see if the other person is typing a reply ^^
Thanks!

**Comment by gregor** [comment]
This is definitely on our wish list as we do have this feature on the mobile clients and lately expanded it to work in groups too. We just haven't gotten around to implementing it yet.

**Comment by helenakos** [comment]
@someoneEsle We still have it on the list, no committed date yet. Closing for now but not dismissing the needed feature.
