### ISSUE TITLE
Network.

### ISSUE THREAD

**Issue by noci2012** [wireapp/wire-webapp#392]
This should not be in wire-webapp, but in wire general, but there is no way to enter issues there.

You announce yourself as a Swiss based company using a Luxembourgh Finance backing company with german developpers. 
The again the Server addresses are with google (1e100.net) and Amazon both are AFAICT  US based companies that don't a a lot of trouble harvesting Personal info from people.
The mail comes from a US based server.

Then there is no Safe Harbour protection since more than a year, while  the announced replacement doesn't really solve the issues that caused the Safe Harbour treaty to be void in the first place.

I expected a EU based solution.

**Comment by raphaelrobert** [comment]
Hi @noci2012,

We only use datacenters that are located in the EU. For our service we use AWS servers in western Europe. Emails are also sent out from there and that can be seen in the "Received:" field. 
Our website is currently hosted on GAE, but we are in the process of changing that (however it is only a static website that is not part of the product). 
In both cases you can verify that on a good internet connection ping times are too low for a server to be several thousands of kilometres away from Europe. 
Finally datacenters operated in the EU are bound by European data protection laws.
I hope this clarifies the situation a bit!

**Comment by lipis** [comment]
Just to add one more thing.. our website is hosted on GAE, but even that is not in US.. it is hosted in EU data centers.

**Comment by noci2012** [comment]
Hm.. The country of origin code in my spam checker classiyfies it as US origin, might be because of Amazon as the controlling owner of the address spaces.
And Amazon as a US based company and is required to answer to the US laws..., so there is a vacuum there, it just depends on who pulls strings more effectively.
Without any real consecuences for Amazon if doing it wrong on the EU side.  in this respect i have no optimistic view i can agree to that.
