### ISSUE TITLE
Observed: Password reset fails

### ISSUE THREAD

**Issue by noci2012** [wireapp/wire-webapp#393]
The reset mail has a lifetime of 10 minutes, yet it may take far more then 20 minutes before it gets delivered.
I tried to reset the password three times everytime the link is declared void AFTER the new password is entered, btw, the new password is not checked for typo's using a 2nd field to enter it.

**Comment by noci2012** [comment]
Part of this might be that there is no allowance for spam filter solutions. 
I tried a few resets because the sources varies a greylisting using server somwhere in between you sender & my receiver can cause mail the be held for between 30-45 minutes. (That is if after retries are done according to RFC's, if retires occur before the established minima the new countdown for the allowance timer will start again at somewhere around the 30-45 minutes. 
So a retry within 5 minutes will guarantee a fail and will setup the alloweance window 5 minutes later.

**Comment by noci2012** [comment]
created a new account for remedy.

**Comment by gregor** [comment]
@noci2012 Thank you for the report. We are tracking the issue internally. It will be addressed by the backend time at some point. Thereby I am closing this issue on the webapp also for housekeeping reasons.
