### ISSUE TITLE
Timed messages immediately obfuscated

### ISSUE THREAD

**Issue by Tuj3Bz90dV** [wireapp/wire-webapp#4055]
On the latest update, Wire for Web Version 2018.07.16.1405, received messages with a timer of 24 hours are immediately obfuscated, instead of 24 hours after being received. 

A cursory review of recent commits suggests 20d18967e517d57c03b159228c84cc3e77451c1c or 431ca57a68d1fe6012be3e2702c253358e215d4a may be the problem, but I could not confirm this.

**Comment by atomrc** [comment]
Hi,
Thanks for the report.

The commits you point to are actually a feature that we introduced in the latest release indeed. 

This feature obfuscate the timed messages received when the app is not focused.
This prevents users from having the app not focus (but still visible on screen) and still be able to read the message while the timer haven't started yet.

The obfuscation should go away and the timer starts when the app is focused again.
Can you confirm this behavior or does the obfuscation stays when you focus the app?

**Comment by gregor** [comment]
The change was done in order to address concerns raised in https://github.com/wireapp/wire-desktop/issues/928

**Comment by Tuj3Bz90dV** [comment]
Yes, that is correct: messages continue obfuscated when the application is focused, and even when receiving them with the application in focus does not appear to make a difference.

I tried both Chrome and wire-desktop clients on Linux, to the same effect. If it matters, there is a mobile device associated in which everything works correctly.

**Comment by atomrc** [comment]
Which version of Chrome and `wire-desktop` are you using?
(you can find the desktop version in "help > about > Wire" in the menu bar.

**Comment by Tuj3Bz90dV** [comment]
`Version 3.2.2840`
`Wire for Web Version 2018.07.16.1405`

Chrome was also the latest one `67.0.3396.99`.

**Comment by Tuj3Bz90dV** [comment]
After a few more experiments in Chrome, it appears some messages do end up deobfuscated after a while, but it seems unpredictable when or how that happens.

**Comment by atomrc** [comment]
Ok, you are pretty up to date.

If I understand correctly, so far no timed messages you have received have been showing up in a plain text mode, is that right? 
Do you see any error in your browser's console?

**Comment by Tuj3Bz90dV** [comment]
Alright, I think I found some sort of logic to what's happening. If you send enough messages such that the timed messages are scrolled away out of the screen, then when you scroll up they will be deobfuscated correctly. Otherwise, they remained obfuscated for an arbitrary amount of time.

On Chrome there are no console errors to report. Yes, this is plaintext mode, but it also happens with images. With images, though, if you click to enlarge they show up correctly.

**Comment by atomrc** [comment]
Ok, I don't really see where the problem comes from right now.
It could come from 2 places: 
- either the `focus` event is not correctly triggered on your browser/desktop app ;
- or somehow, there is an element overlaying the obfuscated message.

Let's try this.
Could you run in your console:

```
window.addEventListener('focus', console.log);
```

and check that it logs something when you focusout/re-focus the app.

Other test, can you, in the inspector, inspect one of the messages that won't deobfuscate, and run:

```  
(() => {
    const box = $0.getBoundingClientRect();
    const elementAtPoint = document.elementFromPoint(box.left, box.top);
    return elementAtPoint && $0 !== elementAtPoint && !$0.contains(elementAtPoint);
}());

```

It should return `false`.

**Comment by Tuj3Bz90dV** [comment]
The focus event definitely happens as I would expect it to.

I don't know where I am supposed to run that last snippet, though. I can inspect the timed message, I can even force-focus it using Chrome, but nothing happens, and I don't see any place to run Javascript on it specifically (?).

Whatever this is, it appears to be Chrome-specific. Messages appear fine on Firefox.

EDIT: The console doesn't seem to like the lambda, but running it as follows works:

```
> const box = $0.getBoundingClientRect();
undefined
> const elementAtPoint = document.elementFromPoint(box.left, box.top);
undefined
> elementAtPoint && $0 !== elementAtPoint && !$0.contains(elementAtPoint);
null
> elementAtPoint
null
```

Nevermind the above, I accidentally ran it when the message was not visible on screen. It does return false otherwise:

```
> box = $0.getBoundingClientRect();
DOMRect {x: 375.98956298828125, y: 386.3541564941406, width: 632.0181884765625, height: 23.333332061767578, top: 386.3541564941406, …}
> elementAtPoint = document.elementFromPoint(box.left, box.top);
<div class=​"text ephemeral-message-obfuscated" data-bind=​"html:​ asset.render()​, css:​ {'text-graphite':​ $parent.is_editing, 'text-large':​ z.util.EmojiUtil.includesOnlyEmojies(asset.text)​, 'text-graphite':​ message.status()​ === z.message.StatusType.SENDING, 'ephemeral-message-obfuscated':​ message.isObfuscated()​}​" dir=​"auto">​sdfadgdfgdfh​</div>​
> elementAtPoint && $0 !== elementAtPoint && !$0.contains(elementAtPoint)
false
```

**Comment by atomrc** [comment]
Thanks for your investigations.
For that part, everything looks normal. This behavior is really strange.

Can we try this. 

- In the devtools, go to `Sources`.
- In there, press `ctrl-p` then start typing `MessageListViewModel`
- add a breakpoint on line `537` and `538` (`if (messageEntity.conversation_id...` and `this.conversation_repository.checkMessageTimer...`)
- send a timed message from another device
- focus back the web view
- check that both breakpoint are reached.

Thanks a lot.

**Comment by Tuj3Bz90dV** [comment]
Breakpoints are not triggered unless I force them to, by e.g., resizing the browser window such that the timed message is hidden then visible again, or by the aforementioned scrolling away.

Simply unfocusing and focusing the window appears to have no effect. The callback itself, `getInViewportCallback`, doesn't seem to be reached.

**Comment by atomrc** [comment]
Hey @Tuj3Bz90dV 

So, we were able to reproduce the bug locally and fix it. 
If you are curious about it, it was due to floating numbers (more on this on the PR https://github.com/wireapp/wire-webapp/pull/4104/files).
It will probably be released early next week.

Thanks again for reporting the bug and for your effort into debugging it with me.
We really appreciated your help.
