### ISSUE TITLE
Emojis button in web app and desktop app

### ISSUE THREAD

**Issue by dietmarw** [wireapp/wire-webapp#408]
This still seems to be missing.

**Comment by herrmannplatz** [comment]
Indeed. 😤 Having a dedicated button is one of the next items on our list.

**Comment by ffflorian** [comment]
I implemented an Emoji picker which you can test (still in beta though): https://github.com/wireapp/wire-webapp/tree/emoji-picker

Note: this is a personal sideproject and not offically supported.

**Comment by helenakos** [comment]
@ffflorian No longer a side project but officially supported! https://medium.com/wire-news/wire-for-web-2017-04-19-a72948238161 

Emoji autocomplete is great, we also want to have an emoji button but don't have it planned at the moment, so I will close this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by OmeGak** [comment]
Is this feature no longer available? After upgrading to 3.1.2822, emoji autocomplete is not working anymore.
