### ISSUE TITLE
"This is the first time you have signed in on this computer"...but it's not.

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#4117]
Recently the webapp has given me this message and advised me my history wouldn't be present as a result. But I have used it continuously on this laptop. I have no reinstalled the OS or browser or intentionally deleted the device. Is this a bug or is there a common error I could have committed that removed the device?

**Comment by gregor** [comment]
Can you check your devices section of the preferences  on your affected device? There is an "activated on" date for your current device. Is this the date you saw the message on? If so, did you possibly accidentally delete the wrong device remotely?

**Comment by ghost** [comment]
I checked and I didn't delete this device. I had to delete old devices as the max had been reached so I deleted them from tablets I no longer have. I then encountered the warning and started a new conversation. Just today the same thing happened and I was again told it was the first time I had used the device even though I used it yesterday as well. Are there some logs I can send you?

**Comment by ghost** [comment]
I didn't intentionally close this. Must have hit the wrong button. Or maybe my laptop is haunted. Is it possible re the Wire webapp that resintalling or altering Fireffox history/cookies settings has affected this?

**Comment by gregor** [comment]
Definitely. If you delete your local browser storage we have no way to know which cryptographic identity your "device" previously had. You will always create a new device this way. This is outlined in our FAQs on the support site.

**Comment by ghost** [comment]
Can you tell me where in the FAQs? I searched the terms "browser" "cookies" and "history", and manually looked through all support topics and must have missed it. I never had this issue on another laptop even with Firefox locked down to cookies and no history saved. I don't know what setting specifically is the problem.

Also when looking at the device list how can I determine which is which from a single list (ie not logging in to each device to see which is "current"? I can't recall creation dates for all and don't know how to see which of the multiple "Firefox" entiries is associated with which device.
