### ISSUE TITLE
Foreign avatars in conversation

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#412]
Clicking on avatar in conversation gives first avatar I clicked before.

E.g. I click Otto's avatar then click mine and instead of mine I get Otto's.

![untitled](https://cloud.githubusercontent.com/assets/23050090/19981299/d23e08b0-a21a-11e6-9d83-a6e3ce17d9ad.png)

**Comment by herrmannplatz** [comment]
Thanks. Made already a fix.

**Comment by herrmannplatz** [comment]
Should be fixed. Feel free to reopen if not.

**Comment by ghost** [comment]
Yep, I noticed that already in browser notification (good thing to inform about changes, BTW)! Thanks a lot!
