### ISSUE TITLE
Feature request: Support IRC "/me" command (just like Skype does)

### ISSUE THREAD

**Issue by dietmarw** [wireapp/wire-webapp#419]
This is something that I like to see also in the wire apps.

**Comment by helenakos** [comment]
Thanks for your request. We don't have plans to support this at the moment, therefore will close this issue. We have used such commands for bots, if you're interested in bot development and would like to contribute have a look around https://github.com/wireapp?utf8=%E2%9C%93&q=bot&type=&language=
