### ISSUE TITLE
Still getting "this is the first time you have used this device" errors

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#4250]
____________________________

**Comment by kristin-wire** [comment]
Hi Hap124,

This is Kristin from Support reaching out. We've seen a few cases like this in support before...it sounds like your browser is configured to delete local data once closed, and so it is removing anything related to Wire and thus creating a new device when you log in. Can you check your browser settings? Also - does it happen in other browsers?

**Comment by ghost** [comment]
____________________________
