### ISSUE TITLE
TypeError: Ha(...).family is null on login attempt

### ISSUE THREAD

**Issue by kworr** [wireapp/wire-webapp#4313]
Hello.

Looks like last fix of osFamily detection wasn't the last one. This time I can see the login screen but I can't get further. I receive `TypeError: Ha(...).family is null` error trying to submit username/password. This happens in Runtime.js:61

    const getOsFamily = () => getOs().family.toLowerCase();

What I have:
```
»platform
  {…}
    description: "Firefox 60.0"
    ​layout: "Gecko"
  ​  manufacturer: null
    ​name: "Firefox"
  ​  os: {…}
      ​​architecture: null
  ​​    family: null
    ​​  toString: toString()
    ​​​    length: 0
        ​​​name: "toString"
      ​​​  prototype: Object { … }
        ​​​__proto__: function ()
  ​​    version: null
    ​​  __proto__: Object { … }
  ​  parse: function e()
    ​prerelease: null
  ​  product: null
    ​toString: function toString()
  ​  ua: "Mozilla/5.0 (X11; DragonFly x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
    ​version: "60.0"
  ​  __proto__: Object { … }
```

This time it looks like jQuery isn't populating all fields, probably?… I'm zero at Javascript.

Thanks in advance.

**Comment by gregor** [comment]
The libary we use to parse your user agent chokes on Dragonfly. We have opened an issue on the library https://github.com/bestiejs/platform.js/issues/156. Looks like we need to add a safeguard also in the place where we detect the device type when creating an new device linked to your account until the library has fixed this.

**Comment by gregor** [comment]
@kworr A fix mitigating the situation has been deployed to production a few days agin. Can you confirm it is working for you now?

**Comment by kworr** [comment]
Still the same error.

**Comment by gregor** [comment]
@Yserz Can you please take a look?

**Comment by gregor** [comment]
We deployed a new version of the webapp with additional safeguard in place for platform detection. Does this work for you now?

**Comment by kworr** [comment]
Yep, works perfectly now!
