### ISSUE TITLE
Launching a web application with a local server

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-webapp#4413]
## Browser version

Google Chrome 68.0.3440.106

## Installed browser addons

No

## Operating system

Linux admin 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What steps will reproduce the problem?

1.  Change the server address to local.
2.  User authorization on the page http://IP_ADRRES:8888/login/#login
3.  Then, ask for an email address to confirm. I enter the address and press send.

## What is the expected result?

The expected result is to get into the application and start working there.

## What is the actual result?
In fact, the message does not come to the post office. In the browser console produces the following error:

`WebSocketService.js:96 WebSocket connection to 'wss://IP_ADRRES:8080/await?access_token=rRcoazGqun7ZHbZ_x6Qtc251XPL1DIe5O7WQvFRlB7dMTNkF_IW79xVk12MA42G5Pi3XNlXNDzssK91jlEWNBA==.v=1.k=1.d=1535312218.t=a.l=.u=63033fef-aab3-4f49-be2f-13de2e4aa7de.c=11214639721820334433' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by gregor** [comment]
Thanks for bringing this up. We redesigned our login flow a while ago and apparently did not update the readme. This will be fixed with https://github.com/wireapp/wire-webapp/pull/4468. The goal `yarn start` should actually already open the page mentioned in this PR.
