### ISSUE TITLE
How to start a web application

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-webapp#4414]
When starting from the outside port 8888 is available and there it is only possible to authorize by phone number. Port 8088 from the outside is not available, but the application itself is running on it at the address http://IP_ADDDRES:8088/ aut and here it is possible to register authorization by phone or e-mail, etc.

help me please

**Comment by bennycode** [comment]
@sd166 Can you login with your Wire account on http://localhost:8080/page/auth.html?env=prod#login? If login doesn't work on the first try (showing "Unexpected Error"), then just try again.

Please report back if that works.

**Comment by sd166** [comment]
This is if you try to authorize by phone at the address http://IP_ADDR:8888/login/#login
When I try to log in, I get an error in the console:

POST http://IP_ADDR:8080/login/send 403 (Forbidden)

**Comment by sd166** [comment]
If you go to the address http://IP_addr:8080/page/auth.html, it displays the following error in the browser console:

![wire_webaap](https://user-images.githubusercontent.com/10991740/45079248-b2084880-b0fa-11e8-9903-cd37cce5a7a8.jpg)

When entering the user registration:

![wireapppppp](https://user-images.githubusercontent.com/10991740/45079369-11feef00-b0fb-11e8-9252-979e1f8b00cc.jpg)

After entering the name, email, password. Errors, or what does not output and falls on the verification page where you need to enter a 6-digit code. In the server console:

```
[nginz] 87.239.27.145 - - [05/Sep/2018:11:02:07 +0300] "OPTIONS /activate/send HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 6 0.000 - - - - aacff3613f4e46926eab44b7ac1258a5
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#18
[nginz] 87.239.27.145 - - [05/Sep/2018:11:02:07 +0300] "POST /activate/send HTTP/1.1" 200 31 "http://IP_ADDR:8080/page/auth.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 6 0.092 0.092 - - - d703ec19a6b112cc4966eb42f15e20e7
```
The code does not come. Where is that unconfigured?



When you try to log in to the server console:

```
[brig] D, code=403, label=invalid-credentials, request=e86b568be82777b657049052d9455426, "Missing cookie and token"
[nginz] 87.239.27.145 - - [05/Sep/2018:11:06:41 +0300] "POST /access/logout HTTP/1.1" 403 105 "http://IP_ADDR:8080/page/auth.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 10 0.004 0.004 - - - e86b568be82777b657049052d9455426
[nginz] 87.239.27.145 - - [05/Sep/2018:11:06:42 +0300] "OPTIONS /login?persist=true HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 8 0.000 - - - - a50311e86f6f906fe0f74f891d5c9535
[nginz] 87.239.27.145 - - [05/Sep/2018:11:06:42 +0300] "POST /login?persist=true HTTP/1.1" 403 96 "http://IP_ADDR:8080/page/auth.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 10 0.048 0.048 - - - ae658b4b30a861611005831dccf88eda
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#21
[brig] D, code=403, label=pending-activation, request=ae658b4b30a861611005831dccf88eda, "Account pending activation."
gin?persist=true HTTP/1.1" 403 96 "http://IP_ADDR:8080/page/auth.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" - 10 0.048 0.048 - - - ae658b4b30a861611005831dccf88eda
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#21
[brig] D, code=403, label=pending-activation, request=ae658b4b30a861611005831dccf88eda, "Account pending activation."
```


When I try to sign in to the browser console:


![2342342344](https://user-images.githubusercontent.com/10991740/45079911-55a62880-b0fc-11e8-803f-e4895addc011.jpg)

**Comment by sd166** [comment]
When I try to log in, I get this error:
![222222221](https://user-images.githubusercontent.com/10991740/45674476-e259d900-bb35-11e8-83bb-2c4b1002160d.jpg)

If you go to swagger-ui there is no /self/consent

**Comment by bennycode** [comment]
We have updated our instructions. You have setup a virtual host on your machine: https://github.com/wireapp/wire-webapp#how-to-build-the-open-source-client
