### ISSUE TITLE
Avatar image is broken

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#444]
Looks like avatar image became broken in desktop version since yesterday. All of them just disappeared (mine, others), while mobile works fine. No browser/addons updates so far. Tried to upload new — no result.

**Comment by ghost** [comment]
Seems like time to time it works. Server side performance issues?

**Comment by herrmannplatz** [comment]
Does it happen for all images or only specific?

**Comment by ghost** [comment]
To all images. That is why I assumed that it could be performance problem. Generally speaking image performance is not particularly good. Sometimes it takes second for images to appear.

**Comment by bennycode** [comment]
Should be fixed by now we did a lot of improvements regarding this. :)
