### ISSUE TITLE
Feature request: Show timestamps for calls

### ISSUE THREAD

**Issue by shvchk** [wireapp/wire-webapp#447]
Now timestamps are shown for messages and pings, but not calls (see attached image). It would be nice to have them, maybe like `start — end`, e.g. `14:39 — 14:56`.

![wire-no-call-timestamp](https://cloud.githubusercontent.com/assets/872945/20259855/8f1ce304-aa70-11e6-9074-6851f5606333.png)

**Comment by gregor** [comment]
We implemented this change with PR #657 which will be part of our next release. Thereby closing this.
