### ISSUE TITLE
Feature request → Unique keys

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#449]
I'd like to know if it is possible to see:

1. Unique keys (fingerprints) on every message (in pop-up menu for example).
2. Give names to my fingerprints so other part can easily distinguish message origin. It is not convenient to have, let's say, two fingerprints named "DESKTOP".

Thanks a lot for Wire!

**Comment by herrmannplatz** [comment]
Will bring this up for discussion. Thank you for participating! :)

**Comment by herrmannplatz** [comment]
#313

**Comment by helenakos** [comment]
Thanks for your request, we don't have this particular change planned, but some brains at Wire are already thinking of a solution for easier fingerprint comparison. Will have to close this one. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
