### ISSUE TITLE
Feature request → URL preview in desktop client

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#451]
Make URL previews in dekstop client just like in messages from mobile, not just links.

**Comment by herrmannplatz** [comment]
Atm all clients rely on open graph data. Mobile clients will show at least the title of the page if no data is present. We will align with other clients once we have time for it.

**Comment by herrmannplatz** [comment]
Tried to address this in #525

**Comment by helenakos** [comment]
Thanks for your request, as @herrmannplatz mentioned, we rely on open graph data. We don't have further actions planned for this at the moment. Revisiting in the future. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
