### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#454]
Webapp kicked me off and I cannot log in. Tried to reset it couple times but still unable to log in with new password — "Problems with the connection. Please try again."

**Comment by ghost** [comment]
It was my fault with sessionstore file in Firefox profile. Removing it helped.

**Comment by lipis** [comment]
Then we can just close this one I guess :)

**Comment by ghost** [comment]
Yep, I'm sorry for hasty report :)
