### ISSUE TITLE
[Suggestion] Add voice message functionality (like in the android and ios apps)

### ISSUE THREAD

**Issue by roberdorfer** [wireapp/wire-webapp#455]
Currently it's not possible to send voice messages, would be great if support for it could be added.

**Comment by bennycode** [comment]
Hi @rbieb, thanks for sharing your thoughts with us!

We are collecting feature requests here: https://github.com/wireapp/wire/issues
If you don't mind we would be pleased if you can raise your issue there again.

Best from Berlin,

Benny
