### ISSUE TITLE
Do not redirect the google bot to the unsupported page

### ISSUE THREAD

**Issue by lipis** [wireapp/wire-webapp#4556]
<img width="765" alt="screen shot 2018-09-11 at 19 03 18" src="https://user-images.githubusercontent.com/125676/45372564-02e5d880-b5f6-11e8-9463-2f7700980b13.png">

Example bot request: https://app.wire.com/?agent=Mozilla/5.0%20(Linux;%20Android%206.0.1;%20Nexus%205X%20Build/MMB29P)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/41.0.2272.96%20Mobile%20Safari/537.36%20(compatible;%20Googlebot/2.1;%20+http://www.google.com/bot.html)

https://websiteadvantage.com.au/Request-HTTP-Header-Info (Although not sure how up to date is that)

**Comment by bennycode** [comment]
@lipis Let's track this in Jira.
