### ISSUE TITLE
SHow online & offline users next to their name

### ISSUE THREAD

**Issue by Nuruddinjr** [wireapp/wire-webapp#46]
I think it is very inconvenient not see whether user is online or no next to their names or somewhere else .
`feature request`

**Comment by bennycode** [comment]
Hi @Nuruddinjr, we decided against an online status because of privacy reasons. You can read more about this topic here: https://github.com/wireapp/wire-webapp/issues/8 

But thanks that you have raised the issue.

Best,
Benny
