### ISSUE TITLE
Allow running the webapp under docker using custom URLs

### ISSUE THREAD

**Issue by tiago-loureiro** [wireapp/wire-webapp#4647]
[This branch](https://github.com/wireapp/wire-webapp/compare/docker) introduces a dockerfile which allows us to build and run the webapp inside docker, exposing it over port 5000. Furthermore, it allows it to be started with specific URLs for both the REST and the Websocket by modifying the _staging_ URLs in the generated scripts. You can also run this locally 
by running `docker run -p 5000:5000 quay.io/repository/wire/webapp:alpha` and opening your browser on http://127.0.0.1:5000.

However, it is not production ready so I will list here the different TODOs that need to be addressed before it is in a state where we can merge and use it "everywhere".

- [ ] On premise installations do not (currently) support setting consent. This needs to be either optional on the webapp _OR_ properly supported by the backend
- [ ] Setting backend URLs should be done in a cleaner way, i.e., during the build process or potentially through a config file read during startup. This is also relevant for other links on the webapp that point to wire.com such as "forgot password", etc.
- [ ] CSP headers also need to be relaxed/configured; currently, running this on something not under `wire.com`, `zinfra.io` or locally would not be possible. Assets will also likely not be served by Amazon.
- [ ] Allow setting the application port ([here?](https://github.com/wireapp/wire-webapp/blob/dev/aws/application.py#L210)) to something else other than `5000`.
- [ ] The resulting image takes ~500 MB; this is unnecessary and the executable should the contents of the resulting `ebs.zip` (which contains ~10M) and a base image with python and its [requirements](https://github.com/wireapp/wire-webapp/blob/dev/aws/requirements.txt)
- [ ] ...

**Comment by ayavorskiy** [comment]
Hi, thank you for your effort related to making Wire-Webapp more accessible. 
I was trying to run the docker image and test it using your stage server and got following error 

http://0.0.0.0:5000/auth/ -> http://0.0.0.0:5000/auth/#createaccount after filling required fields I got 
 "Unexpected error"
Failed to send email code NetworkError: "Cannot do "post" request to "https://staging-nginz-https.zinfra.io/activate/send"."
<img width="1392" alt="screen shot 2018-10-08 at 14 04 33" src="https://user-images.githubusercontent.com/6198345/46605910-caa5bd00-cb03-11e8-90a8-b79756bdaaa7.png">
Do you allow new registrations on your stage server https://staging-nginz-https.zinfra.io?

**Comment by ayavorskiy** [comment]
Sorry for disturbing regard my question above, error related to CORS in Google Console clearly show the root cause of issue. I successfully deployed wire-webapp and wire-server with SSL certs and properly working calls and video. The only real issue that remains is some part (forgot password feature; accounts and teams) of source code which is missing https://github.com/wireapp/wire-webapp/issues/5197

**Comment by bennycode** [comment]
@ayavorskiy Since you have been able to deploy our webapp and server, can we close this ticket and continue the conversation in https://github.com/wireapp/wire-webapp/issues/5197?

**Comment by ayavorskiy** [comment]
@bennyn this ticket was originally created by your team member @tiago-loureiro as checklist but if only my comments hold it to be closed, it should be closed :)

**Comment by bennycode** [comment]
Ok! The topic got solved with https://github.com/wireapp/wire-webapp/pull/4946.
