### ISSUE TITLE
video/audio on-off option 

### ISSUE THREAD

**Issue by narimangharib** [wireapp/wire-webapp#48]
Would be nice if users can disable or enable audio/video on their browser or phone.

When video/audio calling are off, you will no longer receive notifications when people try to call you on your browser.

**Comment by bennycode** [comment]
So you want to have a more specific menu to set notifications based on the platform (iOS/Android/web)?

**Comment by narimangharib** [comment]
Sorry for late reply.

Currently, many people are trying to make a video/audio call when I open my wire account. It would be great if we have a feature like that one on Facebook for Wire. Please see the attached image.

Thanks
![screen shot 2016-09-05 at 5 37 15 pm](https://cloud.githubusercontent.com/assets/3672889/18253769/71d15a0e-738f-11e6-9f65-0fef7632cdc2.png)
