### ISSUE TITLE
{{config.CURRENT_VERSION_ID}} appears on a public IP

### ISSUE THREAD

**Issue by GiovanniMounir** [wireapp/wire-webapp#4827]
## Wire for web version

2018-10-02-08-03-prod

## Browser version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

## Installed browser addons

None.

## What steps will reproduce the problem?

1.  Clone the repository.
2.  Run `yarn start`.
3.  Go to IP:8888 and inspect the source code.
4.  appears on the 3rd line instead of the actual version.

## What is the expected result?

The version appears on the 3rd line of the web page source code. Example: `2018-10-02-08-03-prod`

## What is the actual result?

The following text appears on the 3rd line of the web page source code: `<!-- {{config.CURRENT_VERSION_ID}} --> `

I'm using the webapp with a self-hosted wire-server; I had to change Backend.js and auth.js to point to the public IP address - not sure if this is the correct procedure. I'm not using `localhost`. Any advice will be greatly appreciated.

Thanks!

**Comment by bennycode** [comment]
Hi @GiovanniMounir, thanks for reporting the issue. We will address it with the following PR: https://github.com/wireapp/wire-webapp/pull/4946 👍
