### ISSUE TITLE
Backslashes entered by users are handled like escapes

### ISSUE THREAD

**Issue by alekratz** [wireapp/wire-webapp#494]
Here's an example of my input to the webapp:
![](http://i.imgur.com/4uRtllz.png)

and how it shows up in the chat window:
![](http://i.imgur.com/5LjiRnk.png)

I am using Chromium 54.0.2840.100 (64-bit) on Linux.

**Comment by ghost** [comment]
\| is shown like |

**Comment by ffflorian** [comment]
@timur-davletshin: You mean `\|` is shown like `|`, right?

**Comment by ghost** [comment]
Yes, exactly

**Comment by ffflorian** [comment]
This is fixed by now.
