### ISSUE TITLE
Allow image paste from clipboard

### ISSUE THREAD

**Issue by PatelUtkarsh** [wireapp/wire-webapp#5]
In OS X you can copy image in clipboard without creating an actual file, and { command + v } allows it to paste that image as we paste normal text.

Current OSX app and Web app does not allow pasting of an image.

**Comment by bennycode** [comment]
Definitely a desirable feature! [Clipboard API and events](https://w3c.github.io/clipboard-apis/) currently have 'Working Draft' status but [browser support looks good](http://caniuse.com/#feat=clipboard). We will investigate...

**Comment by helenakos** [comment]
Hey @PatelUtkarsh, thanks for the feedback! Noted this one down for future planning :)
