### ISSUE TITLE
request: support tor browser

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#5051]
tor browser doesnt get past the loading page

**Comment by bennycode** [comment]
Hi @kb8000, thanks for making us aware of this. Can you please provide the user agent of your browser? For now we don't have the resources to test the compatibility of Tor browser but we might consider it for the future.

**Comment by ghost** [comment]
@bennyn @ffflorian tor browser version 8.0.3

error message:

You are in private mode
Wire needs access to local storage to display your messages. Local storage is not available in private mode.

**Comment by mythsunwind** [comment]
The reason for not supporting Tor **browser** are described here: https://github.com/wireapp/wire-webapp/issues/1882#issuecomment-346298159

You can also find instructions how to use wire on Tor through the socks proxy implementation in the above issue.
