### ISSUE TITLE
No link preview in Wire Web client

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#506]
When sending a link from Wire web client, no link preview is generated. Links sent via macOS or iOS client get a link preview (also on Wire web client).

**Comment by lipis** [comment]
As this is done client side.. this impossible to achieve via JS without an extension.

**Comment by ghost** [comment]
Hm, Telegram’s web client can generate link previews.

On 26 November 2016 at 01:04:52, Lipis (notifications@github.com) wrote:

As this is done client side.. this impossible to achieve via JS without an
extension.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wireapp/wire-webapp/issues/506#issuecomment-263034189>,
or mute the thread
