### ISSUE TITLE
Feature request → Change phone number

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#5067]
Browser: Firefox 63
OS: Debian Stable

Feature request: add ability to change phone number from web-interface just like in mobile app.

**Comment by bennycode** [comment]
@timur-davletshin As written in our [issue template](https://raw.githubusercontent.com/wireapp/wire-webapp/2018-11-15-13-14/.github/ISSUE_TEMPLATE.md), please raise feature requests [here](https://github.com/wireapp/wire/issues).
