### ISSUE TITLE
Persitant storage only for non temporary devices

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#510]
Since there is two type of user devices (temporary or not), it would be interesting to have a different online storage policy for media/messages.
When someone has only non temporary devices (e.g. one iOS and one "desktop"), there is no need to store their delivered medias/messages online. They must be localy read from the device.

**Comment by 0ki** [comment]
Could you give an example of a "temporary device"?

**Comment by IpsmLorem** [comment]
Just open a session on a web browser. It will be classed as a temporary one. If I understand correctly, each user can have only one temporary device associated with their account.

**Comment by gregor** [comment]
If you log in from a web browser without enabling the remember me checkbox, you will register a temporary client. @IpsmLorem is correct that a user account is limited to a single temporary device. The user data will be deleted from the local database by signing out. If we do not persist it, even a page refresh would result in history loss.

**Comment by IpsmLorem** [comment]
When talking about persistence I was refering local (indexDB ?) storage vs online storage.
Trying to clear things up:

A user having:
* a long term iOS device: datas are stored on iOS FS
* a long term "Desktop" (ATOM) device: datas are stored on OS FS (indexed DB ?)
* a long term web app device: datas are stored on indexed DB
* a temporary device: datas are stored (for how long ?)  into Wire cloud

**Comment by gregor** [comment]
We can only decrypt each message once. We do not store unencrypted messages on our servers. Anything that is not persisted locally in the IndexedDB is lost after a page refresh. Or currently already when switching conversations.

**Comment by IpsmLorem** [comment]
What about media ?

**Comment by herrmannplatz** [comment]
All the assets are encrypted with a symmetric key and stored on our backend. This key is then send as a part of a regular encrypted message. see https://github.com/wireapp/generic-message-proto/blob/master/proto/messages.proto#L189

**Comment by IpsmLorem** [comment]
When only devices with local sotrage capabilities are at stake, why keeping assets online ?

**Comment by EgbertW** [comment]
What is the storage policy on this? How long is the asset available for download?

I'm assuming the reason it's stored online, encrypted with a symmetric key, is that without this approach, the asset would need to be encrypted and transferred once for each recipient, generating a lot of data usage in group conversations. Is that true?

**Comment by gregor** [comment]
Thanks everyone for the interesting discussion. We will consider the feedback for discussion regarding future changes to the product. At this time we do not plan to change the behavior of permanent and temporary devices.
