### ISSUE TITLE
Feature request: Wire.me hyperlink

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#519]
Hyperlink for web pages which would start a chat with a specific user or group in Wire messenger.

**Comment by helenakos** [comment]
@herrpoerner Thanks for the request, it's something we have planned for the future :)

**Comment by ffflorian** [comment]
@helenakos

If it's about the domain you could add the feature e.g. in `https://wire.com/u/<username>` , with the same functionality which starts a bot chat.

**Comment by helenakos** [comment]
We are not dismissing this, however I am closing only due to clean up purposes.
