### ISSUE TITLE
Missing PASSWORD_RESET source code. Source code for account and teams.

### ISSUE THREAD

**Issue by ayavorskiy** [wireapp/wire-webapp#5197]
Dear Wire developers,
Can you please share source code for https://account.wire.com and https://teams.wire.com which both are set in 
https://github.com/wireapp/wire-webapp/blob/dev/app/script/config.js#L98 and https://github.com/wireapp/wire-webapp/blob/dev/app/script/config.js#L103 

In current source codes it's seems to be missing PASSWORD_RESET: '/forgot/', feature 

Thank you for your efforts and sharing your project to open-source.

**Comment by raphaelrobert** [comment]
Hi @ayavorskiy,

This is correct, the source code for that is not published as of yet. We are currently working on refactoring the code behind `account.wire.com` and are considering open sourcing it once that is process is finished.
`teams.wire.com` is our team management and billing solution. It is not something that is needed for Wire Pro on-premise installations as such and therefore we will not open source this part.

**Comment by ayavorskiy** [comment]
Hi @raphaelrobert ,
Any updates on this issue or possible date that we could rely on?

**Comment by raphaelrobert** [comment]
Hi @ayavorskiy, this is still work-in-progress at the moment.

**Comment by Yserz** [comment]
@ayavorskiy wire-account is open-source now *yay* https://github.com/wireapp/wire-account/
