### ISSUE TITLE
scrollbar styling

### ISSUE THREAD

**Issue by kinghat** [wireapp/wire-webapp#5218]
## Wire for web version
Version 2018-11-15

## Browser version
chrome 70 stable

## Operating system
linux

can you make it so the scrollbar can be easily styled by users?
![image](https://user-images.githubusercontent.com/16073360/49175940-57544680-f30f-11e8-8499-b43398118e44.png)
implementing my own proper dark theme and would like to use my own as below:
![image](https://user-images.githubusercontent.com/16073360/49176277-1577d000-f310-11e8-8815-572446a3d652.png)

**Comment by bennycode** [comment]
> can you make it so the scrollbar can be easily styled by users?

We are working on a concept to have themes but it might take some time until it gets into our production code but we are definitely on it! 😎

**Comment by bennycode** [comment]
Since January 18, 2019 we offically support a dark theme: https://wire.com/en/blog/dark-mode/
