### ISSUE TITLE
Missing video overlay when accepting call

### ISSUE THREAD

**Issue by fungs** [wireapp/wire-webapp#5221]
## Wire for web version

Latest online.

## Browser version

Electron via Rambox (based on Chromium)

## Operating system

Linux x86_64

## What steps will reproduce the problem?

Accept a video call.

## What is the expected result?

Video overlay should be shown.

## What is the actual result?

Call is established but no video shown, not sign that the call is actually ongoing. However, everything appears normal for the other side. Video overlay is completely missing, showing chat only. Yesterday, I shortly got a video overlay with black buttons and black video screen for a few seconds which then disappeared.

**Comment by mythsunwind** [comment]
Rambox is based on Electron 2 which includes an old version of Chrome 61. We recently released our wire-desktop application which is based on amuch newer version of Electron (3) and Chrome (66). I can remember that we skipped version 2 of Electron also because of some calling issues.

Can you check if you have the same issue on wire-desktop or with a more recent Chrome on app.wire.com?

**Comment by fungs** [comment]
I will test again to see, if the problem persists. It only recently happened, so the code changes cannot be too old. I would say, it is important to not only support latest chrome, but to make sure it runs in all newer browsers. Otherwise, you are cutting off all those users who, for good reasons, cannot or don't want to upgrade to latest chrome. There are a lot of platforms and OS where you are stuck with a certain browser which is either based on chrome or firefox engines.

**Comment by mythsunwind** [comment]
Even though I agree with you that it is important to not only support latest browser versions, Google makes it very hard for us to do so. Not only is WebRTC (which is used by video and audio calling) changing sometimes with every release and we have to build in workarounds for it, but also Google does not officially provide a way to get older versions of their browser. And: The Chrome updater mechanism does not allow to block updates.

For Firefox we always test against and support Firefox LTS, which is their long term support version. For Chrome we always support the version we have in our latest wire-desktop client and the current released Chrome version.

**Comment by fungs** [comment]
Sad situation, I'm not a web dev. Now it's only chrome and firefox left on the market.

What about using [Selenium](https://www.seleniumhq.org/) or similar. For instance, https://www.browserstack.com/list-of-browsers-and-platforms/ has all the chrome versions available for testing.

**Comment by bennycode** [comment]
Video calls are properly working in Chrome 83 and Firefox 78. I just tested it.
