### ISSUE TITLE
Not working in Edge 18

### ISSUE THREAD

**Issue by felixse** [wireapp/wire-webapp#5263]
## Wire for web version

app.wire.com

## Browser version

Edge 18 (User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763)

## Operating system

Windows 10 1809

## What steps will reproduce the problem?

1.  Open https://app.wire.com in Edge

## What is the expected result?

WebApp should be usable

## What is the actual result?

Redirect to https://wire.com/de/unsupported/

**Comment by bennycode** [comment]
I can confirm this bug. Thanks for letting us know. Edge 17 also doesn't work. We will get this fixed!

Edge 17 user agent:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by thenktor** [comment]
See also #4142

**Comment by bennycode** [comment]
@thenktor Are you using a Windows Insider build? 

@felixse Can you please provide the user agent ([navigator.userAgent](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/userAgent)) for your MS Edge 18 installation?

**Comment by thenktor** [comment]
No, I'm using Windows 10 Professional Version 1803 with EdgeHTML 17.17134.

**Comment by bennycode** [comment]
> No, I'm using Windows 10 Professional Version 1803 with EdgeHTML 17.17134.

That's interesting because I am using Windows 10 with Microsoft EdgeHTML 17.17134 too and it works just fine. What's your user agent? 

Mine is:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by felixse** [comment]
User agent is: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763`

But seems to be fixed now, thank you 👍
