### ISSUE TITLE
HTML tags filtering

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#530]
It looks like HTML tag are directly allowed in conversations which I consider a bug. What if I try <script>?

Screenshot with some statistics pasted from HTML file:

![untitled](https://cloud.githubusercontent.com/assets/23050090/20901123/87119016-bb4a-11e6-9e82-e87dd39622fe.png)

**Comment by bennycode** [comment]
@timur-davletshin Can you please provide the input that you sent to get the result which is shown in your screenshot?

**Comment by bennycode** [comment]
Closed due to inactivity.
