### ISSUE TITLE
URL Parsing

### ISSUE THREAD

**Issue by azlux** [wireapp/wire-webapp#5380]
Wire version: Version 3.0.2828
Wire for web version: Wire Web Version 2017.11.10.1041
Operating system:  Windows 10
Which antivirus software do you have installed: default, windows defender

What steps will reproduce the problem?
1.send the the link : https://a_l_-_h.png

What is the expected result?
A clickable link

What is the actual result?
A bad not well formed link

Thank
Az

**Comment by AndyLnd** [comment]
This is a known limitation of the link-parsing library we use (https://github.com/markdown-it/linkify-it/issues/79). There is unfortunately no workaround that works for us. Until we switch to another markdown renderer or this gets fixed in the library, we are stuck with this behaviour.
