### ISSUE TITLE
Contact are loosing their avatars

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#5381]
Wire version: 3.0.2828
Wire for web version: 2018.01.24.1811
Operating system: Windows 10 x64

What steps will reproduce the problem?
1. Justwatch my contact list

What is the expected result?
Everyone having an avatar, each one should have one displayed

What is the actual result?
Some contact doesn't have an avatar displayed, but thay have on Wire iOS.

![cap](https://user-images.githubusercontent.com/1250795/35527665-cde7c1e6-052b-11e8-953e-1c4d0a2e939f.png)

**Comment by bennycode** [comment]
We have experienced this bug with very old profile pictures. On our backend we introduced a new concept for handling avatars so it should not happen anymore if users uploaded a new avatar within the last year.
