### ISSUE TITLE
GIFs received from iOS devices don't loop

### ISSUE THREAD

**Issue by jack-cole** [wireapp/wire-webapp#5383]
Wire Version: **2.15.2750** 
OS: **Windows 10 Pro 64bit** 
Do you have an antivirus software installed: **Avira Free Antivirus** 
What steps will reproduce the problem? 
1. **iOS user sends gif using the built in GIF function via giphy.com** 
2. **View the message in Wire for Windows** 
3. **Scrolling up several pages, then scrolling down will start the gif again and then stop it on the last frame**

What is the expected result? 
**The gif should loop.** 

What happens instead? 
**The gif stops on the last frame after it plays entirely.** 

Please provide any additional information below. Attach a screenshot if
possible.

**If I save the gif to the desktop, it loops fine. Gifs received from Android and Windows devices loop fine.** **This issue also happens on my Android phone.**

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire/issues/347 https://github.com/wireapp/wire-webapp/issues/5571

**Comment by bennycode** [comment]
We haven't received the misbehaving file, so I am closing this issue.
