### ISSUE TITLE
Color profile inside picture are not used : wrong colors

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#5384]
Wire version: 3.0.2828
Wire for web version: 2017.11.10.1041
Operating system: Windows x64
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Send a picture with a color  profile in it
2. The pictures is displayed in the conversation

What is the expected result?
- color profile should be used to display the correct color according to the color profile of the monitor 

What is the actual result?
- color are wrong if the monitor (OS) color profile is different than the one inside the picture sent

**Comment by bennycode** [comment]
Thanks for this detailed report. As a workaround you can transfer images as files to make sure they don't get compressed.

**Example:**

![image](https://user-images.githubusercontent.com/469989/89906376-97df1b00-dbeb-11ea-83a7-9b8673b05618.png)
