### ISSUE TITLE
GIF is looping forever

### ISSUE THREAD

**Issue by MatthiasBergen** [wireapp/wire-webapp#5385]
Hi there! 

I am using desktop app version 3.4.2885 on Windows 10  PRO Version 1803.

When sending a GIF in one of my chats this is looping forever :-(

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire/issues/347 https://github.com/wireapp/wire-webapp/issues/5571

**Comment by bennycode** [comment]
We don't plan to change the looping behaviour of GIFs in the near future.
