### ISSUE TITLE
Message timers in group expire earlier than expected for sender

### ISSUE THREAD

**Issue by Wurzelkoch** [wireapp/wire-webapp#5387]
Wire Version 3.0.2816
Wire für Web Version 2018.10.23.1205
Operating system: Debian 9
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Write message to group chat
2.  wait some minutes
3.  read group chat

What is the expected result?
My own messages should appear.

What is the actual result?
In one of my group chats, several people with different devices (Linux Desktop, Android) have the same problem, that after some time we cannot read our own text messages. They simply dissapear as if they had never been there. Any other person sees them as usual. Only one group chat seems to be affected. With 48 members, it is the biggest group chat I'm involved in, Timed messages are set to 1 week (which is the case in some non-affected chats as well)

Please provide any additional information below. Attach a screenshot if possible.

**Comment by bennycode** [comment]
We fixed issues with our message timers.
