### ISSUE TITLE
No redirect after password change on different device

### ISSUE THREAD

**Issue by eknoes** [wireapp/wire-webapp#5593]
*Follow up to #5592*
## Wire for web version
Current Web version: 2019-01-08-13-20

## Browser version
Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

## Installed browser addons
None, also happens with addons disabled

## Operating system
Arch Linux, Kernel 4.20.0-arch1-1-ARCH

## What steps will reproduce the problem?
1. Change your password
2. Open https://app.wire.com on another device

## What is the expected result?
Show the login interface

## What is the actual result?
Endless loading bar with near to zero progress, nothing happens.

The console shows a Javascript error:
![Error: BaseError.js:25](http://dl.eknoes.de/wire.png)

XHR requests result in HTTP401/403, but no error is shown to the user
![HTTP 401/403](http://dl.eknoes.de/wire-network.png)

**Comment by lipis** [comment]
This seems that it works as expected now, please write back if you still have an issue.
