### ISSUE TITLE
error yarn 

### ISSUE THREAD

**Issue by husseinalsukkar** [wireapp/wire-webapp#5655]
[root@iraqq wire-webapp-dev]# yarn start
yarn run v1.13.0
$ yarn build:server && grunt build && concurrently "yarn start:server:dev" "grunt watch"
$ cd server && yarn build
$ yarn clean && tsc -P tsconfig.json && node ./bin/copy_server_assets.js && node ./bin/create_commit_sha_file.js
$ rimraf ./dist/
/bin/sh: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[root@iraqq wire-webapp-dev]#

**Comment by ffflorian** [comment]
Hi @husseinalsukkar,
you forgot to run `yarn` before building.

**Comment by husseinalsukkar** [comment]
ffflorian 

root@iraqq:~/wire-webapp# yarn start
yarn run v1.13.0
$ yarn build:server && grunt build && concurrently "yarn start:server:dev" "grunt watch"
$ cd server && yarn build
$ yarn clean && tsc -P tsconfig.json && node ./bin/copy_server_assets.js && node ./bin/create_commit_sha_file.js
$ rimraf ./dist/
/bin/sh: 1: rimraf: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@iraqq:~/wire-webapp#

**Comment by husseinalsukkar** [comment]
root@iraqq:~/wire-webapp# yarn run
yarn run v1.13.0
error There are no binary scripts available.
info Project commands
   - build:prod
      yarn build:server && grunt build_prod
   - build:server
      cd server && yarn build
   - build:style
      node ./bin/less.js
   - bundle:dev
      webpack --config webpack.config.dev.js --progress
   - bundle:prod
      webpack --config webpack.config.prod.js
   - bundle:test
      webpack --config webpack.config.test.js
   - configure
      node ./bin/configure.js
   - dist
      grunt build
   - fix
      yarn fix:assets && yarn fix:js && yarn fix:ts
   - fix:assets
      yarn prettier --write && yarn stylelint
   - fix:js
      yarn lint:js --fix
   - fix:ts
      yarn lint:ts:auth --fix && yarn fix:ts:server
   - fix:ts:server
      cd server && yarn fix
   - lint
      yarn lint:assets && yarn lint:js && yarn lint:ts:auth
   - lint:assets
      yarn prettier --list-different
   - lint:js
      eslint -c .eslintrc.json --ignore-path .gitignore --ignore-path .eslintignore --ext .js src/script/ test/ bin/ grunt/
   - lint:ts:auth
      tslint --config tslint.json --project tsconfig.json "src/script/**/*.{ts,tsx}"
   - lint:ts:server
      cd server && yarn lint
   - postinstall
      yarn configure && grunt init && cd server && yarn
   - prettier
      prettier --ignore-path .gitignore "**/*.{json,md}"
   - start
      yarn build:server && grunt build && concurrently "yarn start:server:dev" "grunt watch"
   - start:server:dev
      cross-env NODE_ENV=development node ./server/dist/index.js
   - stylelint
      prettier --ignore-path .gitignore --write "**/*.less" && stylelint --fix --ignore-path .gitignore "**/*.less"
   - test
      yarn test:types && yarn lint && yarn test:server && yarn test:auth && yarn test:app
   - test:app
      karma start karma.conf.js
   - test:auth
      yarn bundle:test && karma start karma.conf.react.js
   - test:server
      cd server && yarn test
   - test:types
      yarn tsc --noEmit
   - translate
      yarn translate:upload && yarn translate:download
   - translate:buildpot
      rip json2pot "temp/i18n/**/*.json" -o "temp/i18n/webapp.pot"
   - translate:download
      node ./bin/translations_download.js && yarn translate:postprocess && yarn translate:extractpo && yarn fix:assets
   - translate:extract
      i18next-scanner 'src/{page,script}/**/*.{js,html,htm}'
   - translate:extractpo
      rip po2json "temp/i18n/*.po" -m "temp/i18n/**/*.json" -o "src/i18n"
   - translate:postprocess
      node ./bin/translations_post_processing.js src/script/localization/translations && node ./bin/translations_post_processing.js temp/i18n
   - translate:upload
      yarn translate:buildpot && node ./bin/translations_upload.js
question Which command would you like to run?:

**Comment by ffflorian** [comment]
Not `yarn run`, but `yarn install`.

**Comment by husseinalsukkar** [comment]
How?

في الاثنين، ٢١ كانون الثاني، ٢٠١٩ ٥:٤٥ م، كتب Florian Keller <
notifications@github.com>:

**Comment by ffflorian** [comment]
> How?

https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install

**Comment by husseinalsukkar** [comment]
I made a format for the VPlS. Can you give me the installation orders
accurately

في الثلاثاء، ٢٢ كانون الثاني، ٢٠١٩ ١١:٢٥ ص، كتب Florian Keller <
notifications@github.com>:
