### ISSUE TITLE
Flickering since last update

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#5659]
## Wire for web version

2019-01-17-15-08

## Browser version

Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

## Installed browser addons

uBlock + uMatrix

## Operating system

Debian 9/stable

1.  Open personal or group chat
2.  Hover mouse over white pane

## What is the expected result?

Normal operation

## What is the actual result?

Serious flickering issues (no corrupted content, only screen redrawing). Only conversation part of the screen is flickering, left part (contacts) is OK. Tested both in FF 64 and 65 (beta).

**Comment by maciejhirsz** [comment]
Can reproduce with Firefox 65 on Manjaro Linux, so this is likely a Linux/Firefox wide thing?

**Comment by maciejhirsz** [comment]
This is still happening as of today on Firefox. It's most visible when moving the mouse cursor from the message area to the text input and back.

**Comment by bennycode** [comment]
Flickering has been fixed.
