### ISSUE TITLE
Ability to Delete, Not Block Contact

### ISSUE THREAD

**Issue by liocalset** [wireapp/wire-webapp#569]
Hi,

Currently there is no way to delete a contact, and the user must block the contact to remove them off their contact list. It would be nice if there were the ability to remove a contact from your contact list without having to block them. Maybe a user has stopped using Wire for a period of time, and you want to clean up your contact list yet not block them. If they come back online, they can resend a contact request without additional intervention on the recipient's end.

Also, the current implementation makes it harder to keep track of contacts the user actually wants blocked vs. those that they simply wanted deleted, should there ever be the ability to view all blocked contacts which would also be nice.

**Comment by helenakos** [comment]
@liocalset Thanks for the request, this is something we should plan to implement in the future.

**Comment by helenakos** [comment]
Closing due to clean up purposes. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by fredericnaud** [comment]
This issue was closed but it's definitely something I would be interested in seeing in the app.  Why was it closed?
Thanks!

**Comment by helenakos** [comment]
@fredericnaud Hey, thanks for writing us. It's closed because due to time constraints we cannot work on it at the moment and there is no committed date right now. So in order to keep better track of everything we tend to clean up the github issues.

**Comment by ghost** [comment]
Not cool!

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206
