### ISSUE TITLE
Markdown headers not appearing on web

### ISSUE THREAD

**Issue by CalebBurton** [wireapp/wire-webapp#5702]
## Wire for web version

 2019-01-28-15-08 

## Browser version

Firefox Quantum Version 64.0.2 (64-bit)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

## Installed browser addons

uBlock Origin, Privacy Badger, Decentraleyes, HTTPS Everywhere

None of these show that they're blocking anything on the page, and the console log is clean.

## Operating system

MacOS Mojave (10.14.2)

## What steps will reproduce the problem?

Send a markdown-styled heading in a message. It transforms into styled text on mobile, but not on web. Similar to the issue described in [Issue #10](https://github.com/wireapp/wire-webapp/issues/10)

![markdown-styling](https://user-images.githubusercontent.com/8314716/51867185-d3bbd380-2318-11e9-9187-26b5b0138052.png)

**Comment by Wurzelkoch** [comment]
Same for Wire for Linux 
3.5.2881
2019.03.18.1258
Markdown that works: *italics*, **bold**, `source`
Any other markdown doesn't render. Former versions of wireapp used to have full markdown support.

**Comment by CalebBurton** [comment]
This also applied to unordered lists. They show up fine on mobile, but not desktop.

**Comment by taylorjdawson** [comment]
@ffflorian is this feature in progress?
Could you briefly explains what needs to be done to fix the markdown rendering issue?
Thanks!

**Comment by bennycode** [comment]
We are supporting headers now in Markdown syntax.
