### ISSUE TITLE
Please stop using CloudFlare

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#5716]
Your [support page](https://support.wire.com/) is in the privacy-abusing private walled-garden of CloudFlare.  It's embarrassing when a end-user-privacy-focused project makes use of CloudFlare and it's bad for their credibility.  Note there is a browser [add-on](https://addons.mozilla.org/en-US/firefox/addon/detect-cloudflare-plus/) for non-Tor users to also detect dodgy CloudFlare sites.

# Problem with CloudFlare
See https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-460077544

**Comment by ghost** [comment]
![cfwire](https://user-images.githubusercontent.com/18015852/52673076-f3114e00-2f1f-11e9-89c9-be170c9ae8d9.png)

**Comment by ghost** [comment]
The problem is worse than I thought, because it's not just users seeking support who encounter CloudFlare.  When a session key loses sync in a conversation, users see:
```
! A message from Bob was not received. Why?
```
And the "Why" is a link to CloudFlare.  So Tor users are being denied information about a problem because the app attempts to access CloudFlare.  Even when the CAPTCHA works, users who are signed into their Wire app should not have to solve a CAPTCHA to get help dialog.

The "Why" should trigger dialog from within the app.

**Comment by resynth1943** [comment]
@bennyn can you please explain why this was closed, seemingly with no resolution?
