### ISSUE TITLE
error bower

### ISSUE THREAD

**Issue by husseinalsukkar** [wireapp/wire-webapp#5730]
root@admin:~/wire-webapp# yarn install
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > react-intl@2.8.0" has unmet peer dependency "prop-types@^15.5.4".
warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".
[5/5] Building fresh packages...
[1/7] ⠂ @bower_components/webapp-module-bubble
[6/7] ⠂ node-sass
[-/7] ⠂ waiting...
[4/7] ⠂ iltorb
error /root/wire-webapp/node_modules/@bower_components/webapp-module-bubble: Command failed.
Exit code: 1
Command: bower install
Arguments:
Directory: /root/wire-webapp/node_modules/@bower_components/webapp-module-bubble
Output:
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm

root@admin:~/wire-webapp#

**Comment by ffflorian** [comment]
@husseinalsukkar 
do not run yarn as root.

**Comment by husseinalsukkar** [comment]
what should i do ?? what is the command that i should use ??
