### ISSUE TITLE
Feature request: forward messages

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#575]
Similarly to the ability to reply on a message #182 it is often useful to forward a message from one conversation to another one (or to the same one).

**Comment by mohammadrafigh** [comment]
this issue seems deprecated I think since we have share for messages now...

**Comment by bennycode** [comment]
It's in our backlog! Thanks @maximbaz. :)

**Comment by knobhead** [comment]
sooooo? :grimacing:
