### ISSUE TITLE
Feature request: ability to have a conversation with myself

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#576]
Today it is impossible to add myself as a contact, though I don't see any technical limitations that prevent us from having this feature.

The reasons for wishing to have a conversation with my own account are:
- Sharing private information between my own devices (especially nice because of end-to-end encryption).
- Quickly adding a note/todo item for myself (especially useful together with the ability to delete messages once they become irrelevant).
- Testing the formatting of a message before sending it to someone else (in cases when you are writing an important message and want it to look nice).

I know quite a few people (including me) who are using this functionality in apps like Slack or Telegram, and I truly believe it is a useful feature to have.

**Comment by gregor** [comment]
Definitely a valid use case. Not sure if and when we will ever implement it though. As a workaround you can create a group with two other people and then remove both of them. You will end up with a conversation like you requested.

**Comment by max-baz** [comment]
Thanks for the workaround!

**Comment by lipis** [comment]
We used to have that actually in the early days of Wire :)

**Comment by max-baz** [comment]
Just curious, what was the reason to remove this functionality? :)

Honestly the workaround works flawlessly, a bit cumbersome to configure, but you need to do it once.

**Comment by lipis** [comment]
If I remember correctly it was a bit confusing for newcomers.. opening the app for the first time and having only one conversation with yourself there.

**Comment by ffflorian** [comment]
@lipis 
> it was a bit confusing for newcomers

Understandable. I also don't think my own name should be in the conversation list from the beginning on, but it would be good if I'd be able to find myself by searching my username - and then start the conversation.

**Comment by anatoli26** [comment]
Just opened a new issue for the subj, but here's already a discussion. Any chance to restore it? The suggestion to not show self at the beginning but make it searchable looks like it solves the reason it was deleted?

**Comment by bennycode** [comment]
For the time being you can create a group conversation and then kickout someone from this group conversation. This will create an almost empty group (only yourself included) which you can use to take notes.

**Comment by thomas-kuntz** [comment]
Cool that we have that ability to do it but I think there could be a far easier way to do this... 😉

**Comment by gregor** [comment]
You can now create conversation with just yourself. Today we released a new version of the webapp with an updated way to create groups. You can skip the step to select participants and can create a conversation with just yourself that way.
