### ISSUE TITLE
Something went wrong please try again

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#580]
I tried to register new user via my localhost website, it returns me "Something went wrong, please try again"
What's wrong with that, supposed to be like that?

**Comment by gregor** [comment]
Yes, due to CORS it is currently not possible to make certain requests from domains which we have not whitelisted on our backend. You will not be able to register from localhost and you will not be able to refresh your access token from localhost for example.

**Comment by herrmannplatz** [comment]
#294

**Comment by herrmannplatz** [comment]
Will close this for now.
