### ISSUE TITLE
Feature request: show help for styling the text with markdown syntax

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#582]
People get confused with markdown syntax (see #250 and #355), but it would be a pity to lose such a nice feature because of it.

I suggest to implement a hint of some sort (at least in the web / desktop apps), that would explain how to style the messages. Perhaps even a most common subset of features, not the full list.

My suggestion of a hint message:

* Use \*stars\* or \_underscores\_ to style text as *italic*.
* Use \*\*double stars\*\* or \_\_double underscores\_\_ to style text as **bold**.
* Use \\\*backslash\\\* to escape special characters like \*stars\* and \_underscores\_.
* Use \`back ticks\` to disable the formatting of `_all_ \special\ *characters* ¯\_(ツ)_/¯`.

**Comment by bennycode** [comment]
Good idea, @maximbaz! Something we could plan for the future.
