### ISSUE TITLE
There is no alert that a conversation became not verified

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#584]
According to the support page a user should be alerted when a non-verified device joins the conversation:

> **Why should I verify my conversations?**
> After verifying a conversation, you will be alerted if your contact starts using Wire on a new device.
> https://support.wire.com/hc/en-us/articles/207859815-Why-should-I-verify-my-conversations-

However this does not happen. Repro steps:

- You (user A) join a conversation with user B
- User A verified all current devices of user B
- User B opens an "incognito browser" and logs in, therefore adds another device
- User B is sending a message to user A
- User A is not notified that this message came from a non-verified device. 
- User A still believes that the conversation is verified, it is impossible to spot this, unless they become suspicious and open a user-info popup.

----------------------------------

~~This relates to another issue, it is very difficult to manually monitor whether the conversation is still verified or not. In fact, the only way to check this is to click on a name, and look for a shield icon **inside** the popup. This is not convenient at all, much better indicator would be the one that is always visible, for example next to the name.~~

**UPDATE**: this is actually a feature, not a bug. Read from [here](https://github.com/wireapp/wire-webapp/issues/584#issuecomment-270399559).

![image](https://cloud.githubusercontent.com/assets/1177900/21276645/aae83338-c3d2-11e6-9926-fac6b75cc703.png)

Feel free to split this issue in two if you think it is reasonable.

**Comment by gregor** [comment]
Our implementation on the web unfortunately lacks a few components of the mobile clients. We definitely have to work on this. Thanks for bringing it up as verification is a key part of trust in encrypted conversations.

**Comment by max-baz** [comment]
By the way, regarding the image with the shield icon, I've just noticed that on app.wire.com the two shield icons are visible, while on the `dev` and `prod` branches there is only one icon.

A hotfix, that was forgotten to be merged back? :wink:

**Comment by herrmannplatz** [comment]
@maximbaz there was an issue when you only had one device, the conversation wouldnt be marked as verfified. that should be fixed on dev and should land on prod with the next release.

**Comment by max-baz** [comment]
I think you refer to a different issue. Have a look at screenshot below, this is what I see today on `dev` branch. Two devices, both verified, and the icon is missing. Open `app.wire.com`, and the icon is present.

![image](https://cloud.githubusercontent.com/assets/1177900/21644662/d0cb5592-d28e-11e6-8dce-4b9e8ead6d78.png)

**Comment by herrmannplatz** [comment]
In order to verify a conversation you need to verify all the participating clients (including your own client). Keep in mind that the verification is not synced across clients (see #248). So pls check your devices in the preferences. Also keep in mind app.wire.com and your local dev branch are two different clients.

**Comment by max-baz** [comment]
I know that :) On the screenshot above you see that all two devices are verified, and the icon to the right is visible. When the icon to the right is visible, the icon to the left should also be visible.

That is also clear that app.wire.com is not a `dev` branch, but I hoped that it follows the `prod` branch :)
I mentioned that earlier and I just double checked, the behavior on `prod` branch is exactly the same, no icon on the left side of the name.

**Comment by herrmannplatz** [comment]
Ok ok :)

Can you pls check again that you have verified your own devices in the preferences (preferences > devices)? The shield in the popover only indicates that this user with all her/his devices is verified.

**Comment by max-baz** [comment]
Oh wait, now I get what you are saying! So the icon on the right means "I verified all this user's devices, so nobody is eavesdropping on _their_ side", but icon on the left means "I verified all their and mine devices, so nobody is eavesdropping on _any_ side"?

Yes, that was it! I had one of my devices not confirmed, just like you said. Now that I know this, it actually makes sense! :smile:

**Comment by max-baz** [comment]
Then this issue is only about "notifying" that a conversation has suddenly became not verified as mentioned in the docs. I was confused that two icons have different meaning but now I see the point of it, so it is not an issue after all. Sorry about that :)

**Comment by herrmannplatz** [comment]
No problem. Yes indeed thats still an issue.

**Comment by gregor** [comment]
The system messages that indicate a conversation downgrade are fully implemented and live for quite some time. Thus closing this issue.
