### ISSUE TITLE
Dark Mode: Input / Output selection dropdown is all white.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#5852]
![image](https://user-images.githubusercontent.com/388716/52918655-82738400-32c7-11e9-8bdd-e44949d72f32.png)

**Comment by ffflorian** [comment]
Hi @Transisto,

please provide some more information when reporting bugs like this, especially:

* which browser
* which operating system
* which extensions

you are using.

Additionally, add a note if you are using the dark mode.

Thanks.

**Comment by Transisto** [comment]
Windows 10 desktop

**Comment by ffflorian** [comment]
Thanks for the bug report, I can reproduce it.
