### ISSUE TITLE
Searching in a conversation moves to the right spot for a second but view jump away I think when images load.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#5866]
To reproduce, 

Search for something old with images arround the same time. 

Message location get lost and I'm never sure if I should be scrolling up or down to get to it.

**Comment by mythsunwind** [comment]
Hi @Transisto thanks for the report. This will be fixed in the next release of the WebApp.

**Comment by bennycode** [comment]
It's fixed now.
