### ISSUE TITLE
Typo in Device Verification Screen

### ISSUE THREAD

**Issue by gopherit** [wireapp/wire-webapp#5902]
For some reason, there are extra strings of the user's first name at the beginning and end:

![wire-desktop-web-device-typo](https://user-images.githubusercontent.com/25557897/53294693-8caaec00-37b9-11e9-86ec-3d696132bd43.png)

This appears in both the Web and Desktop versions but not the mobile version.

Wire for Web:  Version 2019-02-18-11-26
Wire for Desktop:  3.6.2908 2019.02.18.1126

I tried finding the string in the code so I could submit a pull request, but I'm not familiar with where to find it, so I'm making an issue instead.

**Comment by lipis** [comment]
Are you sure this screenshot is from the WebApp and not Android?

**Comment by gopherit** [comment]
@lipis, 100% positive.  The error occurs in both the web app (https://app.wire.com) as well as the Desktop version of Wire for Windows.  It does not occur in the Android app.  The Android app correctly says, "Verify that this matches the fingerprint shown on Dubz's device."  It lacks the two extra strings before and after.

**Comment by ffflorian** [comment]
Hi @gopherit, thanks for the report. This will be fixed in the next release of the WebApp.

**Comment by gopherit** [comment]
This bug was resolved quickly, a few days after this Issue was created.  Thanks Wire development team.  Closing.
