### ISSUE TITLE
Inconsistent display of some characters between web interface and app

### ISSUE THREAD

**Issue by Caspy7** [wireapp/wire-webapp#599]
If I put  ̆¯\\\_(ツ)\_/¯̆  in the web app it shows up as  ̆¯_(ツ)\_/¯̆ for me. I realized it's wiki markup so I inputted  ̆¯\\\\\\\_(ツ)_/¯̆ and it displayed correctly. Then my friend, on her mobile app, says that the first one looked fine but the second one had three arms.
*sigh*
So for me I'm seeing something differently than she's seeing because the web app version seems to be interpreting wikimarkup while the mobile app is not.
The primary difference in this case seems to be the interpretation of \

**Comment by max-baz** [comment]
Link: https://github.com/wireapp/wire-android/issues/414 and https://github.com/wireapp/wire-webapp/issues/494 and https://github.com/wireapp/wire-webapp/issues/582

**Comment by lipis** [comment]
I will close this.. @Caspy7 please upvote the ones that are posted by @maximbaz  :)
