### ISSUE TITLE
Bug: messages are displayed in a wrong order when client time is not exact

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#600]
I've discovered an interesting case, where messages appeared in different order on different devices. 
Have a look what two users see on different clients. The number in a message denotes the order of when it was sent:

![image](https://cloud.githubusercontent.com/assets/1177900/21467416/dfcd8c4a-c9ec-11e6-9e1c-e9b803b78226.png)

Further investigations showed that the time on Windows box was ~20 seconds ahead, comparing to all other clocks. Even though the OS time was set to be automatically synchronized with internet time!

I disabled the automatic synchronization and enabled it again, and for all new messages the issue was gone.

While yes, it is an issue with Windows time service itself, I think the app should handle this case somehow. Who knows how many users are affected with this bug? 

Perhaps a simple and sufficient solution would be to check on app startup if client time is accurate (like time.is does it), and if there is a sufficient difference, show a warning and suggest users to synchronize the time.

**Comment by lipis** [comment]
That's a known issue when the system time is wrong. Fortunately today most of the devices have the correct time. But it's an interesting idea maybe to check in the beginning if the time is correct and just inform the user that their time is most likely wrong and some messages might not be in order.

**Comment by gregor** [comment]
@maxin Thanks for the detailed issue report. Just as @lipis stated this is currently a limitation of the webapp. Due to some decision we took with the database stucture and primary keys, we currently cannot and do not update timestamps of outgoing messages. All incoming messages are tagged with a server timestamp. We do get that timestamp from the server when sending a message but as we have previously written the message to the database. We have not found the time to write and test a database upgrade routine that allows us to handle this more properly moving forward. It's definitely on our wish list though.

**Comment by max-baz** [comment]
What a coincidence, during one day I stumbled upon 3 issues that all look like a duplicate of this one. I was not searching for them on purpose :)

**Comment by bennycode** [comment]
It gets time to fix this bug. We will investigate on it in our next "Service Run". ✌️

**Comment by anatoli26** [comment]
Some of my contacts are also affected, always windows desktop client, but from this issue and the related ones I understand this is a general problem of all clients. It's a show-stopper actually, for now I just recommend my contacts not to use desktop client, only mobile (it's too difficult and error-prone for most non-technical users to configure time sync on windows).

This is the most significant issue I found during my first 24 hs of Wire use, all other issues are less important. You guys are doing a great job!

**Comment by herrmannplatz** [comment]
should be fixed with https://github.com/wireapp/wire-webapp/releases/tag/2017-03-08-17-32
