### ISSUE TITLE
7 days duration for the "Timed message" (or at least 3-5 days...)

### ISSUE THREAD

**Issue by Kasmetski** [wireapp/wire-webapp#606]
What do you think about 7 days "Timed message"? For now the longest duration is 1 day.
When people are using this option for all of their messages and contacts it's going to be useful to have 7 days option too (or at least 3 - 5 days...). If someone couldn't see the message until the 24 hours he could see it in the next days.

**Comment by gregor** [comment]
The lifespan of a timed messages does not indicate until when a recipient can read a message but for how long. The timer will only start once it is rendered into the view on one of his devices. Users can definitely read a message the next day even if it is set to 30s only.

**Comment by Kasmetski** [comment]
In this case there is no need of 7 days timer, so you can close the issue.
Thank you for the explanation.
