### ISSUE TITLE
Can't Make Voice Calls on 32-bit Laptop

### ISSUE THREAD

**Issue by strypey** [wireapp/wire-webapp#6063]
## Wire for web version

 2019-02-28-15-10

## Browser version

ABrowser 64 (32-bit). ABrowser is basically a reskinned and hardened Firefox, minus proprietary bits.

## Installed browser addons

NoScript 10.2.2rc2 (wire.com marked as "trusted")
uBlock Origin 1.18.4 (disabled for app.wire.com)

## Operating system

Trisquel 8 Flidas GNU/Linux (32-bit. Trisquel is basically Ubuntu 16.04 minus all the proprietary bits, and with a Mate desktop instead of GNOME)

## What steps will reproduce the problem?

1.  Login to app.wire.com
2.  Choose a contact. 
3. Click the phone icon to start a voice call.

## What is the expected result?

The app will keeping ringing until the contact answers, the call is cancelled, or the preset numbers of rings is reached without an answer.

## What is the actual result?

App starts calling, then immediately hangs up.

# Additional information

I can't receive calls either. The app rings when a contact initiates the call, but as soon as I click to answer, it hangs up. Normally, apps that require use of the microphone pop up an applet asking for permission to use it. I get no such pop-up when trying to use voice calling on Wire, and I suspect that's where the problem lies. When the desktop client was working on 32-bit devices like mine, voice calling worked fine.

**Comment by ffflorian** [comment]
@strypey Have you tried it with the normal Firefox version?

**Comment by strypey** [comment]
On 2019-03-12 21:39, Florian Keller wrote:
> @strypey Have you tried it with the normal Firefox version?

Not on that OS. Vanilla Firefox has a number of proprietary components,
so its not available in the Trisquel repositories. I'm happy to test in
any browser that doesn't have proprietary components. Also happy to send
you console outputs or logs to help you debug the problem. Just let me
know what you need.

**Comment by strypey** [comment]
The web app is now telling me:
"you cannot call because your browser does not support calls"

ABrowser is essentially a rebranded Firefox, so it ought to be able to support calls. As I said in the original bug report, web apps that require use of the microphone normally pop up an applet asking for permission to use it. I get no such pop-up when trying to use voice calling on Wire, and I suspect that's where the problem lies. When the desktop client was working on 32-bit devices like mine, voice calling worked fine.

Could the problem be related to Wire no longer supporting 32-bit computers, rather than being related to the browser? If this is the case, it would be great if the error message identified the problem correctly.

**Comment by strypey** [comment]
If there's been a decision to stop supporting the browser version of Wire on 32-bit devices, it would be great if users got a message to that effect when they try to login using a 32-bit device (eg "The Wire team are no longer providing official support for any use of Wire on 32-bit devices, here be dragons" or whatever). If not, it would be great if we could get some eyes on this bug. Many of the community using Trisquel/ Abrowser (including the FSF) have been keen users and promoters of Wire.

**Comment by bennycode** [comment]
We don't provide professional support for modified versions of Mozilla Firefox.

**Comment by strypey** [comment]
FYI I just tested app.wire.com again on the latest versions of Trisquel 8.0 and Abrowser. The app is now successfully asking for permission to use the mic, and the call is ringing. So the problem appears to have been solved. Thanks for that.

@bennyn
> We don't provide professional support for modified versions of Mozilla Firefox.

This raises two issues. Firstly, app.wire.com is advertised as a web app. That means if it doesn't work in any standards-compliant web browser, as well as being false advertising, it undermines the ideal of the open web governed by web standards any vendor can implement.

Secondly, it seems like all the browsers you do officially support contains proprietary components. AFAIK vanilla Firefox does (the Adobe EME crippleware module), as do Safari and Chrome. Is there any fully free code browser that you do provide professional support for? If not, how does that support Wire users who care about their software freedoms? Keep in mind that  one reason many users might pick Wire over another E2EE chat app is because it's liberating software, with full source code available under a free license.

**Comment by bennycode** [comment]
> as well as being false advertising

We explicitly define on our [download page](https://wire.com/download/) and [support page](https://support.wire.com/hc/en-us/articles/202960551) which browsers we support.

**Comment by strypey** [comment]
@bennyn 
> We explicitly define on our download page and support page which browsers we support.

I'm sorry but that's a cop out. If a web app doesn't work in any and all standards-compliant web browsers, that's a bug that needs to be fixed. In the late 90s and early 2000s, a lot of websites could only be viewed properly in Internet Explorer. A lot of work was done to convince web developers to make their work web standards compliant, so it can be viewed properly in any web browser, and users can use the browser they prefer, instead of being forced by compatibility headaches to use the browser developers prefer. 

One of the reasons complying with open standards is important is because it helps users avoid being compelled to use proprietary software, when they would otherwise choose liberating software. The page you link to lists Chrome, Microsoft Edge, Opera, or Firefox. All of these contain proprietary software. It's simply unethical to oblige users to install and use proprietary software in order to use a web app, especially one that promote itself as "open source".

Given that you don't supply native clients for 32-bit desktops, nor officially allow community-developed clients to access your servers, the only way to chat with Wire contacts on a 32-bit device is via the web app. So it's all the more important that the web app works with any standards-compliant browser.
