### ISSUE TITLE
Cursor is in a wrong position in textarea with a certain text length

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#6105]
## Wire for web version

Both in production and latest `dev` branch, which is `2019-03-14-21-49` right now.
I've been experiencing this for a long time, but didn't have time to compose a proper bug report 🙂 

## Browser version

Latest Chromium on Linux (73.0.3683.75)
Latest Wire Desktop (3.7.2891)

## Installed browser addons

Doesn't matter since it reproduces in Wire Desktop.

## Operating system

Arch Linux

## What steps will reproduce the problem?

1. Start pasting the following text again and again in the textarea for composing a new message: "lorem ipsum dolor sit amet "
2. At some point you will see that a scrollbar appears, and cursor is in a completely wrong position:

![wire1](https://user-images.githubusercontent.com/1177900/54391253-9468fc80-46a4-11e9-9d82-0bfde2d021fe.gif)

3. But if you continue pasting the text, once the message becomes large enough, the issue disappears:

![wire2](https://user-images.githubusercontent.com/1177900/54391339-d98d2e80-46a4-11e9-8a38-5cc461eb48cd.gif)

## What is the expected result?

At no time a scrollbar is visible and cursor is always in the correct position

**Comment by Filbuntu** [comment]
@ffflorian Thank you for combining the two reports. Will there be some work on this?
It is is still an issue (I-beam pointer (AKA the I-cursor) is moved away from the actual typing place:
Wire version: 3.11.2912
Wire for web version: 2019.11.26.1327
Operating system: Ubuntu 19.10 (and 19.04)
Which antivirus software do you have installed: No active one.

**Comment by Filbuntu** [comment]
Hopefully there will be a fix for this soon as it is really a bugging bug. Thanks in advance!

**Comment by lipis** [comment]
This should be fixed now.. please verify and report back if you still have the issue.

**Comment by Filbuntu** [comment]
@lipis  Thanks for working on this and notifying us about the progress! 
I was already thinking Wire is on freeze as I have not seen any progress on the issues I am subscribed to. As this one and another one were addressed, I am very much encouraged!
PS: From which Wire Desktop App version on is the issue fixed?
