### ISSUE TITLE
Markdown formatting partially broken

### ISSUE THREAD

**Issue by Wurzelkoch** [wireapp/wire-webapp#6162]
This is more or less a duplicate of https://github.com/wireapp/wire-webapp/issues/5702.
The same (or a very similar) problem appears in wire-desktop.

Wire version: 3.5.2881
Wire for web version: 2019.03.18.1258
Operating system: Debian 9 with Linux Debian 4.9.0-8-amd64
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Send message formatted using markdown
2.  View message with Wire for Linux

What is the expected result?
Proper Markdown formatting

What is the actual result?
only *italic*, **bold**, `source` render, any other markdown appears unformatted

**Comment by ffflorian** [comment]
Hi @Wurzelkoch, as you already said, this is a duplicate of #5702. Or is there anything else in your but report? If not I'm going to close it for now. 🙂

**Comment by Wurzelkoch** [comment]
I didn't know who separated webapp and desktop are, so I wanted this issue also in desktop. If it will be dealt with in webapp, happily close this duplicate.

**Comment by ffflorian** [comment]
@Wurzelkoch
the Desktop app is just loading the webapp in the background, that's why I moved your issue. I'll keep you updated in #5702.
