### ISSUE TITLE
Can't see my messages from the other devices

### ISSUE THREAD

**Issue by Kasmetski** [wireapp/wire-webapp#620]
Not sure if this is a bug, or I suggest a future request, but here is the problem..

I'm using latest versions of Wire for Android and Linux.
I have verified my devices.. the problem is when I write something from my phone, I can't see it in the chat on my computer. Same thing happens from pc to phone.

I would suggest to keep this behavior when the devices are not verified, but when I do, I prefer to see the messages...

**Comment by max-baz** [comment]
@Kasmetski how does that exactly behave, when someone sends a message to you, you see it displayed on both devices, but when you post a reply, your own message is visible only on that one device?

If yes, I wonder if you might hit #600, that is, your devices have different system time, and your outgoing message is displayed in a different place, perhaps being inserted somewhere up in the conversation history.

**Comment by Kasmetski** [comment]
`@Kasmetski how does that exactly behave, when someone sends a message to you, you see it displayed on both devices, but when you post a reply, your own message is visible only on that one device?`
-Correct

I've made more tests and this is what I found..
The problem only appear when "Time messages" are checked. If this option is OFF - everything is great and I can see the message on both devices immediately.

**Comment by herrmannplatz** [comment]
@Kasmetski thats correct, timed messages are not send to you own clients. we should make this more clear. Will close this for now.

**Comment by Kasmetski** [comment]
And why is that? Is there a chance to have this like a option in the settings? If I want to share my messages with the other devices, even if they are "time messages"?
