### ISSUE TITLE
Device verification restart

### ISSUE THREAD

**Issue by karzembe** [wireapp/wire-webapp#6244]
We encountered an issue with Wire regarding the device verification. When the devices are verified and the user logs off and on, all verified devices become unverified. And even if you log off and log on from the same device your device are shown as a new device. If it is something we can fix? Would you consider it for feature request?

Wire version: 3.7.2891
Wire for web version: <Check the About dialog>
Operating system: Linux mint
Which antivirus software do you have installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?

1.  Verify devices
2.  Log off and on
3.  Verified devices are unverified

What is the expected result?

What is the actual result?

Please provide any additional information below. Attach a screenshot if possible.

**Comment by bennycode** [comment]
We have fixed this issue. Thanks for reporting.
