### ISSUE TITLE
Markdown Images

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire-webapp#627]
Opening a ticket here, just for better tracking. Have mentioned a few things via [twitter](https://twitter.com/0xdade/status/820198012769026048).

## Case 1
```
![dade](https://zerocool.io/dade_murphy_32.jpg)
```

Generates this (incorrect) HTML

```
<img src="a href=&quot;https://zerocool.io/dade_murphy_32.jpg&quot; target=&quot;_blank&quot; rel=&quot;nofollow noopener noreferrer&quot;&gt;https://zerocool.io/dade_murphy_32.jpg&lt;/a" alt="dade">
```

## Case 2
```
![dade](//zerocool.io/dade_murphy_32.jpg)
```

Generates this (correct) HTML

```
<img src="//zerocool.io/dade_murphy_32.jpg" alt="dade">
```

&nbsp;

## Proposed Solution
I see two solutions for this:

1. When inserting images via markdown on the web, handle `https://` the same as `//` is handled when generating the images, then allow CSP to continue blocking them.
2. **(Ideal)** Handle markdown images the same way that github does, where it downloads the file to something that is within the CSP zone, uses that for `src=` then provides the original url via `data-canonical-src=` attribute.

**Comment by gregor** [comment]
Fixed by #1875. Will be part of the next release to production.
