### ISSUE TITLE
The upload progress circle is too small to be noticeable on desktop devices

### ISSUE THREAD

**Issue by notNSANE** [wireapp/wire-webapp#628]
![vu6wc0z](https://cloud.githubusercontent.com/assets/7162375/21971926/2fae42a0-db94-11e6-98cf-ce683caed598.png)

There's not enough contrast between the green and the grey, and it's really small. I have to get my eyes closer to the monitor to actually see the progress.

**Comment by helenakos** [comment]
@notnsane Thanks, forwarding to our design team.
