### ISSUE TITLE
Desktop/Screen sharing always shares the recently shared window

### ISSUE THREAD

**Issue by thenktor** [wireapp/wire-webapp#6291]
## Wire for web version
2019-03-29-09-38

## Browser version
Firefox 66.0.2 

## Operating system
macOS

## What steps will reproduce the problem?

1.  Join a meeting/chat room as guest
2.  Share screen
3.  Chose a window, that should be shared
4.  Stop sharing screen
5.  Share screen again

## What is the expected result?
It should ask again, which window/screen should be shared

## What is the actual result?
It just shares the recently shared window without asking again. Therefore it's not possible to share another window/screen if needed.

**Comment by Yserz** [comment]
Unfortunately Firefox doesn't expose this API, but it's possible to select application windows in Chrome now.
