### ISSUE TITLE
meta: enable issues on the main wire repo

### ISSUE THREAD

**Issue by d4l3k** [wireapp/wire-webapp#63]
As far as I can tell there's no recommended place to file issues that effect the entire platform. It'd be nice if the wireapp/wire repo had issues enabled and was used for feature requests and discussion that spans the entire platform.

Alternatively, it'd be nice if the internal issue tracker was public. There's a few references here and there to it.

**Comment by bennycode** [comment]
@raphaelrobert WDYT?

**Comment by d4l3k** [comment]
@raphaelrobert @bennyn Any updates on this?

**Comment by bennycode** [comment]
Hey @d4l3k, sorry for the late reply! We decided to continue facing issues in the individual repositories instead of dealing with them in the main repository. So please keep up posted here. :smiley:
