### ISSUE TITLE
"decrypting messages" for a while then get logged out.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#6302]
![image](https://user-images.githubusercontent.com/388716/55687674-b79e6900-593d-11e9-9a3c-adc744ca3073.png)

I tried using the web app after having been logged out for no reason on desktop 
in this issue : https://github.com/wireapp/wire-desktop/issues/2457

I waited about 5min for "decrypting messages" to load then near 80% into it I get the above screen asking me to log in.

I logged back in with password and everything went fine all history loaded properly. I'm reporting in case it can help the linked desktop issue.

**Comment by bennycode** [comment]
Thanks! We have fixed this particular issue in the past.
