### ISSUE TITLE
Libre variant of Firefox "not supported"

### ISSUE THREAD

**Issue by strypey** [wireapp/wire-webapp#6344]
## Wire for web version

2019-04-10-09-01

## Browser version

ABrowser 66.0.2 (32-bit) - essentially a reskinned Firefox, with any proprietary bits like the Adobe EME module removed.

http://whatsmyuseragent.org identifies it as:
Mozilla/5.0 (X11; Linux i686; rv:66.0) Gecko/20100101 Firefox/66.0

## Installed browser addons

* NoScript 10.1rc1 (wire.com marked as "trusted")
* uBlockOrigin 1.18.1 (disabled for wire.com)

## Operating system

Trisquel 8 (Flidas) GNU/Linux ([FSF-endorsed distro](https://www.gnu.org/distros/free-distros.html) based off [Ubuntu 16.04](https://distrowatch.com/?newsid=10171))

## What steps will reproduce the problem?

1. Open  a new browser tab in ABrowser on Trisquel 8
2.  Navigate to app.wire.com

## What is the expected result?

A login screen.

## What is the actual result?

An error message saying:
> "This browser is not supported.
> Download the latest version of Google Chrome, Mozilla Firefox, Opera or Microsoft Edge."

## Additional notes:

* This only started happening today, sometime within the last 5 hours. I was able to login as normal at 15:00 Hong Kong time (CST)
* could this be related to voice calls not working for some time on the same browser/ OS, as reported in #6063 ?

**Comment by strypey** [comment]
The Wire web app appears to be working in 32-bit ABrowser again. Yay!

**Comment by ffflorian** [comment]
@strypey I will close this issue then. Great that it's working again for you!
