### ISSUE TITLE
delivery notifications and sent times

### ISSUE THREAD

**Issue by d4l3k** [wireapp/wire-webapp#64]
One feature that I really like from signal is delivery notifications via a status icon. It makes it clear whether the other person is available to receive the message or not.

In addition, sent times makes it nice for people on the other side so they can see the actual time the message was sent. One use case is when I'm commuting to and from work via the subway and messages are sometimes delayed by up to 10m while I have no cell signal. It just makes it clearer which messages were supposed to be a response to other messages. If someone sends me a message and I respond while without cell signal, and then they send me another message it's currently ambiguous to which message I was responding to.

Filed in this repo due to  https://github.com/wireapp/wire-webapp/issues/63

**Comment by herrmannplatz** [comment]
Its indeed an interesting feature but not on our roadmap so far.

**Comment by d4l3k** [comment]
@herrmannplatz Is the roadmap posted anywhere for the community to see and comment on?

**Comment by lipis** [comment]
Not the same issue of course but it's kind of related to the user presence indication (#8). 

As for the roadmap, we don't have anything in public. What do you think would be the most appropriate media for it?

**Comment by d4l3k** [comment]
CockroachDB has a page on the GitHub wiki https://github.com/cockroachdb/cockroach/wiki.

**Comment by d4l3k** [comment]
I'm not necessarily a huge fan of it. Doesn't have a great way to leave comments. Previously it was in the form of a GitHub issue https://github.com/cockroachdb/cockroach/issues/2132
