### ISSUE TITLE
Feature request: a message with an image URL should be replaced with the image itself

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#640]
I can think of one intuitive way to share images on Wire web / desktop: find an image in the browser, right click > "Copy image URL" > paste in Wire and send.

Today the pasted link remains a link, while I would expect it to be converted to an image automatically (similarly to how there is sometimes a website preview generated for a pasted URL).

If the message consists of something plus image URL(s), then the message should not be replaced entirely, but the image(s) should be attached after the message.

There could have been a workaround to wrap the link in `![](pasted_link)`, except that (1) this requires even more editing due to #627 and (2) there is a content security policy, that refuses to accept any image from domains other than a few predefined ones.

For the second point, I double @0xdade's suggestion in #627: 
> Handle images the same way that github does, where it downloads the file to something that is within the CSP zone, uses that for src= then provides the original url via data-canonical-src= attribute.

**Comment by fortran77** [comment]
The default action should be to send a link as a link. This is intuitively more correct, and it does not require the software to distinguish between links to images and links to other things like html pages and binary files.

Users often prefer to send links to public images (and other public documents), and not the images (or other documents) themselves, over low-bandwidth channels.

After inserting a link, the user could explicitly ask that the link be resolved.

**Comment by 0xdade** [comment]
I think it'd probably be ideal to have the recipient(s) click a link that ends in (.png, .jpg, whatever) and have it loaded inline in the client. That would be a bit of a compromise, where it makes it so you can see images without leaving the client, but not necessarily automatically fetch the image.

**Comment by max-baz** [comment]
Actually when [this pull request](https://github.com/wireapp/wire-webapp/pull/570) makes its way to production, a knowledgeable sender will know to use "Copy image" instead of "Copy image URL" in browser when they want to share a picture with someone. I will still be annoyed when someone else sends me a link instead of an image (as I will need to click it, switch to a browser to look at it, switch back), but the total priority of this feature request will be smaller... maybe?

In my opinion, low bandwidth scenarios are important for mobile clients, but not really for the web client. It might be possible that with such decision we sacrifice usability for 100% of users for the sake of those 1% who count every megabyte of their home internet connection. I don't know the numbers though, it's just a theory to consider.

My thinking behind this proposal is simple: a website link is sent for you with an intention that you will look at it in your browser (and even then Wire is generating a preview, with title and image preview). An image link is sent to you with an intention to see an image. The less actions it takes to do that, the better. Zero actions — good, one action (click a link to see image inline) — appropriate for low bandwidth scenarios, switching back and forth between Wire and browser — not appropriate.

By the way, there's a feature request to [globally disable URL previews](https://github.com/wireapp/wire-desktop/issues/293). I think all low-bandwidth scenarios should be covered by that one. One toggle in settings, and you don't get any previews, not for websites, not for images.

**Comment by Bugsbane** [comment]
Personally I would wish that we saw the image inline, so there was no need to click, wait for the browser to open etc, but that the link was displayed underneath (either in full or a link icon with the word "Link" that opened a browser when clicked), so I could still copy that if I wished. Clicking on the image itself would open it in the default gallery app. A Web browser is a distinctly suboptimal place to view images unless you're already in the web app using one.

**Comment by aquatooth** [comment]
yeah, i put my 2cents in here for a vote UP on this feature request, however there might be more important things like bugs to work on first!

**Comment by mythsunwind** [comment]
Please do not add "me too" comments into a bug tracker. If you want to show your sympathy for a feature request, GitHub has the possibility to add "reactions". This will reduce noise for us, while make us aware that more people would like the same feature. Thank you.

**Comment by bennycode** [comment]
I will close this issue for now because we will collect feature requests here: https://github.com/wireapp/wire/issues

But thanks for bringing it up, @maximbaz!
