### ISSUE TITLE
Webapp incorrectly detects 'private mode'

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#6489]
System:
firefox-esr 60.5.0esr
Debian 9.7 64 bit
Gnome 3.22.2

Problem:
Trying to login to the webapp at app.wire.com, I get:
'You are in private mode.
 Wire needs access to local storage to display your messages. Local storage is not available in private mode.'
I am not in private mode. However, I use a lot of browser privacy and security features. I have turned most of these off but it doesn't seem to fix the problem. The list is:
- Cookies (usually disabled, but allowed for this session)
- Browser plugins NoScript, Privacy Badger, uBlock Origin, and HTTPS Everywhere (all disabled for this session)
- Always use tracking protection (switched off for this session)
- Always block popups (exception added for https://app.wire.com/)

Any thoughts?

**Comment by next-mad-hatter** [comment]
It seems some firefox upgrades can break user profiles and cause indexeddb to become unusable.  @ghost does the problem persist under a new firefox profile (your history will be unavailable there of course)?

**Comment by bennycode** [comment]
Closing the issue because @ghost is a deleted user on GitHub.
