### ISSUE TITLE
"File could not be saved" during backup

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [wireapp/wire-webapp#6493]
## Wire for web version

version="2019-04-23-10-51"

## Browser version

Firefox 66.0.3 (64-bit) (Ubuntu)

## Installed browser addons

ublock Origin

## Operating system

Ubuntu 18.04.2

## What steps will reproduce the problem?

1.  Login in
2.  Click Preference
3.  Click **Back up conversations**

## What is the expected result?

Backup is created and available for download

## What is the actual result?

"File could not be saved" is displayed

For a (split) second, the progress bar is displayed, as usual 
![Screenshot from 2019-04-29 20-40-50](https://user-images.githubusercontent.com/18633286/56919279-7de5fb80-6ac0-11e9-9d6a-b520e8eebd3b.png)

But after that, the error is raised
![Screenshot from 2019-04-29 20-42-39](https://user-images.githubusercontent.com/18633286/56919307-89d1bd80-6ac0-11e9-833d-a9bbac675839.png)

I don't know if it's related but this error is raised within the javascript console during the backup
![Screenshot from 2019-04-29 22-13-40](https://user-images.githubusercontent.com/18633286/56924221-a7a51f80-6acc-11e9-9c57-3076af114548.png)

:sunflower:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
For information, same problem with version `2019-05-09-09-36` and Firefox 66.0.5

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
For information, same problem with version `2019-06-06-12-31` and Firefox 67.0.1

**Comment by bennycode** [comment]
Thanks for the report. We have fixed this issue! ✌️
