### ISSUE TITLE
video: be able to change where the local video is pinned

### ISSUE THREAD

**Issue by d4l3k** [wireapp/wire-webapp#65]
It'd be nice to be able to move the local video pin location. There are times when it is obscuring the video feed of the other person and it'd be great to be able to move it to a different corner.

Most of the time I prefer to pin it top middle right under the camera so it appears I'm looking into the video camera.

Ideal pinning locations
- Top left
- Top right
- Bottom left
- Bottom right
- Top center

**Comment by helenakos** [comment]
Hey @d4l3k, thanks for the feedback! Having it in the middle so it appears you're looking into the camera makes a lot of sense. Opening a ticket internally :)

**Comment by helenakos** [comment]
No committed date yet. Closing this issue as part of cleanup.

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
