### ISSUE TITLE
Webapp cannot restore from Android backup

### ISSUE THREAD

**Issue by mlms13** [wireapp/wire-webapp#6514]
## Wire for web version

2019-04-23-10-51

## Browser version

- Firefox 66
- Some version of Chrome via Electron in Rambox

## Installed browser addons

None in Electron

## Operating system

Ubuntu 18.04

## What steps will reproduce the problem?

I was using the Wire webapp through [Rambox](https://rambox.pro/#home), and when I switched from the Snap package to the `deb` package, it lost my history. I'd love to restore from an Android backup, but that doesn't seem to be possible.

1. Create backup from Wire for Android
2. Save it to Dropbox or somewhere you can access from a computer
3. From the webapp, go to settings and Restore from backup
4. There's a file mask that filters out backups from Wire for Android based on the file extension, so choose to view "All files"

Step 4 suggests things aren't going to go well...

![Screenshot from 2019-05-02 11-12-22](https://user-images.githubusercontent.com/1105543/57093466-31224080-6ccb-11e9-8a37-0623737ade60.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi,

On the web application (preferences -> account): 

> You can only restore history from a backup of the **same platform**. Your backup will overwrite the conversations that you may have on this device.

(emphasis mine)

So I think you cannot restore your webapp with Android backup.

:sunflower:

**Comment by bennycode** [comment]
History backups from webapp / desktop app are compatible with each other. However, backups from other platforms (i.e. iOS and/or Android) are not compatible with our webapp / desktop app. We noted this as a feature request. Thanks.
