### ISSUE TITLE
Search index contains expired messages

### ISSUE THREAD

**Issue by moba** [wireapp/wire-webapp#6611]
Expired messages at least in group chats on the Desktop application can still be found in the search.

Wire version: 3.9.2895 2019.05.09.0936
Operating system: Debian

What steps will reproduce the problem?

1.  Open "search" in a conversation with expired messages.
2.  Search for strings contained in old, expired messages.
3.  You will see the search result, but when you click on the result it takes you back to the conversation.
4. If you search for the same result a second time, it will be gone from the search.

What is the expected result?

No hits! Expired messages should be directly purged from the search index.

The mobile client does not behave this way, it shows no search results in the same conversation.

**Comment by muesli** [comment]
Can confirm I can reproduce this on Arch with 3.9.2895 as well.

**Comment by lipis** [comment]
It seems that it's fixed now, we can't reproduce it. If you still have issues, please write us back.
