### ISSUE TITLE
Consider moving away from CoffeeScript?

### ISSUE THREAD

**Issue by Siilwyn** [wireapp/wire-webapp#67]
Moving forward, before Wire explodes in popularity :smiley: I think it's worth thinking about and discussing if CoffeeScript is worth using instead of vanilla JavaScript. CoffeeScript requires a compile step and additional understanding which adds an extra hurdle for people to contribute.

Looking at [GitHut](http://githut.info/) JavaScript has roughly 22 times more repositories and is growing faster in popularity while the amount of repositories in CoffeeScript is stagnating.

**Comment by bennycode** [comment]
[CoffeeScript](http://coffeescript.org/) was the programming language which suit us the most when starting to work on [Wire for Web](https://app.wire.com/). Moving with the times we are evaluating [TypeScript](https://www.typescriptlang.org/) and ECMAScript 6 in conjunction with the [Babel compiler](https://babeljs.io/). What's your take on that, @Siilwyn?

**Comment by Siilwyn** [comment]
All three have useful features and it depends on the core contributors preference, vision and experience. The more familiar you are with a language, the easier it is to understand. The size of the project is also an important factor TypeScript's compile-time type checking comes in handy in a large code base and should lead to fewer bugs.

I would say use ES6 because then you're part of the largest development community, rather than a subset. Unless you think a lot of bugs could be prevented by type checking. Another added benefit would be that in the future the build step with Babel can be removed which leads to less complexity.

**Comment by bennycode** [comment]
At the moment we evaluate both (TypeScript & ES6) because we like the benefit of a typed language (TypeScript) but want to be future proof (ES6).

First steps in TypeScript are made here:
- https://github.com/wireapp/bazinga64

We are also investigating on how to transition from "CoffeeScript" to "ES6" for our webapp. We might follow the approch of @kevinsawicki:
- https://github.com/electron/node-rcedit/pull/17

Stay tuned! :v:

**Comment by herrmannplatz** [comment]
#891
