### ISSUE TITLE
Chat rooms may encounter this problem when sending pictures.

### ISSUE THREAD

**Issue by baoxiao123** [wireapp/wire-webapp#6716]
The FetchEvent for url resulted in a network error response: the promise was rejected。
Pictures cannot be displayed。
‘/assets/v3/3-2-ef8afcee-f33a-4473-8b4..‘
linux  https Environmental Science，same area。
I don't understand why this problem arises.

**Comment by bennycode** [comment]
Thanks for reporting. Looks like the picture got deleted by the other party.
