### ISSUE TITLE
No error message on device remove password

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#673]
1. Choose Preferences → Devices
2. Click remove any active device
3. Type wrong password

Result: no error message on wrong password

**Comment by gregor** [comment]
Thank you very much for your report. We are aware of the usability issue created by not idicating an error in this case at all.

**Comment by aquatooth** [comment]
posting here because it deserves a BUMP being ~3months and a rather bad bug that should be worked on ahead of enhancements etc.

**Comment by bennycode** [comment]
@aquatooth We are aware of the situation and we track this in our internal system. Thanks! ✌️
