### ISSUE TITLE
Pictures are shown with wrong orientation

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-webapp#678]
Pictures sent by an Android Wire client seem to be shown always in landscape orientation assuming an upright position in the web client, disregarding orientation information on the picture itself. 

On my iPhone this very same images in the same conversation show up in the correct orientation,.

This doesn't seem to happen with images sent by an iPhone.

**Comment by mat1th** [comment]
I've the same issue with all android send pictures.

**Comment by gregor** [comment]
This issue has been addressed by our Android team.
