### ISSUE TITLE
URL with special chars gets markdown processing which breaks the link

### ISSUE THREAD

**Issue by kmisiunas** [wireapp/wire-webapp#6828]
## What steps will reproduce the problem?

1.  Send a link to anyone:
`https://stva.zh.ch/internet/sicherheitsdirektion/stva/de/StVAaw/AWumschreib/_jcr_content/contentPar/downloadlist/downloaditems/gesuch_umschreibung_.spooler.download.1558588990145.pdf/ZFO104AUSL201902.pdf`
2.  the `_` triggers Markdown and break the link 

## What is the expected result?

Expected result would be URL with clickable destination

## What is the actual result?

Actual results looks like this:
<img width="577" alt="Screenshot 2019-06-27 at 10 41 17" src="https://user-images.githubusercontent.com/4820843/60251060-200b3f80-98c8-11e9-8e6b-3cf5abee803d.png">

**Comment by lipis** [comment]
<img width="607" alt="Screenshot 2020-08-11 at 1 41 06 PM" src="https://user-images.githubusercontent.com/125676/89888245-4f6a3200-dbd8-11ea-9212-a86a71ac5847.png">

This if fixed already! Thanks for reporting.
