### ISSUE TITLE
Timed 4w messages broken

### ISSUE THREAD

**Issue by Fluffkin** [wireapp/wire-webapp#6836]
Wire version: 3.9.2895
Operating system: Linux/Gentoo

What steps will reproduce the problem?

1.  Set "Timed message" for 4 weeks, send a message
2.  I see "3 weeks 6 days", receiver sees "3 minutes 6 seconds"
3.  Timed message vanishes after about 4 to 5 minutes

What is the expected result?
Messages not being deleted for 4 weeks

What is the actual result?
"Why did you just set timed messages to 3 minutes?"
"I didn't! I set it to 4 weeks!"
<4 minutes later messages start to vanish>
"I told you so!"

**Comment by bennycode** [comment]
We have fixed the bug with our 4w message timer. On top of that we have implemented a feature so that you can set timers on conversation level:
