### ISSUE TITLE
Many audio bugs that seems related [Important]

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#6837]
- When switching audio source (mic) and making calls it doesn't ring on the other end.

- When receiving a call after changing audio source it ask to abort the current call before, there is no ongoing call, aborting it cause incoming call to be cancelled too.

- Feature request : Make audio source stick, especially microphones, I connect devices in and out like webcam and audio source keep switching to the wrong ones. (Maybe it could remember last selections and fail over to next most used)

**Comment by bennycode** [comment]
We improved the A/V selection in our app a lot. Thanks for reporting!
