### ISSUE TITLE
slow, delayed image loading on desktop client

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire-webapp#6840]
When images are received on the desktop client (electron), the desktop client either: 
1) doesn't load the image before focus is given to the application
2) the loading of the images are so slow that it takes multiple minutes. 

When I receive an image - it appears to only begin to load that image when i give the desktop client focus (click on it) .. then it takes around 1-2 minutes for that image to load. 

My question, suggestion, request is that the client load that image immediately, before I give the app focus. My workflow now is that I have to click the app, then move on to doing something else while that loads.

**Comment by lipis** [comment]
It seems that it is fixed now, the image appears right away!
