### ISSUE TITLE
Improve documentary around connections

### ISSUE THREAD

**Issue by supersexy** [wireapp/wire-webapp#6900]
Version: Personal
Tested this in Chromium and Firefox, Ubuntu 16.04, vie https://app.wire.com

It is not possible to add participants to an existing group. By clicking on the group name on top of the screen the group details flyout opens on the right site of the screen and there is an "Add participants" item, which after click creates another screen in that area with a big "ADD PARTICIPANTS" on top and a search box, but I can not manage to add any existing user to the group.

Note: it is not clearly documented anywhere on that screen, if one has to put @ before a username or not, however I tried with and without, but in any case no user will be added. The "ADD" button on bottom stays greyed out and pushing enter does not do anything. 

I am logged in with the user I want to invite in another browser window - none of them can invite the other one into any previously created group.

Wire looks cool, but chatting just to myself is a little bit boring, I really would like to invite other people, it is just more fun. :)

**Comment by supersexy** [comment]
OK, of course this happens **after** creating an issue: I just learned, that adding a user to a group seems to be only possible with accounts, that **I have to connect to before**. This was not clear to me and it was not documented anywhere. I am still not sure if that is really the case, so it would be very nice if you would like to confirm that.

_In any case, please add some info about any required actions users have to do to the "ADD PARTICIPANTS" screen - there is plenty of space above or below that search box. Thanks!_

I feel a little bit dumb that I spent too much time with that, but also I feel that this really should be documented - there is no way understanding that "of course" one has to first connect users and only then can add users to a group. Also the UI is misleading then - if it is not possible to add any users, because there are no connected users, then why is that part of the UI visible / accessible? Instead there should be some kind of dialog box / warning / info for the user that just says:

"To be able to add users to a group first you have to connect to users."

Of course a sane variation of that would be to avoid the extra step and generate user connection right from that "ADD PARTICIPANTS" screen.

**Comment by ffflorian** [comment]
Hi @supersexy,
in the free version you first have to connect to every participant you want to add to a group.
In the pro version you can add everyone who's in your team.

**Comment by bennycode** [comment]
Closing the issue because it got answered by Florian.
