### ISSUE TITLE
Content button → Soundcloud, YouTube missing

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#694]
Content button (just added) is missing YouTube and Soundcloud links, just WWW.

**Comment by gregor** [comment]
Currently the collection only contains links for which a link preview has been generated on the sender side. This will be changed at some point in the future.

**Comment by helenakos** [comment]
As @gregor mentioned, this will be improved in the future, but currently we don't have a committed date. Closing this issue for cleanup purposes. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
