### ISSUE TITLE
Web session is too short

### ISSUE THREAD

**Issue by keeferrourke** [wireapp/wire-webapp#6958]
## Wire for web version

`2019-07-11-13-18`

## Browser version

Firefox 67.0.4 64-bit

## Installed browser addons
 - uBlock Origin
 - NoScript (with all scripts allowed for app.wire.com)
 - HTTPS Everywhere
 - Privacy Possum

## Operating system

macOS Mojave

## What steps will reproduce the problem?

1.  Login to app.wire.com
2.  Change browser tabs
3.  Wait 15 minutes
4. Switch back to wire, discover logged out

## What is the expected result?

Session should not expire so often. 

## What is the actual result?

Session has expired and I need to log back in to see new messages. This takes a while because they have to decrypted again.

**Comment by R4m4n** [comment]
I'm also getting the same issue. I think it's because of the 
`MissingCookieError: Authentication failed because the cookie is missing.`.
I'm also looking for a solution.

**Comment by lipis** [comment]
Is that still an issue? We can't reproduce it. Please write back if you still experiencing it.
