### ISSUE TITLE
Link with markdown wrong

### ISSUE THREAD

**Issue by sokke90** [wireapp/wire-webapp#6973]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Windows 10

1.  Send link like `[test](google.de)`
2.  browser wants to open https://app.wire.com/google.de -  Working fine on iOS.

## What is the expected result?

go to http://google.de

## What is the actual result?

going to https://app.wire.com/google.de

**Comment by ffflorian** [comment]
@sokke90 you are using markdown wrong.
You should use

```markdown
[test](http://google.de)
```
