### ISSUE TITLE
Wire conversation not updating on multiple devices

### ISSUE THREAD

**Issue by GenerallyDisjointed** [wireapp/wire-webapp#7011]
My first ever issue report, hope I do it right

Running wire web app via chromium on linux (ubuntu xenial), and concurrently running wire on my android phone (3.34.789).

I log out of web app, unable to receive messages from person, reboot phone and then they start coming through
 
Desktop app receives messages, android app doesn't. All devices have been verified.

**Comment by ffflorian** [comment]
@purpleden sorry I am a bit confused about where you receive messages at which point. Can you please write down the exact steps leading up to your problem? That would help us a lot!

**Comment by GenerallyDisjointed** [comment]
Apologies!

I log into the wire web app.
Start a conversation (works fine)
I start Wire on my Android phone
Verify all devices
Conversation from that point on does not concurrently update on android phone

**Comment by ffflorian** [comment]
1. So it is an Android bug?
2. Do you have the Android app open or closed?
3. Did you try sending a message from the webapp to the webapp (maybe from another computer?)

**Comment by GenerallyDisjointed** [comment]
1) It appears to be so
2) The Wire android app is open on front screen
3) Yes, does not update unless I restart the phone. Restarting the android app does not work

**Comment by ffflorian** [comment]
This should be in the [Android issues](https://github.com/wireapp/wire-android/issues) then :)
Can you please create the issue there? Unfortunately I'm not able to transfer your issue.
