### ISSUE TITLE
[Web] Cannot retry sending failed sent messages

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#7013]
Version 3.0.2828
Wire for Web Version 2018.02.01.1026
Operating system: Windows 10 x64

What steps will reproduce the problem?
1. Have a failed sending message

What is the expected result?
- be able to retry

What is the actual result?
- message is grayed and cannot resend it

![cap](https://user-images.githubusercontent.com/1250795/35856540-9f760104-0b36-11e8-93e2-fa1f8265020b.png)

**Comment by chriseomi** [comment]
> ![image](https://user-images.githubusercontent.com/388716/57102378-5d50b800-6cf1-11e9-8a65-de51fbed5da2.png)

I'm having them same issue now out the blue. Never had it before. Weird.

**Comment by chriseomi** [comment]
This is now happening 100% of the time reproducibly. Basically on a fresh start of Wire, message sending works fine, but after about 10 minutes I will switch back to Wire and then new messages will become gray and refuse to send. Restarting Wire fixes it for another 10 minutes or so.

Running Wire 3.10.3133 on macOS Catalina 10.5.3

**Comment by bennycode** [comment]
We don't plan to add a "Retry" button. Instead we will make our code more reliable so that it automatically retries to send unsent messages once your network connection recovers.
