### ISSUE TITLE
[Web] Can't go from once conversation to another without moving around a cursor.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#7017]
CTRL-N moves me to search but I don't see how to select the result of the search without reaching to the mouse.

Also if search is already open, opening the search again with CTRL-N should bring your cursor to the search.

If you want to compete with other collaboration tools this is needed.

**Comment by bennycode** [comment]
You can now switch conversations with the following hotkeys:

![image](https://user-images.githubusercontent.com/469989/89887247-39f00a80-dbce-11ea-98a5-651d77030adb.png)

**Comment by Transisto** [comment]
Please reopen and rename title to:

"Feature, select a user search result with keyboard."
