### ISSUE TITLE
[Web] fullscreen view for shared images/videos

### ISSUE THREAD

**Issue by vith** [wireapp/wire-webapp#7019]
Shared images can be clicked on to open a slightly larger view (although lacking fullscreen), but video playback is only available in the tiny default size. A fullscreen button for both would be great.

**Comment by bennycode** [comment]
Hi @vith, unfortunately we cannot provide fullscreen view for media embeds like YouTube videos because such embeds don't provide this feature for external apps.

From [YouTube's fullscreen FAQ](https://support.google.com/youtube/answer/72689):

> If full screen mode isn't working
> If you’re watching videos on websites other than YouTube, the option to use full screen mode may be turned off.

**Comment by vith** [comment]
Sorry, I should have been more specific. I meant for media directly shared through Wire.
