### ISSUE TITLE
[Web] Mic auto-adjust pushes volume too high

### ISSUE THREAD

**Issue by sebnarvaez** [wireapp/wire-webapp#7025]
Wire version: 3.9.2895
Operating system: Arch Linux

What steps will reproduce the problem?

1.  Start a video-call
2.  Talk through the internal laptop mic
3.  After a few seconds of talking, the volume of the mic is auto-adjusted, but it's pushed way too high, making clipping noises. When manually adjusted, the volume is auto-adjusted again, and there's no way to disable this.

I think this is actually a chromium issue, which uses WebRTC to adjust the mic's volume, but isn't there a way to just disable that feature for the Wire distribution?

**Comment by bennycode** [comment]
@sebnarvaez we disablaed auto gain control (AGC) with [this PR](https://github.com/wireapp/wire-webapp/pull/9443). It will go live with our next release.

**Comment by sebnarvaez** [comment]
Thank you!
