### ISSUE TITLE
Microphone selection not working

### ISSUE THREAD

**Issue by nijel** [wireapp/wire-webapp#7083]
## Wire for web version

2019-07-11-13-18

## Browser version

Tested in two browsers:

* Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
* Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36

## Installed browser addons

Bitwarden

## Operating system

Debian Linux

## What steps will reproduce the problem?

1. Ensure microphone access is allowed in the browser.
2.  Open audio preferences
3.  See the microphone selection is disabled

## What is the expected result?

The microphone selection should work.

## What is the actual result?

Microphone selection is disabled. The audio devices are however listed, but it's not possible to choose one.

Settings on Chrome:

![app wire com_](https://user-images.githubusercontent.com/212189/62768450-2bd94c80-ba97-11e9-9642-47932316bb03.png)

Settings on Firefox:

![Screenshot_2019-08-09 Wire · The most secure collaboration platform](https://user-images.githubusercontent.com/212189/62768181-9dfd6180-ba96-11e9-89d3-2f3205b56ac9.png)

The "Default" device has no actual microphone, so audio calls do not work with it. In case I enable the select by modifying the HTML code, the microphone selection seems to work and I'm then able to make the audio calls. So it seems that just the configuration UI is confused for some reason. The Firefox screenshot shows the settings after making such change - the audio device has been changed and audio calls work.

**Comment by bennycode** [comment]
We improved the A/V selection a lot! Please give it another try. :)

**Comment by nijel** [comment]
Thanks, seems to work fine now.
