### ISSUE TITLE
Aliases for contacts

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-webapp#7122]
Because some people set stupid names or nicknames when registering so you have no idea who they are.

And it also makes sense in other means, like adding what company the contact belongs to 
(Would be better handled with Groups though).

**Comment by ffflorian** [comment]
@europ there are no updates as of now. Anyway, I re-opened this for better visibility.

**Comment by larcenou** [comment]
> @tmikaeld We will work on improving the whole naming area soon. Hold on tight.

holding on tight ist starting to hurt after 3 years.

**Comment by Sledge-Hammer** [comment]
Actually that would be a terrible feature to have.
Not everyone wants their name used over the Internet and the lack of contact renaming is so far one the best features of Wire.
If you add something like that at the very least each person should have the option to allow whether others can rename them or not...

**Comment by pinta83** [comment]
> @tmikaeld We will work on improving the whole naming area soon. Hold on tight.

bump..... 4 years, no progress? :(

**Comment by bennycode** [comment]
> > @tmikaeld We will work on improving the whole naming area soon. Hold on tight.
> 
> bump..... 4 years, no progress? :(

We don't plan to build this feature anytime soon.

**Comment by nidico** [comment]
FYI, here's the spec proposal solving the same issue in Matrix: matrix-org/matrix-doc#3015
