### ISSUE TITLE
Syntax highlighting in Dark theme is often unreadable

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#7123]
Wire Desktop 3.9.2895
Arch Linux

## What steps will reproduce the problem?

1. Switch to Dark theme
1. Send the following message:

````
CSS:

```
li:nth-child(3n)::before {
  content:'Fizz';
}
li:nth-child(5n)::after {
  content:'Buzz';
}
```

Python:

```
def main():
    print "hello world"
```
````

## What is the expected result?

Syntax highlighting is readable

## What is the actual result?

Dark-blue and grey are not readable:

![image](https://user-images.githubusercontent.com/1177900/63159960-eaa7e600-c01c-11e9-9938-2d2696faea24.png)

**Comment by lipis** [comment]
We should use solarized 
https://ethanschoonover.com/solarized/

**Comment by odiferousmint** [comment]
Or better yet, support multiple color themes! Personally I like `monokai`.

**Comment by lipis** [comment]
<img width="483" alt="Screenshot 2020-08-11 at 1 06 58 PM" src="https://user-images.githubusercontent.com/125676/89885300-8b4ec880-dbd3-11ea-9972-860e1e9d9010.png">

Should be fixed now!
