### ISSUE TITLE
Cannot send singular emoji character from Firefox

### ISSUE THREAD

**Issue by Caspy7** [wireapp/wire-webapp#717]
When I paste one emoji into the text entry line and hit enter it will not send.

Adding a space allows it to send.

This is the behavior in Firefox. Chrome seems to work (though its emoji set stinks on my computer :).

**Comment by ffflorian** [comment]
@Caspy7 Sorry, I can't reproduce this.
Did something appear in the console when you tried sending? From where did you copy the Emoji? And which OS / which Firefox version are you using?

**Comment by gregor** [comment]
We have been unable to reproduce this issue internally to this date. Thus I am going head and closing it for now.

**Comment by Caspy7** [comment]
The issue, I believe, is that I'm using a browser extension to easily send emojis straight to the text box.
I just tested and found that pasting them works, but when they're sent straight to the text box it's not registering a new character apparently so it thinks there's no text there.
I don't know exactly who to "blame" here :)

**Comment by gregor** [comment]
@Caspy7 Sounds like an incompatibility between the extension you use (which one?) and Knockout. If the text is updated without it registering the paste we will fail to send the message as we still believe the input is empty. I am not sure which events Knockout binds to in this case.

**Comment by Caspy7** [comment]
Emoji Keyboard
https://addons.mozilla.org/en-US/firefox/addon/emojikeyboard/

**Comment by bennycode** [comment]
Hi @Caspy7, we are sorry to hear that your Emoji Keyboard Firefox extension is incompatible with Wire. As a workaround we recommend you to use the emoji keyboard of your operating system.
