### ISSUE TITLE
emoji picker rendering issues on macOS Catalina

### ISSUE THREAD

**Issue by mattieb** [wireapp/wire-webapp#7210]
The emoji picker is corrupted on macOS Catalina 10.15 Beta (19A546d) for some sequences (guessing they're combining sequences?)

![image](https://user-images.githubusercontent.com/56017/64037215-0e8e2000-cb23-11e9-978d-5447bf705b89.png)

**Comment by max-baz** [comment]
This is fixed in https://github.com/wireapp/wire-webapp/pull/7314
