### ISSUE TITLE
Web App fails to load in Firefox Nightly when WebRTC is disabled

### ISSUE THREAD

**Issue by nitrohorse** [wireapp/wire-webapp#7232]
## Wire for web version

[Version 2019-09-02-10-32](https://medium.com/wire-news/wire-for-web-2019-09-02-f45c845aa48c)

## Browser version

Firefox Nightly:
- `Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0`

## Installed browser addons

None (tested in incognito mode)

## Operating system

Linux

## What steps will reproduce the problem?

1. Open Firefox's `about:config` page.
1. Set `media.peerconnection.enabled` to `false`
1. Navigate to https://app.wire.com/

## What is the expected result?

Web app loads.

## What is the actual result?

![wire2](https://user-images.githubusercontent.com/1514352/64135515-c5ff8c80-cdd8-11e9-9d90-4e79fb249589.png)

Looks like the issue stems from [this commit](https://github.com/wireapp/wire-webapp/commit/d687a6b08c70dc9afaca11c112cd06ec03fdbd00) - https://github.com/wireapp/wire-webapp/blob/dev/src/script/media/MediaStreamHandler.ts#L61.

**Comment by atomrc** [comment]
Hi @nitrohorse 

Thanks for the report. This bug has been fixed recently and will be out with the next release of the app. (https://github.com/wireapp/wire-webapp/pull/7270/files)

Have a great day.
