### ISSUE TITLE
Lastpass password manager missing checkbox

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-webapp#726]
This is a continuation of the recent issue  #614.

The current web app (Version 2017-02-03) is now working nicely with Laspass, with just one minor exception. This is not a big problem, but let me document it anyway.

This is on Google Chrome using the Lastpass extension.

Lastpass in automatic login mode (Note 1) will not only fill in the login and password fields, but also check any desired checkboxes, before it completes the login. Additional fields including checkboxes can be specified by using Lastpass's option to "Save All Entered Data".

However, even if I specify that the checkbox with the label "checkbox-remember-password" (which corresponds to the checkbox called "REMEMBER ME" on the screen) is to be checked, it remains unchecked as the login completes.

As a result, when the user does an automatic login using Lastpass, Wire enters the temporary use mode, in which old conversations will not be seen, and new conversations will not be saved.

The reason this is not a big problem is that the user need only log out, which puts Lastpass into manual mode (Note 2), click on the Lastpass menu to make it fill in the login and password fields, then manually check the "REMEMBER ME" checkbox, then manually click on the "LOG IN" button. And old conversations previously saved are now visible again.

But it would still be nice to be able to do an automatic login and still see old conversations and save new ones.

After doing a brief "view source" I am unable to tell if this is a Lastpass issue, or if there is something in Wire's HTML or JavaScript that causes Lastpass to be unable to check that checkbox.

━━━━━━━━
Note 1. If you are not currently at the desired website, Lastpass will make a new web browser tab, visit the desired website, fill in all desired fields, and click on the login button. So in most cases login completes automatically.

Note 2. If you are already at the desired website, Lastpass will only fill in the desired fields, but not click on the log in button. The user now may fill in additional fields as needed and then click the login button manually.

**Comment by bennycode** [comment]
@fortran77, do you still have this problem? I am not using Lastpass but Wire works well with my 1Password extension.

**Comment by fortran77** [comment]
I ended up using Wire messenger inside a Rambox window, which preserves the login across machine reboots. So I never see the login any more.

There are a couple of other problems though that are relevant here. Failure of voice calls to ring on Android devices, and notifications of text messages not appearing on Android devices, have been reported in other places in this issue tracker. After many experiments I have been unable to work around these problems, even after several generations of device updates. All the other voice apps (Google Duo, Skype, WhatsApp, Telegram) exhibit none of these symptoms. 

Also there were intermittent problems with voice calls going silent for a while (and neither any comfort noise or lack thereof to notify the user of the call going silent, nor any fast beeps to replace lack of comfort noise). Again, not a problem that seems to occur with the other apps listed above.

But the intermittent silence problem is relatively moot, if voice calls don't ring in the first place.

I would have submitted debugging logs for voice calls. But if the voice call never rings, then there is no active voice call, and no debugging log.

These are all Wire-specific that do not occur with the other apps listed above. They affected both me and those I correspond with.

So I ended up using Wire less and less until I use it almost not at all.

As a result I think it's safe to assume any any missing checkbox is either fixed or if not fixed doesn't really affect me. :-)

**Comment by fortran77** [comment]
Here is a trivial fix for all problems related to password managers. Provide a separate login page for use with password managers. Use simple HTML, no style sheets, no JavaScript. Just the bare minimum of a form with fields. Use standard names for all fields. Exercise no creativity in designing that page. If options such as remember me are needed, maybe provide distinct web pages instead of such a check box.

**Comment by bennycode** [comment]
Prefill works with [Google Password Manager](https://passwords.google.com/) and [1Password](https://1password.com/), so the bug seems to be on [Lastpass](https://www.lastpass.com/).
