### ISSUE TITLE
Link to "WHY VERIFY CONVERSATIONS?" is dead end

### ISSUE THREAD

**Issue by Filbuntu** [wireapp/wire-webapp#7263]
Wire Desktop Version 3.10.2904 (Ubuntu 19.04)
Easy bug to fix (I guess): In the menu `Devices`: There is a link to "WHY VERIFY CONVERSATIONS?": [https://wire.com/privacy/why/](https://wire.com/privacy/why/) but this is a dead end "Sorry, unable to find the page."

Please change the link to the right address, e.g. https://support.wire.com/hc/en-us/articles/207859815-Why-should-I-verify-my-conversations-
Non-convinced users might think Wire is not professional if they are not directed to the right page and I still hope many will continue to join Wire. Thanks!

**Comment by ffflorian** [comment]
Hi @Filbuntu, thanks for the report! The link should be fixed now.

**Comment by Filbuntu** [comment]
@ffflorian Yes, it does! Thanks for the quick fix!
