### ISSUE TITLE
Feature request → Liked messages collection

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#727]
Add liked messages to collection (top-left icon in conversation), so they are easily accessible.

Thanks in advance.

**Comment by lipis** [comment]
I like this one :)

**Comment by helenakos** [comment]
Such a great idea. Only closing due to clean up purposes. We have noted it down internally. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
