### ISSUE TITLE
Design feedback: colorful names in conversations

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#728]
I think it was a great idea to add color to the user names in conversation view, I quickly got used to use color to distinguish which messages are mine, and which are not.

Except that this concept doesn't work when both me and my contact use the same color. In these cases I have to fallback and actually carefully read sender's name to distinguish messages.

My feedback is therefore to avoid situations where the color of my messages is exactly the same as color of someone else. If my color is blue, and I chat with a person whose color is also blue, can we detect this and perhaps change their color to something else, only on my side? That is, if we make "brown" as a fallback color, then I will see my messages as blue and their messages as brown, while they will see their messages as blue and my messages as brown.

**Comment by mohammadrafigh** [comment]
I agree with you about colors, but the problem with changing other's colors is when you are in a group conversation and there are 100 people in the conversation, then it's very likely to have 10 peoples with your own color. so changing to a different color causes all those 10 people be in brown and it's still difficult to distinguish them.
but if the problem only is distinguishing your messages against others then making the name a bit bolder or putting an icon or symbol in front of your message/name works better this way you can still see the real colors from others.

**Comment by gregor** [comment]
@maximbaz Thanks again for your feedback. Our design people are aware of it and will consider it when updating the product UI. There is no current plan to implement a change in this specific area. I will close this issue for now for house keeping reasons.
