### ISSUE TITLE
No preview for links in web version in Firefox

### ISSUE THREAD

**Issue by Crandel** [wireapp/wire-webapp#7286]
## Wire for web version
 2019-09-02-10-32 

## Browser version
Firefox 69

## Installed browser addons
uBlock Origin, Stylus, Three Style Tab

## Operating system
Arch Linux
## What steps will reproduce the problem?

1.  Send link to chat

## What is the expected result?
View a preview of link
## What is the actual result?
Url of site

If I edit this url in mobile version later I have a preview for this link

**Comment by bennycode** [comment]
Link previews are not possible in our web app due to CORS issues because our webapp is not allowed to fetch remote content.
