### ISSUE TITLE
Whitelist Pale Moon browser

### ISSUE THREAD

**Issue by b9AcE** [wireapp/wire-webapp#7333]
Currently when using the [Pale Moon web browser](http://www.palemoon.org/), to access "[Wire for web](https://app.wire.com/)" one is just told to use one of the big four browsers, but if one uses the builtin functionality to report a different HTTP User Agent to that specific site, such as the current UA for Firefox, the page works just fine.
Therefore it seems reasonable to whitelist this browser, or possibly some sort of "grraylist" whereby you could inform the user that "Pale Moon is not a web browser actively targeted for Wire development, but you can attempt using it unsupported" or similar.

**Comment by bennycode** [comment]
Good idea. Can you tell us the user agent of your browser? You can check it on: http://whatsmyuseragent.org/

**Comment by b9AcE** [comment]
Yes.

As mentioned, Pale Moon has in its default preferences (native, not through plug-in/extension) an option to switch between three "User Agent Mode" settings, which gives three different results and I will list all three of those.
I decided to provide those from a Windows machine, as I think that may be the most common case, but you will easily spot which parts of the strings would be best to actually test for.

"Native":
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:4.6) Goanna/20200731 PaleMoon/28.12.0

"Gecko Compatibility":
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.9) Gecko/20100101 Goanna/4.6 PaleMoon/28.12.0

"Firefox Compatibility":
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.9) Gecko/20100101 Goanna/4.6 Firefox/68.9 PaleMoon/28.12.0

**Comment by bennycode** [comment]
Thanks for sharing your user agent with us. I see the problem that you are facing. Luckily your browser provides a "Firefox Compatibility" mode for this reason. 

It's a lot of work to provide support for all browsers and when allowing browsers we haven't tested ourselves, the risk is high that Wire won't work as expected. To not raise the potential of delivering such broken expierence we have decided to be very strict about the browsers we support. 

After checking with our product management, we have decided to not add PaleMoon to the list of exceptions but we might change from a browser name/version filter to a browser feature/support filter.

**Comment by b9AcE** [comment]
Did you also ask about the second part of the feature request @bennyn?
The part about a potential "grraylist", as described in my original post?
I did not expect you would whitelist Pale Moon for the reason you described, but thought the grraylist concept could open up to more users with many other browsers too, while not adding to your administrative load nor losing reputation for poor functionality if a user actively has to accept that there may be compatibility issues each time before they use the Wire WebApp with a browser on such a grraylist...
