### ISSUE TITLE
How can we seperate  the sender's message queue from the recipient message queue?

### ISSUE THREAD

**Issue by nishat-techindustan** [wireapp/wire-webapp#7401]
Is there any approach to separate the sender's message queue and recipient message queue inside the code. I 've been trying to change the format in the stylesheet but it seems like the styling has effect only in the overall layout of the page. Can someone please tell me how to isolate them inside the code.

**Comment by nishat-techindustan** [comment]
I really need this kind of UI functionality. Is there anything you guys can help me out with.
Any help would be appreciated.

**Comment by bennycode** [comment]
Hi @nishat-techindustan, am I reading it correctly that you just want to change the design in your local frontend?

**Comment by bennycode** [comment]
Closing this ticket because I got no response.
