### ISSUE TITLE
Inconstistant markdown rendering on web vs android/ios

### ISSUE THREAD

**Issue by alaviss** [wireapp/wire-webapp#7403]
## Wire for web version
2019-09-24-11-57

## Browser version
Firefox 69.0.1

## Installed browser addons
uBlock Origin
uMatrix

## Operating system
Gentoo Linux amd64

## What steps will reproduce the problem?

1.  Send a message with the content: `\***action**\*`

## What is the expected result?
Both versions render: \***action**\*

## What is the actual result?

Android/iOS renders: \***action**\*
Web version renders: *\\**action**\\*

**Comment by Wurzelkoch** [comment]
~~Duplicate of #5072, isn't it?~~

**Comment by alaviss** [comment]
I'm not sure if that PR is even related

**Comment by Wurzelkoch** [comment]
I think I wanted to link to another issue, not a PR… 
Maybe cross-repository and that's where it was confused.

Anyways, the problem is still there.

**Comment by bennycode** [comment]
Hi @alaviss, there is a plan to align the different Markups. Can you tell me what's the most annoying difference in our Markdown rendering for you at the moment?

**Comment by alaviss** [comment]
Off the top of my head:

- The bug described in this issue.
- Quote blocks (`> quote here`) are not rendered on Web (shows up as "> quote here"), while Android/iOS uses proper markup like this:
  
  > quote here
- Code blocks (triple backticks) always have syntax highlighting on Web, but not on the Android/iOS app.

**Comment by Wurzelkoch** [comment]
* numbered lists only appear as such in android, not in web. This led to a misunderstanding when I was sent a list of dates in German format (D. Month). To the sender, who used web, they appeared as sent, to me, on android, they appeared as consecutive days.

**Comment by bennycode** [comment]
> This led to a misunderstanding when I was sent a list of dates in German format (D. Month).

Can you provide a specific text example? I have tried sending this (but it showed up normal on Web and Android):

```
01.11
17.11
30.11
```

**Comment by Wurzelkoch** [comment]
This was the very list that had me finding this problem:
```
7. November
10. November
21. November
```
Shows normal in web and in notifications on android (lineage if that's relevant), but shows
```
7. November
8. November
9. November
```
in android app.

**Comment by alaviss** [comment]
There's more than that list issue in this issue FWIW.
