### ISSUE TITLE
Please support Push-notifications

### ISSUE THREAD

**Issue by szaimen** [wireapp/wire-webapp#7458]
Please support Push-notifications, so that I get notifications also when the wire-webapp isn't open in a tab or the browser is completely closed.

**Comment by bennycode** [comment]
@szaimen are you referring to Chrome's [Push API](https://caniuse.com/#feat=push-api)?

**Comment by szaimen** [comment]
> @szaimen are you referring to Chrome's [Push API](https://caniuse.com/#feat=push-api)?

Yes 👍

**Comment by bennycode** [comment]
It will take a long time for us to adopt to Chrome's Push API but our backend team is [keeping track of that](https://github.com/zinfra/backend-issues/issues/864). In the meantime we recommend to use our desktop apps to get notified about incoming messages while our app runs in the background.

**Comment by szaimen** [comment]
Hi @bennyn thanks for your reply!
Could you please send the link again? It doesn't seem to work...

**Comment by szaimen** [comment]
@bennyn Do you have the correct link for me?
