### ISSUE TITLE
Browser extension request

### ISSUE THREAD

**Issue by erotavlasme** [wireapp/wire-webapp#7484]
Hi,
please in order to enhance security and speed of wire web app it would be good to have a browser extension (firefox and chromium based browser). This will allow to run the app locally and avoid to download javascript, HTML and CSS from wire servers via HTTPS every time. Moreover, the browser extension updates can be protected by cryptography.

**Comment by bennycode** [comment]
Hi @erotavlasme, we are planning to deliver our JavaScript code from within our desktop application. We have since plan for a while and it will take us some more time to establish it but we will get there.

**Comment by erotavlasme** [comment]
Hi @bennyn, so will it be necessary to download the desktop app? And will it install the extension?
