### ISSUE TITLE
https://app.wire.com/ returns 0 byte content and 503 Status

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-webapp#749]
date +%s; curl https://app.wire.com/ -D-
1486757931
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Content-Length: 0
Connection: keep-alive

**Comment by herrmannplatz** [comment]
Thanks, we are on it.

**Comment by herrmannplatz** [comment]
should be fine now.
