### ISSUE TITLE
Licensing issues.

### ISSUE THREAD

**Issue by lwatsondev** [wireapp/wire-webapp#751]
Each Wire client's repo is apparently licensed under the GPL, yet the README states "All Open Source Apps are subject to, and may only be used and/or commercialized in accordance with, the Terms of Use applicable to the Wire Application", and then lists said restrictions.

The problem is, the [The GNU GPL is designed specifically to prevent the addition of further restrictions](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary). In other words, the terms dictated in the README are incompatible with your license. You **cannot** impose restrictions on anyone regarding use of your open source code without invalidating the GPL. You can have restrictions or ToS on your servers and service (which is what I think was intended here), but you cannot dictate what people do with the software itself.

There are 2 solutions to this problem, as I see it:

1. Stop using the GPL. Switch to a license that allows your additional restrictions. This would make Wire non-free software, but allows whatever restrictions the devs want.
2. Completely remove the entire section about terms of use from the README and put them in the terms of usage for the **service**, not the clients. You seem to want the ability to control which clients use your servers which is a terms of service issue, not a licensing one. Right now, you're essentially trying to implement server-side restrictions, client-side. This is obviously not going to ever work.

**Comment by raphaelrobert** [comment]
We do not impose restrictions on the clients. These restrictions apply to the service. The section you quoted is indeed from our Terms of Use ([wire.com/legal, section 6.4](https://wire.com/en/legal/#apps-use-requirements)).
We repeated them in the README file, because sometimes users don't read the Terms of Use. 😉
