### ISSUE TITLE
Feature request: make local video in a video call resizable

### ISSUE THREAD

**Issue by Ditti4** [wireapp/wire-webapp#752]
The local video preview box in a video calling is rather tiny. It would be awesome if it was possible to resize that element so you can actually see what you're doing, like holding up your phone so you can show the other person something on its screen.

I've played around with `resize: both` and `overflow: auto` in the web app but I couldn't get it working in a satisfying way (thinking of something like Skype has).

**Comment by helenakos** [comment]
Thanks for the request. I will close because we don't have resources to work on this immediately, but are not excluding it for the future. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
