### ISSUE TITLE
Total loss of history due to Chrome browser update

### ISSUE THREAD

**Issue by dietmarw** [wireapp/wire-webapp#753]
Hi, 
I've just got my web-wireapp reset with a new id just because the browser (Chrome on Linux) got updated to a newer version. This is of course something  that happens frequently and it is really annoying to loose all of the chat history (and attachments) on the same browser. A browser update should not trigger a new wire id.

**Comment by gregor** [comment]
We have not been able to reproduce history loss on browser updates. I am closing this for now. If you reencounter the problem, please open a new issue and with more information on your browser setup (versions involved in the update) and other information that can potentially help us to reproduce the issue.
