### ISSUE TITLE
Long audio lag/delay on audio i'm sending with web app.wire.com on Firefox/Linux

### ISSUE THREAD

**Issue by pasikarkkainen** [wireapp/wire-webapp#764]
Randomly, but quite often, app.wire.com web audio call gets messed up, and for some reason LONG audio delay is introduced to audio I'm sending.. others will hear me 10-30 seconds later, so it obviously makes discussions impossible. I'm hearing others "in real time", but others will hear me much later.

I have no idea how/why this happens, but it seems to happen quite often, and it's super annoying.

Currently I'm using Fedora 24, with the stock firefox-51.0.1-2.fc24.x86_64. Pulseaudio is in use (default setting), if that matters.

Any thoughts how to debug/fix this?

Thanks.

**Comment by pasikarkkainen** [comment]
It seems the native wire app (wire-2.11.2685-x86_64.AppImage) works better, and does *not* have this audio lag problem. So it's only the web app that's buggy.

**Comment by gregor** [comment]
The webRTC implementations on Chrome and Firefox are still not fully aligned. The issue you are describing are out of our reach but lie within those implementations within the browser. Our desktop app is build on electron which internally uses Chrome. Thus the experience can divert and be better compared to Fedora build on Firefox.
