### ISSUE TITLE
.webm (oggvorbis) clips are not shown in own client when drag&dropped.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-webapp#7655]
I already submitted this issue a year ago, so the devs should actually know it. But it is still a problem in the latest versions and I wonder why it couldn't get fixed:

to reproduce:
- drag & drop a small .webm into the client to send it so someone.

what happens?
- the file gets send correctly, the receiver can see the video clip.
- the sender himself gets a video-placeholder symbol in the conversation, the video is neither showing a preview nor is it loadable.

how should it be?
- the sender should be able to see a video preview in the conversation and should be able to load/play it - just like the receiver.

video-file and codec details:
Video: VP80 640x640 30fps [V: vp8, yuv420p, 640x640 [default]] 13secs, 645kb.

If i repeat the same with an h264 encoded .mp4 file it is working. so the problem seems to be webm related.

**Comment by bennycode** [comment]
Hi @tokariu, can you provide a sample file which we can use for testing?

**Comment by bennycode** [comment]
I am closing this ticket because I have not received a sample file for testing.
