### ISSUE TITLE
Web app opened twice --> "A MESSAGE FROM ... WAS NOT RECEIVED"

### ISSUE THREAD

**Issue by Acromonkey** [wireapp/wire-webapp#772]
I am using Wire as a web app in Chromium on my Linux Mint PC. When I accidently open the Wire app twice, I can normally chat in the secondly opened chat window, but in the firstly opened chat windows I will see messages like

"A MESSAGE FROM XXX WAS NOT RECEIVED. (ERROR: 8550)"

You find the detailed error messages in the attached image.

I don't think, that this kind of behavious is intended, because it is very confusing for the user. Especially after I closed the secondly opened chat window, I continued receiving these error messages. They stop appearing when I click on "RESET SESSION".

![wire](https://cloud.githubusercontent.com/assets/19237773/23042724/fe75f7fe-f499-11e6-8e34-43b71f0fb6d6.png)

**Comment by gregor** [comment]
Opening the app in two seperate tabs is going to lead to major issues with message decryption, access tokens and more due to the shared resources within the browser. We could definitely do a better job by preventing users from using the app on multiple tabs within the same browser though.

**Comment by helenakos** [comment]
Thanks for opening the issue and reporting. Closing this issue for cleanup purposes. Please let us know if you see these messages again.
