### ISSUE TITLE
Allow large file uploads when endpoints communicate directly

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-webapp#773]
The security whitepaper says: “Whenever possible the endpoints allow direct media flow between them.”

I don't know what fraction of the time Wire is able to punch through NAT.  When it can, the 25 MB file size limit for uploads should be increased, to hundreds of megabytes, even gigabytes. it would be so convenient to be able to easily send a big file to a remote correspondent.

(This applies to all types of end-points, whether web-app or smartphone/tablet or desktop.)

**Comment by helenakos** [comment]
@fortran77 Thanks for your request. We don't have plans to implement this at the moment, however we are planning on how to offer larger storage and file sharing options in the future, so please stay tuned. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
