### ISSUE TITLE
Emojis with modifiers aren't being listed and sent properly

### ISSUE THREAD

**Issue by BobbyWibowo** [wireapp/wire-webapp#7762]
**Wire version:** 3.11.2912
**Wire for web version:** 2019.11.21.1104
**Applicable on:**
Desktop app on KDE neon 5.17.3 User Edition (Ubuntu 18.04)
Web version on Firefox 70.0.1 (KDE neon)
Desktop app on Windows 10

**What steps will reproduce the problem?**

1. Write `:kiss` in chat input to show a list of emojis whose description contain the string "kiss"
2. Look at the suggestion results

**What is the actual result?**

![Screenshot](https://i.fiery.me/wt0Y.png) ![Screenshot](https://i.fiery.me/5hXF.png) ![Screenshot](https://i.fiery.me/OJcK.png)
From left to right: Desktop app on KDE neon, Web version on Firefox, Desktop app on Windows

**What is the expected result?**

Something like this, I guess?

![Screenshot](https://i.fiery.me/U2pt.png)

**Additional info**

The emojis will also be sent as they appeared on the suggestions list.
That is, the first row in the screenshot below, instead of the second one:

![Screenshot](https://i.fiery.me/UevH.png)

**Comment by bennycode** [comment]
Thanks for the report. It's working now:

![image](https://user-images.githubusercontent.com/469989/90251647-6611c280-de3e-11ea-9d26-2be2631a1694.png)
