### ISSUE TITLE
Bug: The sound bar in a audio message is not center alined. 

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-webapp#780]
When I send a audio file the Wire web app renders the sound a sound bar. This bar is not centered aligned. I think this is a bug.  See the screenshot for the way I'm seeing the bars.

**Comment by helenakos** [comment]
@mat1th I can reproduce, thanks. Will open an issue internally.

**Comment by gregor** [comment]
This is no longer reproducible with a new internal desktop release that should find your way soon. Thereby closing this.
