### ISSUE TITLE
Error message links "Why" to page with 404

### ISSUE THREAD

**Issue by strypey** [wireapp/wire-webapp#7812]
## Installed browser addons

* uBlock Origin 1.24.2
* NoScript 11.0.10rc1

## What steps will reproduce the problem?

1. Produce an error state where a message is not displayed and instead says "A message from [USERNAME] was not received. Why?"
2. Click on the green "Why?" text linked to  https://wire.com/en/privacy/error-1/

## What is the expected result?

Information about the error resulting in messages failing to sync between verified devices.

## What is the actual result?

A new browser tab/ window is opened with an error message saying "ERROR 404 Page not found"

**Comment by ffflorian** [comment]
This should be fixed now.
