### ISSUE TITLE
Website link broken

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#7832]
I didn't know where to make that issue, Thanks to whoever forward this to the right place/person.

When Clicking 

![image](https://user-images.githubusercontent.com/388716/69886467-15f2d000-12b0-11ea-9b39-f29338f55a31.png)
(Desktop and most likely other platforms.)

it sends to a broken 404 link `https://wire.com/en/privacy/why/`

**Comment by tiago-loureiro** [comment]
Hi @Transisto - thanks for reporting. @ffflorian will look into this.

**Comment by ffflorian** [comment]
This should be fixed now.
