### ISSUE TITLE
Call breakup on bad connections

### ISSUE THREAD

**Issue by tdw546** [wireapp/wire-webapp#7845]
Wire seems to be the least resiliant protocol when it comes to audio chat connections.
Whenever one participent in an audio call has a short connections issue (less then a second) the call breaks up immediatly. The symptoms are the usual wire "reconnecting" signal which can be heard by the remaining participants. However after using wire for more then a year now every week, I have yet to experience wire to reconnect a call even once. The only solution for this issue is to drop the call and reopen it.

There is not a single audio chat protocal that breaks up on bad connections this fast and I am having real trouble convincing anyone to use wire if it performs this bad on instable internet connections.

Please consider making wire resiliant to connection losses.
As it is now Wire is not useable when even a single participant has a bad connection

Wire version: Version 3.2.2860
Wire for Web Version 2018.07.26.0854
 Operating system: Windows 7
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Use wire audio call with one participant having a bad internet connection 
2.  The call will break up and the remaining participants will hear the reconnection sound (the connection will never reconnect though)
3.  The reconnect sound will continue to sound even though the disconnected participant is already available again.
4. The call has to be dropped and reinitiated to work again.

What is the expected result?

Wire should reconnect participants that have been disconnected and also only initiate the reconnect sound after at least 3 seconds

What is the actual result?

Call broke up

**Comment by bennycode** [comment]
Hi @tdw546, we made Wire better in dealing with poor network conditions. Fixes have been already applied in [our latest staging build](https://github.com/wireapp/wire-webapp/releases/tag/2020-08-21-staging.0) and will be released this week. 

We hope you will notice the difference!

Best,
Benny
