### ISSUE TITLE
[Feature request] PIN lock

### ISSUE THREAD

**Issue by KaKi87** [wireapp/wire-webapp#7922]
It would be nice to be able to lock Wire web with a 4 to 8 digit PIN. Thanks

**Comment by KaKi87** [comment]
Hello, any news on this ?

**Comment by bennycode** [comment]
We provide this feature for our Enterprise customers. Please reach out to our [Support Team](https://support.wire.com/) if you are an Enterprise customer and you want to have this feature enabled.

**Comment by KaKi87** [comment]
Seriously ? That's not fair.
