### ISSUE TITLE
error There are no binary scripts available.

### ISSUE THREAD

**Issue by gj-ramesh** [wireapp/wire-webapp#7972]
i have setup code as per instruction given you but i can't able to run yarn.
below issue error show.
![image](https://user-images.githubusercontent.com/59202472/71415209-92df5280-2680-11ea-975f-bf2991957e70.png)

![image](https://user-images.githubusercontent.com/59202472/71415318-1305b800-2681-11ea-8728-3d6a1489024f.png)

i have used node js version 13.5.0 and yarn version 1.21.1 with window machine.

any one help me

Thanks

**Comment by ffflorian** [comment]
@gj-ramesh you need to run `yarn` and not `yarn run`.
