### ISSUE TITLE
User presence indication

### ISSUE THREAD

**Issue by mirehasfun** [wireapp/wire-webapp#8]
I really like Wire for Web and use it regularly under Linux. The only thing that really bugs me is the missing user presence indication. Currently there's no way for me to tell whether a contact is online / offline or simply AFK/busy. 

Are there any plans to include such a feature?

**Comment by lipis** [comment]
Thanks for your feedback @mirehasfun. This is by design and there are no plans to implement presence indication.. sorry :/

**Comment by lipis** [comment]
The reason we evaluated presence indicator but decided not to implement it is to protect the user's privacy. We think that a presence indicator could be a privacy concern and we want our users to feel like the usage pattern of the application is not disclosed. We are evaluating introducing this as an opt-in feature, as we start to observe increased demand for it.
