### ISSUE TITLE
Username case sensivity

### ISSUE THREAD

**Issue by KaKi87** [wireapp/wire-webapp#8000]
Hello,

Despite Wire doesn't care about it, my username isn't `kaki87` but `KaKi87`.

The style isn't actually an ultra big problem and I wouldn't create an issue for that.

However, every time I login on Wire from a new device, I spend 10 minutes figuring out why the hell I get an `invalid input` error despite I copy/paste my password from my password manager and I never got *forgot password* issues since then.

And, the real issue is that the username login form is case-sensitive and doesn't accept that I write my username with case-sensivity.

Thanks in advance for fixing this behavior.

**Comment by KaKi87** [comment]
up

**Comment by bennycode** [comment]
Hi @KaKi87, the case-sensivity should be an easy fix. I will investigate in it.

**Comment by bennycode** [comment]
As promised I have investigated in this issue and developed a fix: https://github.com/wireapp/wire-webapp/pull/9349

Thanks for your report! 👍
