### ISSUE TITLE
@ffflorian, 403 Forbidden showing andAuthentication failed

### ISSUE THREAD

**Issue by cgsadmin** [wireapp/wire-webapp#8008]
@ffflorian, 
 that error is gone #1134 but now become other error 
Please help me to get done installation with create new registration 

![image](https://user-images.githubusercontent.com/20816988/72068786-d89c4c00-330b-11ea-96d1-69148b863bb4.png)

**Comment by cgsadmin** [comment]
@lipis , please help for this

**Comment by cgsadmin** [comment]
@lipis ,
Please let us know what to do for this issue

**Comment by cgsadmin** [comment]
@lipis ,
Please help me for this

**Comment by cgsadmin** [comment]
@herrmannplatz , @typfel 

Please help as soon as possible so we move to next

**Comment by cgsadmin** [comment]
@lipis , @herrmannplatz ,
Please help as soon as possible so we move to next

**Comment by cgsadmin** [comment]
@jspittka,
Please help asap

**Comment by cgsadmin** [comment]
> @ffflorian,
> that error is gone #1134 but now become other error
> Please help me to get done installation with create new registration
> 
> ![image](https://user-images.githubusercontent.com/20816988/72068786-d89c4c00-330b-11ea-96d1-69148b863bb4.png)

Can you please reply on this ???

**Comment by bennycode** [comment]
We don't tolerate spam in our project board.
