### ISSUE TITLE
Virtual effects camera prevents activation of physical USB camera

### ISSUE THREAD

**Issue by kekukui** [wireapp/wire-webapp#8036]
When the selected camera in Wire is a _**virtual effects camera**_*, and the virtual camera service is not running, I cannot change the selection in Wire to activate the attached USB camera.

* Youcam / Perfectcam / Manycam, etc

Wire for web version: 3.12.3423
Browser version: Wire desktop
Operating system: Windows 10

**Comment by Transisto** [comment]
Is this what you see?

![image](https://user-images.githubusercontent.com/388716/72915520-716c9780-3d0e-11ea-8658-639491fc30ec.png)

I think I have the same problem

https://github.com/wireapp/wire-desktop/issues/3487

**Comment by kekukui** [comment]
Yes, the camera selection list is disabled.  If I start (or uninstall) the virtual camera service, everything is back to normal.

**Comment by Transisto** [comment]
Same, thanks a lot for your contribution @kekukui 

Unfortunately after raising millions Wire still hasn't managed to hire people who care about acknowledging constructive bug reports.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/7018 https://github.com/wireapp/wire-webapp/issues/6156 https://github.com/wireapp/wire-webapp/issues/4454 https://github.com/wireapp/wire-webapp/issues/6282 https://github.com/wireapp/wire-webapp/issues/7083 https://github.com/wireapp/wire-webapp/issues/6837
https://github.com/wireapp/wire-desktop/issues/3709
https://github.com/wireapp/wire-desktop/issues/2703
https://github.com/wireapp/wire-desktop/issues/3735
https://github.com/wireapp/wire-desktop/issues/3472

**Comment by bennycode** [comment]
We improved the media device management a lot and tested it with [Snap Camera](https://snapcamera.snapchat.com/). Please report back if the problem still exists.
