### ISSUE TITLE
Audio Artifacts While Screen Sharing

### ISSUE THREAD

**Issue by jamesxu123** [wireapp/wire-webapp#8101]
Wire version: Version 3.12.3423
Wire for web version: Wire for Web Version 2020.01.22.1255
Operating system: Win 10 Pro, 1909
Which antivirus software do you have installed: Bitdefender

What steps will reproduce the problem?

1. Screen share
2. Wait a while...

What is the expected result?

Clean audio without artifacts

What is the actual result?

Static-y "clicking" noises start appearing a while into screen sharing. Sounds only appear when screen sharing and disappear as soon as screen sharing stops. Other side is also a Windows 10 desktop client. Problem has persisted through restarts.

**Comment by bennycode** [comment]
Thanks for your report. This issue is fixed with Wire v3.19.
