### ISSUE TITLE
[Bug] Messages not sending

### ISSUE THREAD

**Issue by KaKi87** [wireapp/wire-webapp#8129]
## Wire for web version

`2020-01-22-12-55`

## Browser version

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4033.0 Safari/537.36 Edg/81.0.403.0`

## Installed browser addons

```
Chrometana - Redirect Bing Somewhere Better
Clipbrd Beta
Clutter Free - Prevent duplicate tabs
Copy Link Text
Dark Reader
EditThisCookie
Enhancer for YouTube™
Hover Zoom+
IDM Integration Module
JSON Formatter
Je suis suivi
```

## Operating system

Windows 10

## What steps will reproduce the problem?

1. Select a conversation
2.  Type a message
3.  Submit

## What is the expected result?

The message is sent

## What is the actual result?

The message is displayed with semi-transparency and never sent

## Additional information

The client doesn't send an HTTP request when I click enter, but does send one when I start typing, and this one returns an HTTP 401 code, despite I'm logged in.

Then, I tried logging out and logging in again,which didn't solved the issue.

**Comment by bennycode** [comment]
@KaKi87 does this problem still exist on your end?

**Comment by KaKi87** [comment]
Honestly I don't know because I stopped using the app.

**Comment by bennycode** [comment]
That's fair to say. I will close the issue.
