### ISSUE TITLE
Filename of downloaded image / video `undefined`

### ISSUE THREAD

**Issue by MarcelRobitaille** [wireapp/wire-webapp#8170]
## Wire for web version

 2020-01-22-12-55 

## Browser version

Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

## Installed browser addons

Ublock origin
NoScript (wire.com whitelisted)

## Operating system

Linux Zeus 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux

## What steps will reproduce the problem?

1.  Click context menu on picture / video and click download

## What is the expected result?

I expect the downloaded file prompt to have a file name such as `Wire 2020-01-15 at 6_42 AM.jpeg`.

## What is the actual result?

The filename of the downloaded file is `undefined`.

This is just a small annoyance that I noticed changed recently in the Wire webapp. The filename used to follow the above format but now the default option in the prompt is `undefined`.

**Comment by bennycode** [comment]
Issue has been fixed. Thanks for your report!
