### ISSUE TITLE
[UX] Deleting message next to avatar removes avatar

### ISSUE THREAD

**Issue by mo3rfan** [wireapp/wire-webapp#82]
A minor UI issue, but could cause confusion to the user.

Suppose in a chat thread, if we have user A and B talking like:

```
User A: Hello
        How are you.
User B: I'm doing good,
        thank you.
```

if User B decides to delete the "I'm doing good" message, the conversation flow becomes:

```
User A: Hello
        How are you.
        thank you.
```

and "thank you" seems to appear as if User A said it. The User B's avatar and title should be updated to appear before it (in Android app, this works fine).

**Comment by bennycode** [comment]
Thanks for reporting, @PowerInside. This is a major issue which we now track in our ticket system.
