### ISSUE TITLE
Feature request: make wire webapp accessible via domain for which a TLS cert is issued signed by a CA exclusively owned by Wire

### ISSUE THREAD

**Issue by mirko** [wireapp/wire-webapp#8220]
There is reason not to trust the CAs that come with web browsers and are trusted by default.

While there is the way of certificate pinning, it's getting tedious to keep track of newly issued certificates, referencing and verifying their fingerprints.

I'm kindly suggesting Wire - probably already maintaining a couple of its very own CAs - adding/using a CA and issue a certificate used by a (custom) HTTPS endpoint, enabling users to access the content currently (only?) available under https://app.wire.com.

That would enable users to only trust a single CA in their webbrowser (profile), knowing the private key is under Wire's control, exclusively.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-desktop/issues/3897 https://github.com/wireapp/wire/issues/328

**Comment by bennycode** [comment]
We are keeping track of this ticket in https://github.com/wireapp/wire/issues/328 - Thanks for your report!
