### ISSUE TITLE
Login page not dark

### ISSUE THREAD

**Issue by KaKi87** [wireapp/wire-webapp#8251]
## Wire for web version

`2020-02-14-13-07`

## Browser version

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4056.0 Safari/537.36 Edg/82.0.432.0
```

## Installed browser addons

The list is very long.

## Operating system

Windows 10

## What steps will reproduce the problem?

1. Go to https://app.wire.com/auth/

## What is the expected result?

The login page is dark

## What is the actual result?

The login page is light

![2020-02-22 17_45_26-Greenshot](https://user-images.githubusercontent.com/21284089/75096010-3d012b00-559b-11ea-9926-dd00b2a3ead7.png)

**Comment by bennycode** [comment]
Having a bright UI is part of our corporate identity but you can switch the app theme once your are logged in:

![image](https://user-images.githubusercontent.com/469989/89887754-27c29c00-dbcf-11ea-9664-122101bac8c2.png)

**Comment by KaKi87** [comment]
Yes, but theme preferences should be preserved after session expiration so that user can have a dark page on **re-**logging on his account in which he enabled the dark theme.

**Comment by bennycode** [comment]
The preferences are saved for your account and synced so you will have a dark theme after relogin.

**Comment by KaKi87** [comment]
After, but not BEFORE.
