### ISSUE TITLE
Screen sharing in Linux

### ISSUE THREAD

**Issue by danielquinn** [wireapp/wire-webapp#830]
Wire is pretty awesome, but for it to be useful for my work, I need to be able to share my screen from my Linux desktop.

I'm happy to offer some trouble-shooting/debugging help on this one, but I'm afraid my Javascript-foo is not up to the task of implementing this myself.

**Comment by gregor** [comment]
Screensharing had been temporarly disabled with the upgrade to our new calling protocol. I will be reenabled in our next release in the coming days.
