### ISSUE TITLE
"Change language" option

### ISSUE THREAD

**Issue by 4llan** [wireapp/wire-webapp#831]
According to my locale, the Wire webapp is shown in portuguese. But I just wanted to choose what language I'll use.

There's some way of adding "language" to the options? :)

**Comment by gregor** [comment]
We do not expose this setting in the prefereces. Thanks for the request to do so.

As a workaround, you can always change the language by bookmarking a URL with a specific language flag set. https://app.wire.com/?hl=en for English for example.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
