### ISSUE TITLE
No Internet breaks desktop app

### ISSUE THREAD

**Issue by Wurzelkoch** [wireapp/wire-webapp#8318]
I am using wire-desktop, but I guess this is a webapp problem since I'm told desktop loads webapp. If I'm wrong, please move this issue over to wireapp/wire-desktop.

Until now, when internet connection broke, there was a green bar saying "No internet, wire won't be able to send or receive messages" or the like.
Since todays update, when I loose connection I get a full screen error message "couldn't connect to server" that won't disappear upon reconnect, but I have to quit and restart Wire.

Desktop app Version 3.14.2921
Wire for Web Version 2020.03.03.1405

**Comment by bennycode** [comment]
Offline capability is a long-term goal which cannot deliver right now but it's in our backlog!

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-desktop/issues/5087
