### ISSUE TITLE
Wire fails some security scans on Observatory by Mozilla

### ISSUE THREAD

**Issue by Myllyla** [wireapp/wire-webapp#833]
Wire receives reduced scores in some security scans on Observatory by Mozilla and third-party scans that you may want to look into:

[https://observatory.mozilla.org/analyze.html?host=wire.com](https://observatory.mozilla.org/analyze.html?host=wire.com)
[https://observatory.mozilla.org/analyze.html?host=app.wire.com](https://observatory.mozilla.org/analyze.html?host=app.wire.com)

**Comment by gregor** [comment]
@Myllyla Thanks for letting us know. We will continue to evaluate the situation and our server setup accordingly.
