### ISSUE TITLE
Feature Request: Chat background/bubbles

### ISSUE THREAD

**Issue by greenmanspirit** [wireapp/wire-webapp#845]
I think it would be awesome to give users the option to have a chat background and message bubbles like telegram, whatsapp, etc. This would all those users who like irc/slack like interfaces have that and people who like background/bubbles have that.

Thanks!
//adam

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
