### ISSUE TITLE
Images sometimes not loading and only showing placeholder

### ISSUE THREAD

**Issue by wjtk4444** [wireapp/wire-webapp#8452]
## Wire for web version

2020-03-23-15-58

If my memory is correct, this issue didn't happen before 2020-03-23

## Browser version

firefox 74.0-2 (happens on other browsers too; possibly in electron app and on mobile devices as well)

## Installed browser addons

found irrevelant during testing the issue on other browsers and operating systems

## Operating system

see above

## What steps will reproduce the problem?

1. Open any conversation on wire
2. Leave it open in background (unfocused tab, minimized, etc.). It may require you to wait a couple of minutes.
3. Have someone send you a message containing image
4. Focus the tab again, look at the message.

## What is the expected result?

Image

## What is the actual result?

Image placeholder

## Zoomed-out screenshot

tab focused, tab unfocused and tab focused again

![image](https://user-images.githubusercontent.com/20820296/77936108-eecdfe80-72a1-11ea-89c2-29fd2254ab1d.png)

## Console log (with ID and TOKEN replaced)

2x (for each image that did not load)

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://prod-nginz-https.wire.com/assets/v3/ID&asset_token=TOKEN&forceCaching=true. (Reason: CORS request did not succeed). 
```

**Comment by Maryushi3** [comment]
I can confirm that the same happens with Wire open in Hamsket 0.52.0 (which identifies as Chrome 73.0.3683) and 0.6.0 (Chrome 80.0.3987). Refreshing the tab with Wire makes images successfully reload. It never happened to me on mobile (Android) as far as I remember.

**Comment by gryzly123** [comment]
If this somehow helps with narrowing the problem, this also occurs on the Windows client since last update (3.16.3562 with web version 2020.03.23.1558)

**Comment by mythsunwind** [comment]
Thanks for all the reports, we are aware of this issue and currently working on a fix. As a workaround it usually helps to switch to another conversation and then back. This might be a bit less annoying than refreshing the tab.

**Comment by bennycode** [comment]
Issue has been fixed for https://app.wire.com/.
