### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by rosspi** [wireapp/wire-webapp#8470]
If I try to login (via the web or windows client actually, so perhaps its a server issue) it goes through the loading process
.. updating message.. etc.. looks like it's about to work, and let me in.
But then it just returns back to the login 'Welcome to Wire' screen.
Is anybody else having this issue?

**Comment by Ads20000** [comment]
I am getting this issue, I get the following (and this is about it) in my console:
```
Content Security Policy: Couldn't process unknown directive 'prefetch-src'
```

**Comment by mythsunwind** [comment]
Thanks for the reports. We found the issue and fixed it. The fix will be released this week. Sorry for the inconvenience!

**Comment by rosspi** [comment]
When is it getting released? It still does not work, currently.

**Comment by mythsunwind** [comment]
Release is planned for tomorrow (Tuesday the 21st). Sorry that it took so long!

**Comment by bennycode** [comment]
The release fixing the issue went live on [2020–04–21](https://medium.com/wire-news/wire-for-web-2020-04-21-f314105cb012).
