### ISSUE TITLE
"Clear Content" of group makes group inaccessible

### ISSUE THREAD

**Issue by monolied** [wireapp/wire-webapp#8500]
What steps will reproduce the problem?

1.  Clear Content of group

What is the expected result?

Group dialogue window is empty

What is the actual result?

Group dialogue window disappears and I'm unable to post in group

All known versions.
The same happens with "Archive Group". The only way I know to get access to the group back is phoning someone in the group and ask him to post something. Which is awkward, to say the least. The only situation the group chat should entirely disappear would be when I leave the group.

**Comment by ffflorian** [comment]
@monolied when clearing the content of a group, the group is moved to the archive. Did you check if the group is available in the archive or the search?

**Comment by monolied** [comment]
Ah, and I thought, "Archive" was moving to archive. I didn't expect "Clear Content" to be the same (and since I sometimes archive content, I thought the archive entry to be just these), and I didn't expect to not find the group anymore in the list of groups on the "Folders" tab. But you're right; there they are. So they aren't lost, and I'll get used to that.  I'd still maintain that behaviour is somewhat unexpected in many respects. Thanks a lot!
