### ISSUE TITLE
Feature request: show date in addition to time in front of messages older than today

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#862]
I've caught myself a couple of times already in the following situation:

- Scroll up to find a certain message. 
- Suppose it was sent not today, and you want to know, when this message was sent.
- Hover the message with your mouse, you will see time, for example "19:37". But when, which day?
- To learn which day, you have to scroll up all the way to the beginning of the conversation on that day, to see a header "February 27" - only then you know on which day that message was sent.
- This is highly not optimal, you have to scroll hundreds of messages just to find out the date, and hopefully you don't accidentally skip a date header.

Improvement proposal:

- For the today messages, show only time, like it is now.
- For messages older than today, show date in addition to time.

**Comment by bennycode** [comment]
Because of time constraints we unfortunately cannot work on this ticket for now. But we will keep track of it in our internal backlog! 🙂
