### ISSUE TITLE
Add setting to ignore expiring time on messages

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-webapp#8657]
Hi there,

since it is quite a chore to hand-archive all the expiring messages I would really appreciate a setting to disable this feature in bulk.

Here is my argument:
- Once you have sent a message, there is no guarantee that the other party is not hand archiving the message anyway (as I am doing on occasion)
- The message history is really hard to read if after some time some of the messages are missing
- When I casually skim some messages, determine to deal with that later and then find that it has vanished, that really is annoying.

Therefore time expiring messages offer no security benefit, but a big annoyance on my side, which is why I would like to disable that feature client side.

I know that I could use a fork that disables this, but I would much rather have this feature in the official client.

Wire version: Version 3.16.3630
Wire for web version: Wire for Web Version 2020.04.21.0832
Operating system:10.15.4 (19E287)
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1.  Contact sends me time expiring messagee
2.  I reply
3.  after some time I look at the chat history and wonder why it is the way it is (i.e. there seem to be messages missing)

What is the expected result?
All chat message should be in the history. I'd appreciate if they are marke as messages the other party would like to stay hidden, maybe they can be hidden by default, but they need to stay accessible and searchable.

What is the actual result?

Messages just vanish, I need to stay vigilant and copy them to a manual conversation log if I want to retain them.

Please provide any additional information below. Attach a screenshot if possible.

…

**Comment by 229c9cf0** [comment]
This is most relevant in groups, where one person sending disappearing messages by default makes it hard for everyone to follow the conversation later on. Being able to disable this at least in group settings would be great. (It's already possible to enforce disappearing messages via group settings, adding another "disabled" (vs. merely "off") option to that list would solve this for the group context.)

**Comment by bennycode** [comment]
Adding a setting to ignore the expiration of ephemeral messages defeats the purpose of expiring messages. We will not implement such a setting.
