### ISSUE TITLE
Microphone not working and greyed out in settings in chromium browser and wire desktop

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-webapp#8706]
![wire-chromium](https://user-images.githubusercontent.com/7195846/80960291-e28d1200-8e08-11ea-8465-a7d9c789a4a6.png)

This issue happens on all clients using chrome/chromium and live version of wire-web and wire-desktop. I have confirmations that this is also happening on linux.

Firefox is still able to select and use a microphone.

Firefox and wire-web is currently the ONLY way to make video/voice calls, because it is the only combination where a microphone works.

wire-web + wire-desktop urgently need a fix because this bug prevents voice and video calling.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-desktop/issues/2703

**Comment by tokariu** [comment]
ref.: https://github.com/wireapp/wire-desktop/issues/2703#issuecomment-628244722

**Comment by bennycode** [comment]
Hi @tokariu, we made massive improvements to our A/V selection on [2020–07–24](https://medium.com/wire-news/wire-for-web-2020-07-24-4ea8e37e6334). Does the problem for you still exist?

**Comment by bennycode** [comment]
We haven't received any feedback and assume that this bug is fixed now.
