### ISSUE TITLE
Crash with Opera

### ISSUE THREAD

**Issue by valentinbreiz** [wireapp/wire-webapp#871]
I don't know why but Wire Web often make my Opera Web Browser crash...

**Comment by herrmannplatz** [comment]
Which version of opera and which os? Does it crash when u start it or after some time of using it?

**Comment by valentinbreiz** [comment]
I use Opera v43.0.2442.1144 and Windows 10 v14986.1001

**Comment by Malaquita** [comment]
You wanted to have a screenshot:
![image](https://user-images.githubusercontent.com/30021432/28076354-b4ea6566-665e-11e7-83cc-0db04aaf65cd.png)
