### ISSUE TITLE
Messages not sending with high MTU

### ISSUE THREAD

**Issue by agates** [wireapp/wire-webapp#8739]
## Wire for web version

2020-05-07-09-41

## Browser version

Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

Also affects the desktop client in Flatpak/Appimage

## Installed browser addons

None on chrome/desktop application

## Operating system

Fedora 32 ThirtyTwo

## What steps will reproduce the problem?

1.  Open Wire at app.wire.com or desktop application
2.  Login
3.  Send a message

## What is the expected result?

Expect message to be sent

## What is the actual result?

Message is not sent, remains greyed out.  If I  edit it and remove all text, it will eventually be removed after some undetermined amount of time.

![Screenshot from 2020-05-07 12-07-38](https://user-images.githubusercontent.com/1422175/81324330-538d2d80-9086-11ea-91e5-a12ab8121226.png)

**Comment by agates** [comment]
I also have pihole DNS server on the network and have checked that no related DNS requests are being blocked.

**Comment by agates** [comment]
It works if I connect via VPN.... very confusing.

I have manually disabled IPv6 and bypassed my DNS server to verify and I'm still having the problem.

Note, Wire on Android is working fine on the same network with no VPN.

**Comment by agates** [comment]
I've figured it out.  My MTU setting of 9000 was breaking it.

Setting it back to my network default of 1500 fixed it.

**Comment by bennycode** [comment]
Hi @agates, thanks for your detailed report. Is this problem 100% reproducible for you and does your MTU setting also affect other messaging apps (like Slack, Hangouts, ...)?

**Comment by agates** [comment]
@bennyn yes I have been able to reproduce it across multiple computers with no exceptions so far.  It has never affected any other messaging apps -- the only other one I currently use is Signal, but in the past Skype and Hangouts have worked fine.

**Comment by chienpanglee** [comment]
Hi @agates setting jumbo frames can sometimes be tricky depending on if intermediate hops are configured the same and also different applications/protocols may react differently. 

In theory, if other Wire clients worked with your setup, it's really the same protocol for WebApp/Desktop except that they work together with Chrome browser. As you also pointed that they all worked when going via VPN. In this case, I assume enabling VPN actually sets MTU back to 1500 so I'd recommend that you stick to the default MTU.

**Comment by agates** [comment]
@chienpanglee yeah I had the MTU set high primarily for other local traffic reasons.  I had only just realized the change separately as I hadn't used Wire on that machine prior to the MTU increase and everything else worked fine.

**Comment by bennycode** [comment]
At the moment we have no technical solution to it. We recommend **not** setting jumbo frames and will take this info into our FAQs. Thanks for this very detailed report.
