### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by TechnologyClassroom** [wireapp/wire-webapp#8741]
It would be nice if the Wire webapp became [LibreJS](https://www.gnu.org/software/librejs/) compliant.

Instructions:
- [Setting your JavaScript free](http://www.gnu.org/software/librejs/free-your-javascript.html)
- [Setting your JavaScript free from the LibreJS manual](https://www.gnu.org/software/librejs/manual/html_node/Setting-Your-JavaScript-Free.html)

**Comment by bennycode** [comment]
Thanks for the hint but we are using a lot of third party components which makes it impossible for us to guarantee LibreJS' main condition which is:

> Please ensure these licenses are free and GPL-compatible.

**Comment by TechnologyClassroom** [comment]
I can make issues with upstream third-party components.  Do you have a list?
