### ISSUE TITLE
Testing login credentials

### ISSUE THREAD

**Issue by qalqi** [wireapp/wire-webapp#8780]
## Wire for web version
0.1.0

## Browser version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

## What steps will reproduce the problem?

1.  cloned and installed wire-webapp and wire-server. changed env variables to local. What are the testing login credentials and how to create?

## What is the expected result?
To be able to login with created/mock login credentials to test app

## What is the actual result?
Unexpected error

**Comment by bennycode** [comment]
Hi @qalqi, are you trying to run our project locally?

**Comment by qalqi** [comment]
yeah

**Comment by bennycode** [comment]
We updated our instructions on how to run Wire locally: https://github.com/wireapp/wire-webapp#development - Hope this helps!
