### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [wireapp/wire-webapp#8889]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by bennycode** [comment]
Hi @thomasrockhu, thanks for pinging us about the rate limiting. We will have a look at your GitHub app integration.

**Comment by bennycode** [comment]
Hi @thomasrockhu, we installed the [Codecov Application](https://github.com/apps/codecov) from GitHub's marketplace. What else should we do to migrate to it? Is it necessary to include code in our GitHub workflows?

**Comment by thomasrockhu** [comment]
@bennyn, that should be all! Thanks for getting back to me.

**Comment by bennyn** [comment]
Great. As we are using the Codecov GitHub App is it safe to remove our GitHub Webhook to "https://codecov.io/webhooks/github"?
