### ISSUE TITLE
Add new language for wire

### ISSUE THREAD

**Issue by temporallyaccount** [wireapp/wire-webapp#9124]
#### Requested language
Sinhala language

#### Requested Projects
https://crowdin.com/project/wire-account
https://crowdin.com/project/wire-webapp
https://crowdin.com/project/wire-launch
https://crowdin.com/project/wire-team-settings

#### Other Projects
https://crowdin.com/project/wire-cs
https://crowdin.com/project/wirecom

#### Additional Details
Sinhala language currently enabled for wire desktop

**Comment by lipis** [comment]
Hi @Rru247 we added Sinhala language to the following projects..

- https://crowdin.com/project/wire-webapp/si-LK
- https://crowdin.com/project/wire-desktop/si-LK
- https://crowdin.com/project/wire-launch/si-LK
- https://crowdin.com/project/wire-cs/si-LK

Please note that we need to reach a certain amount of percentage for each project to be translated before it will be merged and published on production! Feel free to join and start translating, and report back when you feel it's ready.

**Comment by temporallyaccount** [comment]
@lipis thank you ^_^
