### ISSUE TITLE
unnecessary and painful limitations

### ISSUE THREAD

**Issue by f4th0m** [wireapp/wire-webapp#9177]
Wire version: Verzió: 3.18.0-60b7602d.0-60b7602d
Wire for web version: Wire Webes verzió 2020.06.24.0933
Operating system: Linux/Mageia Cauldron
Which antivirus software do you have installed: Clamd

Wire does not allow more than 10 files to be shared at once, why? Since unlimited number of photos can be shared anyway why tehre is a painful limit of 10?
Wire only let upload files with max size 25 megs, but it shares happily a 200 megs video from my mobile (android), this also seem to be a really unnecessary limit again. 

What steps will reproduce the problem?
Always

What is the expected result?
No limitations or at least reasonable limits
...

What is the actual result?

...

Please provide any additional information below. Attach a screenshot if possible.

...

**Comment by bennycode** [comment]
@f4th0m if you upgrade your personal account to a [team account](https://app.wire.com/auth/#createteam) you will be able to share 100 MB of files.
