### ISSUE TITLE
Audio calls with multiple users broken by network issues

### ISSUE THREAD

**Issue by Jasmine722** [wireapp/wire-webapp#9180]
Wire version: 3.18.2925-1 (and previous versions during the last 3 months at least)
Operating system: Manjaro (Windows 10, Windows 7 also affected)
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  create a call with at least 3 participants
2.  one of the participants has network/internet issues, resulting in interruptions and high latency
3.  after the network interruption one or more participants can no longer hear the other participants and have to reconnect to the (still) existing call. This also affects the audio connection between unaffected users with stable internet connections.

What is the expected result?

The audio call should be stable for participants with a stable connection, even if one participant has connection issues.

What is the actual result?

Group audio calls that include a single user with an unstable internet connections are very unreliable, making conference calls with customers impossible.

Additional example:

Alice, Bob and Carol create a wire group and start an audio call.
Carol has internet issues and sometimes Carols connection breaks up for a few seconds.
After some time (not always reproduceable) Alice can no longer hear Bob or Carol, although Bob and Carol can still hear Alice. Bob can still hear Carol and Carol can hear Bob. This can also hapen with Bob, where Alice and Carol can still communicate but they can no longer be heard from Bob.
Although the connection from Alice and Bob are stable, they are also affected by the connection issues of Carol.

Please note that this issue happens to participants of the call that have a stable connection.

**Comment by bennycode** [comment]
Hi @Jasmine722, we are now indicating in our UI if a user has a bad network connection during a call. We are also constantly improving the robustness of calls. You will get a significant improvement once we release our desktop v3.20. 🙂
