### ISSUE TITLE
Webapp keeps audio channel open when it's no longer used

### ISSUE THREAD

**Issue by Bugsbane** [wireapp/wire-webapp#924]
Both Firefox and Chrome (not sure about Edge / IE / Opera these days) show a speaker icon in any tab currently broadcasting sound so users know which tabs in particular sounds are coming from.

Currently, Wire's web app undermines this, showing the audio being used constantly, even when the tab isn't being used to make any calls, or any notification sounds. Right now I'm seeing it on a Wire tab I have open in Firefox, which hasn't received a new message in over 12 hours.

![spectacle b22402](https://cloud.githubusercontent.com/assets/401733/24118846/a4c90642-0d85-11e7-84d9-0d34bcfd594f.png)

I'm on Firefox 53 on Ubuntu.

**Comment by gregor** [comment]
This should be fixed in the latest release that we just shipped today. Please reopen if it still happens after a page refresh today. WIth some steps to reproduce on how you get the icon to show up and not go away so we can take another look.
