### ISSUE TITLE
Make previous chat history make visible for new joined member of the group

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#9269]
Hello is it possible to make previous chat history make visible for new joined member of the group?

**Comment by Transisto** [comment]
not currently but it could be an interesting feature.

**Comment by bennycode** [comment]
@someone23231 Thanks for your submission. I took the liberty of renaming the title of this issue to make it easier to find. To answer your question, it is intentional that messages are only available to users from the time the user joins the conversation.
