### ISSUE TITLE
Wire support for Safari

### ISSUE THREAD

**Issue by balupton** [wireapp/wire-webapp#930]
What exactly is holding Safari support back for the web client? This isn't mentioned anywhere. Cheers!

**Comment by mat1th** [comment]
I think of the lack of WebRTC support. See https://webkit.org/status/#specification-webrtc

**Comment by gregor** [comment]
We removed Safari support when we moved to E2EE as we highly depend on IndexedDB. The implementation of this browser feature in Safari was lacking. Safari is since providing what we need but we never reenabled it due to the required testing in order to ensure that each of our releases is shipped with the desired quality. A desicision we will have to reeavaluate at some point again but it currently was not on our immediate agenda. I will bring it up within the team.

Microsoft Edge also is not (yet) supporting webRTC but calling features are simply disabled in this case.

**Comment by balupton** [comment]
great, thanks for the detailed response

for me, I really enjoy Safari - and the web clients of skype, telegram, whatsapp, slack all support it - so wire is the only one missing for me

keep up the great work!

**Comment by sirnacnud** [comment]
I would also prefer Safari support. I use Safari as my main browser and it would be nice to be able to use Wire without having to run a separate browser (desktop app doesn't solve this either since it is an Electron app and not native).

**Comment by mat1th** [comment]
In the next release Safari does also support [WebRTC](https://webkit.org/blog/7627/safari-technology-preview-32/) and the Web Cryptography API. It already supports IndexDB 1 and 2. So there are no big things that are needed to support Safari.

**Comment by gregor** [comment]
Thanks again for your request. While there is no techincal limitation keeping us from re-enabling Safari, we have so far refrained from doing so in order avoid increasing our test effort needed before every release.

We will continue to evaluate if and how we can add Safari back to the list of browsers that can access Wire for Web.

I will go ahead and close this issue as an act of housekeeping and strive to track bugs in the product using the issues here.

**Comment by michaelahlers** [comment]
Can Safari support be restored with an “as-is, use at your own risk” warning? For the careless who—like me—want to use it anyway, set Safari's user agent to a value resembling Chrome.

**Comment by jcredmond** [comment]
Unfortunately, setting the user agent to chrome doesn't work on Mojave / Safari 12.

**Comment by michaelahlers** [comment]
Sigh. Found that out, too, during the public beta.

**Comment by neongreen** [comment]
It works on Safari Technology Preview now if you set the user agent to Chrome, but the UI is slightly buggy.

**Comment by moorage** [comment]
@gregor does the close on this issue. Mean that safari won’t work for the foreseeable future?
