### ISSUE TITLE
Unconnected people show up in the user search input when creating a group

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#9344]
I see the contact I'm looking in the lest for less than a second then it disappear.

**Comment by bennycode** [comment]
@Transisto in which part of the app are you looking for your contacts? Do you search them from our Start UI (left side of the application)?

**Comment by Transisto** [comment]
No, in the part where I add them to a group. (desktop app)

I can try finding same bug issues where it was fixed on Android,

https://github.com/wireapp/wire-android/issues/2858

**Comment by bennycode** [comment]
@Transisto we have several places to add people to a group.

**Create Group**

![image](https://user-images.githubusercontent.com/469989/90258057-4bdce200-de48-11ea-9418-86e56b41287a.png)

**Add participants**

![image](https://user-images.githubusercontent.com/469989/90258091-5b5c2b00-de48-11ea-8b0d-9e2a19d7645e.png)

Which is the one you are having problems with?

**Comment by Transisto** [comment]
BOTH!

From : https://github.com/wireapp/wire-android/pull/2874

> A lesson for the future: Changes in UI should be tested both with team and private accounts.

What about : **Fixes in UI should be applied to both web and mobile app?**

It's the same exact problem 1:1 on mobile that is still on Desktop/web

https://github.com/wireapp/wire-android/issues/2858

#7333  User search show 10 globals before existing contacts [Major usability issue]

Are any of you guys using your own software for these things not to jump in your face?
