### ISSUE TITLE
Feature request: more reactions

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#938]
Today we have only one reaction: ❤️ 

I'd love to see more reactions, ideally support any emoji from #541 as a reaction. Keyboard integration is a must, for example if to enter emoji you type `:`, to add emoji reaction you type `+:`.

By the way, it is worth looking at [Slack's reactions](https://get.slack.help/hc/en-us/articles/206870317-Emoji-reactions) for an inspiration 🙂

**Comment by gregor** [comment]
@maximbaz Definitely on our wishlist as well. If you take a close look at the protocol implementation in our protobuf at https://github.com/wireapp/generic-message-proto/blob/master/proto/messages.proto#L213 you will see that the initial implemtation was architected with this in mind. It is once more just a matter of priorities and product design decisions as to whether and when a feature like tis would find its way into Wire. Votes always help to make us understand the user need or such an expansion of the feature.

**Comment by bennycode** [comment]
Because of time constraints we unfortunately cannot work on this ticket for now. But we will keep track of it in our internal backlog! 🙂

**Comment by danielmcoelho** [comment]
Can't live without reactions – this is a huge feature that it's making my company not shift from Slack to Wire. Even GitHub has them 🥇

**Comment by livejamie** [comment]
This is also a showstopper for us, unfortunately. 

Slack, Discord, Facebook Messenger, even Keybase support them.
