### ISSUE TITLE
UI becomes unresponsive when switching between conversations

### ISSUE THREAD

**Issue by norstbox** [wireapp/wire-webapp#9390]
## Wire for web version

2020-07-24-13-46

## Browser version

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

## Installed browser addons

None at all

## Operating system

Windows 10, 1909

## What steps will reproduce the problem?

1.  Open conversation with long enough history (hundreds of messages)
2.  Scroll back to load history
3.  Switch to another conversation

## What is the expected result?
Conversation opens immediately.

## What is the actual result?
Conversation opens with noticeable delay, meantime UI becomes unresponsive. Delay duration correlate with history size.

**Comment by bennycode** [comment]
Thanks for reporting. We are aware of this and will handle performance tickets once we migrated our frontend technology from "Knockout" to "React".
