### ISSUE TITLE
Shortcut for SILENCE prevents typing letter "S" with accents

### ISSUE THREAD

**Issue by Wasacz** [wireapp/wire-webapp#94]
Currently, the keyboard shortcut for event of type `SILENCE` on Windows is set to `Ctrl`+`Alt`+`S` (please see: [Shortcut.coffee:125](https://github.com/wireapp/wire-webapp/blob/5170a02b73d6bde78e79d25200b04bd839d3766f/app/script/ui/Shortcut.coffee#L125)). This effectively becomes `AltGr`+`S` which is the combination for entering a letter "S" with accents.

For example, in Polish locale it is not possible to type letter "ś" using Wire.

Please note that this applies to the desktop app, too.

**Comment by lipis** [comment]
It seems like our Polish guru Mr. @zbsz is too busy with Android and not using our web client :D

Thanks @Wasacz for reporting it.

**Comment by bennycode** [comment]
@Wasacz Which shortcut would you like to use for silencing conversations?

**Comment by Wasacz** [comment]
@bennyn The simplest way to go would be to replace Alt with Shift but it's
already taken in Firefox.

There is Ctrl+Alt+Dot for ignoring a call, so maybe similar Ctrl+Alt+Comma?
Another reference could be Gmail which is using Ctrl+Dot and Ctrl+Comma
globally so I guess these combinations are safe to use.

Anyway, I would reconsider the need of so many keyboard shortcuts in the
web app. For example, do you add new contacts that frequently so you need
to do it by using a keyboard shortcut?

**Comment by speedy9** [comment]
I would also love a very simple option in the settings: "Turn off hotkeys". I never use them anyway :)
I also see no use for "Archive" shortcut. Such options are not commonly used I think.

**Comment by speedy9** [comment]
Hi. Can we really get at least an option in settings to turn off keyboard shortcuts? This issue is sooooo annoying and really drives me mad sometimes as it interferes with AltGr+"s" and AltGr+"n".
Pleeeease, change this.

**Comment by bennycode** [comment]
Hey @speedy9, I can fully understand your anger and really feel with you. Unfortunately our design team told us today that there is no plan to redesign keyboard shortcuts any time soon. 😢
