### ISSUE TITLE
Import more than one contact from Gmail at a time

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-webapp#943]
To import multiple contacts from Gmail you have to:
1. Click the cog
2. Go to Options
3. Click Import from Gmail.
4. Choose one of the people
5. Click Connect
6. Click the cog again
7. Go back to Options
8. Click Import from Gmail again

You get the idea…

I'd find it much easier if I would just not get redirected out of the Options pane and over to the not yet connected person. Just let me stay in Otions after step 5, so that I can go straight back to step four again, not go trough all of steps 1-5 again.

Even more logical and less time consuming would it be If step four would let me select more than one person before clicking Connect to connect to all of them at once.

**Comment by helenakos** [comment]
@forteller Thanks, this is good feedback. I'll share this with the team.

**Comment by gregor** [comment]
The behavior with import is going to change. Thereby I will close this ticket as of now.
