### ISSUE TITLE
How to create your own version of the desktop application?

### ISSUE THREAD

**Issue by Aisse-258** [wireapp/wire-webapp#9435]
Hello. I want to make some changes to the program interface for the needs of the research group of my university. Please tell me how best to do this so that these changes are applied to the desktop version. I need to be able to distribute my version of the application so that it does not depend on the version on the server. When forked the wire-desktop, I have no access to the interface, since it is loaded from the server. And I can't make wire webapp an independent application.

**Comment by bennycode** [comment]
Hi @Aisse-258, you can run our [desktop application](https://github.com/wireapp/wire-desktop) with `yarn start:localhost`. When you do that, then you can chose to use a locally hosted webapp (which you can start [as described here](https://github.com/wireapp/wire-webapp#development)) using its "Developer" menu:

![image](https://user-images.githubusercontent.com/469989/90398471-c6e90700-e099-11ea-9407-32dbf5109030.png)

Best,
Benny
