### ISSUE TITLE
Receiver of timed (and NOT yet expired) message sees scribble

### ISSUE THREAD

**Issue by sebastian-brandt** [wireapp/wire-webapp#9450]
Wire version: 3.12
Operating system: Observed with Windows 10 and Linux
Which antivirus software do you have installed: Windows 10: Microsoft Defender, Linux: None

What steps will reproduce the problem?
1. Receiver has chat window open
2. Sender sends a timed message to same chat as receiver has open

What is the expected result?
Receiver should see the message text, as it has not yet expired.
As per documentation https://support.wire.com/hc/en-us/articles/213216845-Send-a-timed-message the scribble should be shown only when the message has expired: _"[...] The sender will see a timer to the left of the message, and once expired, the message will be replaced by a scribble that disappears once the message has been read. [...]"_

What is the actual result?
Receiver will not immediately see the message, but a scribble and has to manually "unhide" the message by clicking on the scribble.

**Comment by bennycode** [comment]
Hi @sebastian-brandt, can you reproduce the problem with Wire v3.19?

**Comment by bennycode** [comment]
I have not received an answer and therefore assume that the problem has been resolved.
