### ISSUE TITLE
Shared image EXIF orientation not honored on Windows

### ISSUE THREAD

**Issue by vith** [wireapp/wire-webapp#9451]
## Version

Wire version: 3.0.2828

Wire for web version: 2018.05.24.1549

Operating system: Windows 10 1803

Which antivirus software do you have installed: None

## What steps will reproduce the problem?

1. Take a (JPEG) picture with Android Camera app
2.  Share picture through Wire/Android
3.  View picture on Wire/Windows

## What is the expected result?

Picture is rendered with correct orientation

## What is the actual result?

On Windows, the picture is rendered with an incorrect orientation. On Android, it is correct, even inside Wire. Downloading the image on Windows and opening it in Chrome, it is displayed correctly.

## Please provide any additional information below. Attach a screenshot if possible.

The file has EXIF field:
Orientation | Rotate 90 CW

**Comment by ffflorian** [comment]
Hi @vith, I can't reproduce this on the current version of the WebApp. Can you try and see if this problem still exists for you?

**Comment by vith** [comment]
Going back to 2018-06-07 in the Wire chat where this happened, the problem image won't render or download anymore.

But I can't reproduce the problem with new photos from my Pixel 2 or example images from https://github.com/recurser/exif-orientation-examples

I'll go ahead and close this, seems like it got fixed since then. 👍
