### ISSUE TITLE
Call/hangup keyboard shortcut

### ISSUE THREAD

**Issue by predator8bit** [wireapp/wire-webapp#9454]
Can we have a keyboard shortcut for making and ending calls? It would be really helpful for people who can't use a mouse. I know a person who can use Wire only for text messaging because of this and they would like to have the ability to make calls.

Wire version:  3.0.2816
Operating system: Arch Linux

![wire](https://user-images.githubusercontent.com/27356954/36123711-d27ca6ea-104d-11e8-87be-788f02c921c2.png)

**Comment by bennycode** [comment]
Hi @predator8bit, can you share your workaround scripts with us?

**Comment by predator8bit** [comment]
It was just a shell script that moved the cursor to where the call/hangup button would be and clicked, then it moved the cursor away again. I assigned this .sh file to a simple keyboard shortcut in my settings. I don't have the file anymore since we moved on to using a different chat application.

**Comment by bennycode** [comment]
I'm glad you found a chat solution that works for you. I also informed our product management that we should introduce hotkeys for calling. Thanks for bringing that up.
