### ISSUE TITLE
Multiple devices fingerprint verfication flaw

### ISSUE THREAD

**Issue by Nurmagoz** [wireapp/wire-webapp#9455]
(This is actually a problem and a feature request on the same time)

Wire version: Version 3.3.2872
Wire for Web Version 2018.11.05.1121
Operating system: Debian 9

What steps will reproduce the problem?

1.  add a friend
2.  let your friend login to his account through multiple devices
3.  you will see multiple devices with multiple fingerprints as well (naturally)
4. verify one of his devices
5. he can still talk to you from other devices (which are unverified) but you cant distinguish which one of his messages verified and which one is not
6. attacker can text you through the unverified device , and you think its the verified one (since there is nothing indicating something is wrong)

Thats a verification flaw by design

What is the expected result?

- Add flag/sign to the unverified and verified messages
- Add an option to deny any unverified messages until the user get verified

What is the actual result?

user can easily get tricked and rekt by a MITM

**Comment by Nurmagoz** [comment]
@shvchk 

> Just  a note. You can distinguish between fully verified and not verified  chats by blue shield icon, which appears only when you have verified all  your friend's devices.

Not really , you can only see which device has been verified but you cant see which text is coming from (the verified or the non-verified) : 

![wire1](https://user-images.githubusercontent.com/11895339/49334930-a03f2000-f5d9-11e8-84f6-e691c2a96911.png)

![wire2](https://user-images.githubusercontent.com/11895339/49334933-b056ff80-f5d9-11e8-80b6-e3647f6bae58.png)

**Comment by bennycode** [comment]
As @shvchk mentioned, verifying all your contact's devices is key here. If you do that and there is a new device added to the conversation, you will get a pop-up from Wire telling you that there are untrusted devices when you try to send a message.

**Comment by Nurmagoz** [comment]
> If you do that and there is a new device added to the conversation, you will get a pop-up from Wire telling you that there are untrusted devices when you try to send a message.

I dont have this, any idea why? 

OS: Debian 10
Version 3.19.2928
Wire for Web Version 2020.09.21.10.08
