### ISSUE TITLE
Suddenly stopped working in Rambox

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-webapp#949]
I've been happily using Wire in [Rambox](http://rambox.pro/) for some tim now. But when I opened it now I just got the message "This browser is not supported."

Rambox is a very useful application to run any webapp in different tabs in, and get desktop notifications. It is based on this software:

Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

I hope you'll be able to make Wire work on this setup again soon. Thank you very much!

**Comment by MakisH** [comment]
The respective issue on Rambox: https://github.com/saenzramiro/rambox/issues/762

**Comment by herrmannplatz** [comment]
Could you just recheck.

**Comment by MakisH** [comment]
Still the same problem.

**Comment by bennycode** [comment]
That's strange because we just set our lower bound to Chrome 53: https://github.com/wireapp/wire-webapp/releases/tag/2017-03-28-14-23

Can you run Rambox with Chrome devtools?

**Comment by MakisH** [comment]
I can see the Chrome devtools pane in Rambox, yes. How can I help?

**Comment by bennycode** [comment]
Cool! Can you please check this version number?

![capture](https://cloud.githubusercontent.com/assets/469989/24413654/60d31862-13dc-11e7-973f-d6ce163229d8.PNG)

**Comment by MakisH** [comment]
I can't find it, I actually can't understand the structure of the code right now, because it contains also the Rambox-related code. This may help though (look at the user agent).

![wire-rambox](https://cloud.githubusercontent.com/assets/4943683/24427153/404cc060-140a-11e7-8f4c-fe7ae6e9157a.png)

**Comment by bennycode** [comment]
Thanks! This helps already a lot. When did our app work for you the last time?

**Comment by bennycode** [comment]
I just checked Rambox. It reports itself as:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
```

Result from https://app.wire.com/test/agent/ is:

```json
{
  "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36", 
  "bot": false, 
  "browser": {
    "name": "Chrome", 
    "version": "53.0.2785.143"
  }, 
  "is": {
    "android": false, 
    "android_tablet": false, 
    "bingbot": false, 
    "blackberry": false, 
    "blackberry_tablet": false, 
    "chrome": true, 
    "crawler": false, 
    "desktop": true, 
    "electron": true, 
    "firefox": false, 
    "googlebot": false, 
    "ie": false, 
    "ios": false, 
    "ipad": false, 
    "iphone": false, 
    "linux": false, 
    "mobile": false, 
    "opera": false, 
    "osx": false, 
    "phone": false, 
    "safari": false, 
    "tablet": false, 
    "windows": true, 
    "windows_phone": false, 
    "wrapper": true, 
    "yahoobot": false
  }, 
  "os": {
    "name": "Windows", 
    "version": "10"
  }, 
  "platform": {
    "name": "Windows", 
    "version": "10"
  }, 
  "wrapper": {
    "name": "Electron", 
    "version": "1.4.15"
  }
}
```

We will soon find the issue why [today's fix](https://github.com/wireapp/wire-webapp/commit/fbb63b02db96e39d04d7b52dff16688d567a7b3e) doesn't work. 😎

**Comment by MakisH** [comment]
It was working perfect yesterday noon-afternoon (german time).

By the way, just to be clear, my Rambox also says "Chromium 53", like in the case of the original poster (Rambox 0.5.3).

**Comment by forteller** [comment]
Yeah, last time it worked for me was earlier the same that that I created this issue :)

**Comment by rd-su** [comment]
Any news?

**Comment by lipis** [comment]
Should be fixed in https://github.com/saenzramiro/rambox/pull/792

**Comment by lipis** [comment]
A workaround until it's merged would be to create a new `_Custom Service` that points to `https://app.wire.com`

<img width="509" alt="screen shot 2017-04-03 at 11 31 08" src="https://cloud.githubusercontent.com/assets/125676/24603455/21b62550-1861-11e7-9098-b3ccabc5c24d.png">

**Comment by fungs** [comment]
I'm still using version 0.5.3 of Rambox and Wire started working again. Maybe/likely Wire has adjusted the required browser version? Anyways, things are fixed on both sides now, but Rambox has not released the fix in a stable release, yet. I guess that this issue can be closed, thanks to everyone!

**Comment by forteller** [comment]
Me too :)

**Comment by bennycode** [comment]
Happy to see that it works now. 🎉
