### ISSUE TITLE
Add wire emoticons and option to import custom static & animated emoji/stickers packs

### ISSUE THREAD

**Issue by Aikatsui** [wireapp/wire-webapp#9564]
Feature request for Emoji in web-app repository was closed several days ago https://github.com/wireapp/wire-webapp/issues/7014 - 16 upvotes
Add Stickers in android repository - https://github.com/wireapp/wire-android/issues/1597 - 8 upvotes
Allow for usage of stickers like telegram in android repository - https://github.com/wireapp/wire-android/issues/1925 - 5 upvotes

It seems wire intend to keep 20th century communication application however **we don't interest to use that platform even for business environment due only encryption**. https://github.com/wireapp/wire-webapp/issues/7014#issuecomment-685166140
(This is the first feedback for wire administrators rather than developers because such essential FR ignored several times)

Consider let users to import custom static & animated emoticons/stickers because we cannot expect wire may spend time for design some dozen of sticker packs then doesn't need to spend $ for that. Such feature also available on telegram.
https://github.com/TelegramOrg

- [ ] Add a simple wire own emoticons list as default. it ensure same expression around the platform; avoid <img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/microsoft/209/face-with-tears-of-joy_1f602.png" width=28 >  <img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/emojidex/112/face-with-tears-of-joy_1f602.png" width=28 >
see https://emojipedia.org/face-with-tears-of-joy/
- [ ] Let users to import custom static & animated emoji/stickers packs (Important)

https://openmoji.org (you can check availability to integrate if unable to create default emoticons list)
https://awesomeopensource.com/projects/emoji
https://www.joypixels.com

![](https://user-images.githubusercontent.com/20155474/50403305-9b4e3600-076b-11e9-9d28-2d0a093d4e31.png)

**Comment by KizunaH** [comment]
****

**Comment by bennycode** [comment]
Our roadmap for this year does not include to implement sticker packs. Sticker packs are a nice-to-have feature but not essential for secure enterprise communication. We therefore invest our development resources in the implementation of [Messaging Layer Security](https://en.wikipedia.org/wiki/Messaging_Layer_Security) instead of implementing support for stickers.

**Comment by pYFZOS5** [comment]
https://github.com/wireapp/wire-android/issues/1925

**Comment by pYFZOS5** [comment]
https://github.com/wireapp/wire-android/issues/1925
