### ISSUE TITLE
Question: Is there any API for integration in other products

### ISSUE THREAD

**Issue by Baumgaer** [wireapp/wire-webapp#9709]
Hi there,

is there any API to be able to integrate the webapp into the own webapp similar to jitsi?
I need to able to:

1. Choose a roomname by my own
2. set a password for each room
3. catch some kind of "hangup", "conferenceJoined", "passwordRequired"-event
4. set an avatar and diesplay name for each participant

regards

**Comment by bennycode** [comment]
Hi @Eluminati, you cannot integrate our webapp as such into something but you can build your own app using our [api-client](https://www.npmjs.com/package/@wireapp/api-client) and [core module](https://www.npmjs.com/package/@wireapp/core). For rooms, I recommend using our [guest rooms](https://medium.com/@wireapp/extend-work-conversations-securely-with-wire-guest-rooms-6639740b0864) feature.

Hope this helps!
