### ISSUE TITLE
Images never load in the webapp

### ISSUE THREAD

**Issue by jack5432109** [wireapp/wire-webapp#981]
I have been using wire in multiple devices. 
I observed that the images in communication never load on the web-app 
using chrome Version 56.0.2924.87
and on version that the application, [Franz](http://meetfranz.com/) is based on.

**Comment by herrmannplatz** [comment]
Not sure whats causing this and its quite hard to debug this in Franz.

**Comment by bennycode** [comment]
@jack5432109 How long have you been waiting for the images to download?

**Comment by jack5432109** [comment]
@bennyn couple to maybe like 15 minutes.

nevertheless, the images load as expected now. 
now using [web-app](https://app.wire.com/) Version 2017-04-07
