### ISSUE TITLE
Make the video mirrored so it's more natural

### ISSUE THREAD

**Issue by trosel** [wireapp/wire-webapp#983]
On my macbook, the web camera video is flipped. 

It's more natural and normal for the video to be mirrored (as if it's a mirror).

So when you raise your right hand, you see your hand on the right side of your video feed.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
